### ISSUE TITLE
NRE bug

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1075]
```
Error decompiling System.Void NEEA.NCRE.CBT.Testing.ParsingForm::Timer1_Tick(System.Object,System.EventArgs)
 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.TranslateSwitch(BlockContainer switchContainer, SwitchInstruction inst) in StatementBuilder.cs:line 115
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitSwitchInstruction(SwitchInstruction inst) in StatementBuilder.cs:line 110
   at ICSharpCode.Decompiler.IL.SwitchInstruction.AcceptVisitor[T](ILVisitor`1 visitor) in Instructions.cs:line 1351
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 55
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in StatementBuilder.cs:line 858
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockContainer container, Boolean isLoop) in StatementBuilder.cs:line 843
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in StatementBuilder.cs:line 746
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor[T](ILVisitor`1 visitor) in Instructions.cs:line 674
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 55
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in StatementBuilder.cs:line 60
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitTryCatch(TryCatch inst) in StatementBuilder.cs:line 314
   at ICSharpCode.Decompiler.IL.TryCatch.AcceptVisitor[T](ILVisitor`1 visitor) in Instructions.cs:line 1448
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 55
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in StatementBuilder.cs:line 858
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockContainer container, Boolean isLoop) in StatementBuilder.cs:line 843
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in StatementBuilder.cs:line 746
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor[T](ILVisitor`1 visitor) in Instructions.cs:line 674
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 55
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in StatementBuilder.cs:line 60
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 779
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 805
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(MethodDefinition methodDefinition, IMethod method, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 731
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions) in CSharpDecompiler.cs:line 480
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IMemberDefinition[] definitions) in CSharpDecompiler.cs:line 449
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options) in CSharpLanguage.cs:line 118
   at ICSharpCode.ILSpy.TreeNodes.MethodTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in MethodTreeNode.cs:line 125
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in DecompilerTextView.cs:line 534
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0() in DecompilerTextView.cs:line 513
```

IL:
```
.method private 
	instance void Timer1_Tick (
		object sender,
		class [mscorlib]System.EventArgs e
	) cil managed 
{
	// Method begins at RVA 0x3ab38
	// Code size 163 (0xa3)
	.maxstack 3
	.locals init (
		[0] int32,
		[1] int32,
		[2] int32,
		[3] bool
	)

	IL_0000: nop
	.try
	{
		IL_0001: call void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.ProjectData::ClearProjectError()
		IL_0006: ldc.i4.s -2
		IL_0008: stloc.0

		IL_0009: ldc.i4.2
		IL_000a: stloc.2
		IL_000b: call string [System.Windows.Forms]System.Windows.Forms.Clipboard::GetText()
		IL_0010: ldstr "微步骤"
		IL_0015: ldc.i4.0
		IL_0016: call int32 [Microsoft.VisualBasic]Microsoft.VisualBasic.Strings::InStr(string, string, valuetype [Microsoft.VisualBasic]Microsoft.VisualBasic.CompareMethod)
		IL_001b: ldc.i4.0
		IL_001c: cgt
		IL_001e: stloc.3
		IL_001f: ldloc.3
		IL_0020: brfalse.s IL_002a

		IL_0022: ldc.i4.3
		IL_0023: stloc.2
		IL_0024: call void [System.Windows.Forms]System.Windows.Forms.Clipboard::Clear()
		IL_0029: nop

		IL_002a: nop

		IL_002b: leave.s IL_0099

		IL_002d: ldloc.1
		IL_002e: br.s IL_0033

		IL_0030: ldloc.1
		IL_0031: ldc.i4.1
		IL_0032: add

		IL_0033: ldc.i4.0
		IL_0034: stloc.1
		IL_0035: switch (IL_0052, IL_0001, IL_0009, IL_0022, IL_002a, IL_002b)

		IL_0052: leave.s IL_008e

		IL_0054: ldloc.2
		IL_0055: stloc.1
		IL_0056: ldloc.0
		IL_0057: ldc.i4.s -2
		IL_0059: bgt.s IL_005e

		IL_005b: ldc.i4.1
		IL_005c: br.s IL_005f

		IL_005e: ldloc.0

		IL_005f: switch (IL_006c, IL_0030)

		IL_006c: leave.s IL_008e
	} // end .try
	filter
	{
		IL_006e: isinst [mscorlib]System.Exception
		IL_0073: ldnull
		IL_0074: cgt.un
		IL_0076: ldloc.0
		IL_0077: ldc.i4.0
		IL_0078: cgt.un
		IL_007a: and
		IL_007b: ldloc.1
		IL_007c: ldc.i4.0
		IL_007d: ceq
		IL_007f: and
		IL_0080: endfilter
	} // end filter
	catch
	{
		IL_0082: castclass [mscorlib]System.Exception
		IL_0087: call void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.ProjectData::SetProjectError(class [mscorlib]System.Exception)
		IL_008c: leave.s IL_0054
	} // end handler

	IL_008e: ldc.i4 -2146828237
	IL_0093: call class [mscorlib]System.Exception [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.ProjectData::CreateProjectError(int32)
	IL_0098: throw

	IL_0099: nop
	IL_009a: ldloc.1
	IL_009b: brfalse.s IL_00a2

	IL_009d: call void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.ProjectData::ClearProjectError()

	IL_00a2: ret
} // end of method ParsingForm::Timer1_Tick
```

**Comment by CreateAndInject** [comment]
It's a vb.net program without any confused, and it's microsft .net framework. not Mono.

**Comment by CreateAndInject** [comment]
[NEEA.NCRE.CBT.Testing.zip](https://github.com/icsharpcode/ILSpy/files/1774922/NEEA.NCRE.CBT.Testing.zip)

**Comment by siegfriedpammer** [comment]
The NRE is fixed now. Please note that the C# code is still very ugly and not compilable because the original code was written in VB and contains "On Error Resume Next", for which there is no direct equivalent in C#.
