### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by blowfishpro** [icsharpcode/ILSpy#1077]
This exception occurs when attempting to save the decompiled source as a csproj.  Appears to only happen when the "Decompile anonymous methods/lambdas" option is on.  Can't provide the DLL I'm seeing this with unfortunately.
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ICSharpCode.Decompiler.CSharp.Transforms.ConvertConstructorCallIntoInitializerVisitor.HandleInstanceFieldInitializers(IEnumerable`1 members)
   at ICSharpCode.Decompiler.CSharp.Transforms.ConvertConstructorCallIntoInitializerVisitor.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Syntax.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.Decompiler.CSharp.Transforms.ConvertConstructorCallIntoInitializer.Run(AstNode node, TransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass22_0.<WriteCodeFilesInProject>b__1(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

**Comment by blowfishpro** [comment]
This was on 3.0.1, could not reproduce on latest master, closing
