### ISSUE TITLE
System.IO.EndOfStreamException following upgrade to latest release

### ISSUE THREAD

**Issue by nblackburn77** [icsharpcode/ILSpy#1098]
I started to use the latest release of ILSpy (3.0.1.3459) yesterday but decompiling any of our assemblies gives the following exception:
`System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.LinePositionMapper.GetPositionForLine(Int32 line)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List 1 indexList)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider..ctor(String fileName)
   at ICSharpCode.Decompiler.Documentation.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
   at ICSharpCode.Decompiler.CSharp.Transforms.AddXmlDocumentationTransform.Run(AstNode rootNode, TransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileModuleAndAssemblyAttributes()
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0()`

The problem didn't occur in the previous version. It will decompile the .NET core assemblies and some of the other assemblies developed by my company.
Is there anything I can do to help diagnose the problem? It also occurs with the latest code.

Thanks.

**Comment by siegfriedpammer** [comment]
It seems there is a problem with the XmlDoc files... try unchecking View > Options > Decompiler > Show XML documentation in decompiled code. Seems like we need to add a catch handler for this exception type as well. Would you be able to take a look at the XML file? Does it look like valid XML?

**Comment by nblackburn77** [comment]
Unchecking that option worked thanks.

The XML looks fine, Reflector reads it for example, and it still gets compiled into our help file without any problem. I can try and run ILSpy in the debugger to find out what it doesn't like about the XML.

**Comment by siegfriedpammer** [comment]
Thanks, that would be nice!

**Comment by nblackburn77** [comment]
I'll keep looking at it but I've attached the smallest XML file we have that fails.
It reads up to line 39 fine, but then GetPositionForLine fails because it runs out of bytes to read before currentLine becomes > line.
[Foo.zip](https://github.com/icsharpcode/ILSpy/files/1818914/Foo.zip)

**Comment by nblackburn77** [comment]
It looks like the issue is that the lines of my XML file are terminated with a line feed \r rather than \n.

Changing GetPositionForLine to increment currentLine if it encounters \n or \r worked.
