### ISSUE TITLE
OSX Decompilation Problem when using -p to decompile to a project

### ISSUE THREAD

**Issue by nstarke** [icsharpcode/ILSpy#1110]
Hello,
I am attempting to decompile a DLL to a project using the `-p` option in combination with a valid value for the `-o` option.  I receive the following error output when trying to run the decompiler:

```
Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.IO.Pipes.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.ResolveInternal(AssemblyNameReference name) in C:\projects\ilspy\ICSharpCode.Decompiler\DotNetCore\UniversalAssemblyResolver.cs:line 156
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.FindAssemblyFile(AssemblyNameReference name) in C:\projects\ilspy\ICSharpCode.Decompiler\DotNetCore\UniversalAssemblyResolver.cs:line 109
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters) in C:\projects\ilspy\ICSharpCode.Decompiler\DotNetCore\UniversalAssemblyResolver.cs:line 82
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name) in C:\projects\ilspy\ICSharpCode.Decompiler\DotNetCore\UniversalAssemblyResolver.cs:line 77
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(ModuleDefinition moduleDefinition) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\DecompilerTypeSystem.cs:line 56
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.WriteCodeFilesInProject(ModuleDefinition module, CancellationToken cancellationToken) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\WholeProjectDecompiler.cs:line 307
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(ModuleDefinition moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\WholeProjectDecompiler.cs:line 92
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(ModuleDefinition moduleDefinition, String targetDirectory, CancellationToken cancellationToken) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\WholeProjectDecompiler.cs:line 81
   at ICSharpCode.Decompiler.Console.Program.DecompileAsProject(String assemblyFileName, String outputDirectory) in /Users/nstarke/Documents/tools/ILSpy/ICSharpCode.Decompiler.Console/Program.cs:line 98
   at ICSharpCode.Decompiler.Console.Program.<>c__DisplayClass0_0.<Main>b__1() in /Users/nstarke/Documents/tools/ILSpy/ICSharpCode.Decompiler.Console/Program.cs:line 52
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ICSharpCode.Decompiler.Console.Program.Main(String[] args) in /Users/nstarke/Documents/tools/ILSpy/ICSharpCode.Decompiler.Console/Program.cs:line 75
```

Please note that I am running OSX 10.13.4 with dotnet 2.1.101.  I have tried using `dotnet run -- <ARGS>` as well as invoking `ilspycmd` directly.  If you have any suggestions on how I might go about fixing this I would be happy to submit a PR.  It is also worth noting that the decompilation process works fine without the `-p` option. Thank you for your time!

**Comment by ahokinson** [comment]
It turns out that this happens when another assembly is required to read the definition of a type in that other assembly. In your case, there's a dependency on `System.IO.Pipes.AccessControl` and ILSpy doesn't know how to resolve that assembly.

The solution is to have that required DLL available in the same file path as the DLL you are attempting to decompile.

**Comment by nstarke** [comment]
Just for reference, for this exact error I found the following:
```
$ find /usr/local/share/dotnet -name "System.IO.Pipes.AccessControl.dll"
/usr/local/share/dotnet/sdk/2.1.101/Roslyn/runtimes/win/lib/netstandard1.3/System.IO.Pipes.AccessControl.dll
/usr/local/share/dotnet/sdk/2.1.101/Roslyn/runtimes/unix/lib/netstandard1.3/System.IO.Pipes.AccessControl.dll
/usr/local/share/dotnet/sdk/2.1.101/Roslyn/bincore/runtimes/win/lib/netstandard1.3/System.IO.Pipes.AccessControl.dll
/usr/local/share/dotnet/sdk/2.1.101/Roslyn/bincore/runtimes/unix/lib/netstandard1.3/System.IO.Pipes.AccessControl.dll
```
For `System.IO.Pipes.AccessControl.dll` I found it in `/usr/local/share/dotnet/sdk/2.1.101/Roslyn/bincore/runtimes/unix/lib/netstandard1.3/System.IO.Pipes.AccessControl.dll` - I was greeted subsequently with additional missing dlls, which I was able to successfully retrieve from nuget.  Putting all dependent dll's in the same directory as `ilspycmd` and then running `ilspycmd` from within that same directory allowed me to successfully decompile the project in question.  Thank you very much for your help.  Closing this now.
