### ISSUE TITLE
Issue when decompiling enum.

### ISSUE THREAD

**Issue by mkrueger** [icsharpcode/ILSpy#1111]
Got that on mono - however I can't open the decompiler project myself for some reason it doesn't load on linux - so I just report that one:

Given the System.DayOfWeek enum which is decompiled as :
```
using System.Runtime.InteropServices;

namespace System
{
	[Serializable]
	[ComVisible(true)]
	public enum DayOfWeek
	{
		Friday = 5,
		Monday = 1,
		Saturday = 6,
		Sunday = 0,
		Thursday = 4,
		Tuesday = 2,
		Wednesday
	}
}
```

The IL for the mono version of that looks a bit strange because the value sorting is wrong :

```
.class public auto ansi sealed System.DayOfWeek
	extends System.Enum
{
	// Fields
	.field public specialname rtspecialname int32 value__
	.field public static literal valuetype System.DayOfWeek Friday = int32(5)
	.field public static literal valuetype System.DayOfWeek Monday = int32(1)
	.field public static literal valuetype System.DayOfWeek Saturday = int32(6)
	.field public static literal valuetype System.DayOfWeek Sunday = int32(0)
	.field public static literal valuetype System.DayOfWeek Thursday = int32(4)
	.field public static literal valuetype System.DayOfWeek Tuesday = int32(2)
	.field public static literal valuetype System.DayOfWeek Wednesday = int32(3)

} // end of class System.DayOfWeek
```

Note that when using debug builds an assertion is hit:

```
FailFast: Should not insert using declaration for namespace that is missing from the superset: System.Runtime.InteropServices

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceUsingDeclarations.Run(AstNode rootNode, TransformContext context) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Transforms\IntroduceUsingDeclarations.cs:line 50
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 299
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileType(FullTypeName fullTypeName) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 764
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypeAsString(FullTypeName fullTypeName) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 776
   at ICSharpCode.Decompiler.Console.Program.Decompile(String assemblyFileName, TextWriter output, String typeName) in /home/mkrueger/work/ILSpy/ICSharpCode.Decompiler.Console/Program.cs:line 109
   at ICSharpCode.Decompiler.Console.Program.<>c__DisplayClass0_0.<Main>b__1() in /home/mkrueger/work/ILSpy/ICSharpCode.Decompiler.Console/Program.cs:line 70
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ICSharpCode.Decompiler.Console.Program.Main(String[] args) in /home/mkrueger/work/ILSpy/ICSharpCode.Decompiler.Console/Program.cs:line 75

   at System.Environment.FailFast(System.String, System.Exception)
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceUsingDeclarations.Run(ICSharpCode.Decompiler.CSharp.Syntax.AstNode, ICSharpCode.Decompiler.CSharp.Transforms.TransformContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(ICSharpCode.Decompiler.CSharp.Syntax.AstNode, ICSharpCode.Decompiler.DecompileRun, ICSharpCode.Decompiler.TypeSystem.ITypeResolveContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileType(ICSharpCode.Decompiler.TypeSystem.FullTypeName)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypeAsString(ICSharpCode.Decompiler.TypeSystem.FullTypeName)
   at ICSharpCode.Decompiler.Console.Program.Decompile(System.String, System.IO.TextWriter, System.String)
   at ICSharpCode.Decompiler.Console.Program+<>c__DisplayClass0_0.<Main>b__1()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(System.String[])
   at ICSharpCode.Decompiler.Console.Program.Main(System.String[])
```

**Comment by dgrunwald** [comment]
Fields are shown in metadata order.
But I agree that the missing value for `Wednesday` looks weird. If we have to show some values, we should probably just show all values.

The assertion indicates that our IL-level approximation to the set of usings was inaccurate, and we ended up inserting an unexpected using. I guess the approximation is missing support for non-custom attributes.

**Comment by mkrueger** [comment]
I guessed that it's shown in metadata order that's why I posted the meta data - it looks really weird IMO but that's what's in the dll :/.

**Comment by siegfriedpammer** [comment]
I cannot reproduce the assertion with the latest nightly build. Also, when I try to decompile Mono's mscorlib.dll the order of enum values is as one would expect.

**Comment by christophwille** [comment]
@mkrueger did you get a chance to try this with https://github.com/icsharpcode/ILSpy/releases/tag/v3.1-final because it was released post @siegfriedpammer comment of "can't repro with current builds". Thanks.

**Comment by siegfriedpammer** [comment]
I was only talking about the assertion. The actual problem here is not yet fixed.

**Comment by mkrueger** [comment]
Latest I tried was 3.0.0.3403-beta4
