### ISSUE TITLE
Loading a UWP assembly fails

### ISSUE THREAD

**Issue by ShaharPrishMSFT** [icsharpcode/ILSpy#1141]
When using ILSpy, I can load MD files from the UWP kit as assemblies to get at their metadata.

However, when I try to do the same with CSharpDecompiler, I am instead getting an exception:

System.NotSupportedException
  HResult=0x80131515
  Message=Version not supported: 255.255.255.255
  Source=ICSharpCode.Decompiler
  StackTrace:
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.GetCorlib(AssemblyNameReference reference)
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.ResolveInternal(AssemblyNameReference name)
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.FindAssemblyFile(AssemblyNameReference name)
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name)
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(ModuleDefinition moduleDefinition)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler..ctor(String fileName, DecompilerSettings settings)
   at PlatformWrapper.MainWindow..ctor() in C:\Users\shaharp\source\repos\PlatformWrapper\PlatformWrapper\MainWindow.xaml.cs:line 32

**Comment by siegfriedpammer** [comment]
That is because, `ICSharpCode.Decompiler` does not yet include support for `winmd` files. Support for them is only included in ILSpy.

**Comment by ShaharPrishMSFT** [comment]
Ah. Thanks. I thought ilspy was using that.
