### ISSUE TITLE
Error loading assemlby

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1178]
Used version: ILSpy version 3.2.0.3817-beta

Drag-dropped assembly,
issue:
```
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Mono.Cecil.PE.ImageReader.ReadDebugHeader()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ICSharpCode.ILSpy.LoadedAssembly.<GetAssemblyDefinitionAsync>d__11.MoveNext()
```

binary
https://www.sendspace.com/file/sy3mlr

**Comment by siegfriedpammer** [comment]
Could you please provide the assembly again for testing? Sorry for not getting to this sooner. Thank you very much!

**Comment by greenozon** [comment]
Can't find it at the moment, sorry
but looks like this is smth related to reading out debug info... (it means that .pdb file was nearby, am I right?)

**Comment by greenozon** [comment]
Found the target,
same error on ILSpy version 3.2.0.3851-rc

Most probably this is obfuscated item.
target: https://www.sendspace.com/file/403wwf


I'd notice that this is a severe issue, as ILSpy does not open it up at all (it draws a yellow warning icon in a tree view as if this would not be a .net assembly)

**Comment by neilsimp1** [comment]
I am seeing a similar issue:

```
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Mono.Cecil.PE.ImageReader.ReadDebugHeader()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

This is for Oracle.ManagedDataAccess.dll, isntalled via NuGet, version 18.3.0.

**Comment by devinvisible** [comment]
What was the root cause of the BadImageFormatException? I've noticed that Oracle.ManagedDataAccess.dll (4.122.18.3) seems to have some obfuscated classes and methods. Were these giving the trouble?

**Comment by markpisc** [comment]
@neilsimp1   Did you ever solve your issue? I am getting the same exact error.

**Comment by siegfriedpammer** [comment]
If you are getting the exact same error, then you probably are not using the latest version of the decompiler, please update and if the problem persists, please open a new issue describing the problem. Please also include the assembly for us to analyze. Without the assembly it will be hard to find a fix for the bug. Thank you!

**Comment by neilsimp1** [comment]
@markpisc I gave up on this at the time, but I did just give this a try using ILSpy 4.0.1.4530 and the same DLL and it is working correctly.

I am guessing that based on some logs on my system, I was using ILSpy 3.2.0 before, so it may well be that updating ILSpy fixed the problem.
