### ISSUE TITLE
Assertion Failed in IntroduceUsingDeclarations on type

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1181]
ILSpy version 3.2.0.3829-beta
just browse high level classes in a left-tree view...

issue

```
ICSharpCode.ILSpy.AssertionFailedException: Should not insert using declaration for namespace that is missing from the superset: x.Custom
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage)
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceUsingDeclarations.Run(AstNode rootNode, TransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IMemberDefinition[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0()

```

file
https://www.sendspace.com/file/cofjv2

**Comment by siegfriedpammer** [comment]
Could you please provide the assembly again? Sorry for not getting to this sooner. Thank you very much!

**Comment by greenozon** [comment]
yeah, np - https://www.sendspace.com/file/lra8sv
this one has a couple of  "IntroduceUsingDeclarations" issues (find them all by pressing "Continue", not ignore! :)

PS are there any build artifacts to check your great fixes out? :)
is it appveyor?

**Comment by siegfriedpammer** [comment]
This seems to fixed in the current master branch.
