### ISSUE TITLE
Assertion Failed in IntroduceUsingDeclarations on Property

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1183]
ILSpy version ILSpy version 3.2.0.3850-rc
browse this property: Dile.Debug.ProcessWrapper.IsVersion2

issue
```
ICSharpCode.ILSpy.AssertionFailedException: Should not insert using declaration for namespace that is missing from the superset: System.Runtime.InteropServices
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage)
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceUsingDeclarations.Run(AstNode rootNode, TransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IMemberDefinition[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileProperty(PropertyDefinition property, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.PropertyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0()

```

https://www.sendspace.com/file/4zfatb

No obfuscation

**Comment by dgrunwald** [comment]
See also: #1172 and #1181.

Note: this assertion is mostly safe to ignore. It indicates a bug in the ILAst-level approximation for the using declarations. This is only relevant in some rare cases, such as null propagation with an extension method `a?.M();` when there's another extension method with the same name in the namespace the assertion is complaining about.
We'll likely only fix it in ILSpy 4.0, as a lot of the related infrastructure has changed.
