### ISSUE TITLE
Still getting error: "System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection."

### ISSUE THREAD

**Issue by wpafbo79** [icsharpcode/ILSpy#1201]
I have been very impressed with your tool.  Great product and it is helping me learn a great deal about MSIL and C#.

I am trying to decompile a few DLLs to C#.  The .NET 2.0 ones work fine, but the .NET 4.0 ones fail when I use `File -> Save Code...`.  The error I am getting is:

    Error decompiling System.Boolean Sims3.Gameplay.Objects.Plumbing.Bathtub/TakeBath/Definition::Test(Sims3.Gameplay.Actors.Sim,Sims3.Gameplay.Objects.Plumbing.Bathtub,System.Boolean,Sims3.SimIFace.GreyedOutTooltipCallback&)
     ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
       at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 46
       at System.Collections.Generic.List`1.get_Item(Int32 index) in offset 0
       at ICSharpCode.Decompiler.CSharp.CallBuilder.CastArguments(IList`1 arguments, IReadOnlyList`1 expectedParameters) in offset 20
       at ICSharpCode.Decompiler.CSharp.CallBuilder.GetRequiredTransformationsForCall(ExpectedTargetDetails expectedTargetDetails, IMethod method, TranslatedExpression& target, List`1 arguments, String[] argumentNames, List`1 expectedParameters, CallTransformation allowedTransforms, IParameterizedMember& foundMethod) in offset 388
       at ICSharpCode.Decompiler.CSharp.CallBuilder.Build(OpCode callOpCode, IMethod method, IReadOnlyList`1 callArguments, IReadOnlyList`1 argumentToParameterMap, IType constrainedTo) in offset 1442
       at ICSharpCode.Decompiler.CSharp.CallBuilder.Build(CallInstruction inst) in offset 280
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitCall(Call inst, TranslationContext context) in offset 19
       at ICSharpCode.Decompiler.IL.Call.AcceptVisitor[C,T](ILVisitor`2 visitor, C context) in offset 0
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint) in offset 50
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitLeave(Leave inst) in offset 117
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 14
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in offset 115
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in offset 137
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 14
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in offset 0
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.TranslateFunction(IType delegateType, ILFunction function) in offset 180
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitILFunction(ILFunction function, TranslationContext context) in offset 0
       at ICSharpCode.Decompiler.IL.ILFunction.AcceptVisitor[C,T](ILVisitor`2 visitor, C context) in offset 0
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint) in offset 50
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitStObj(StObj inst, TranslationContext context) in offset 159
       at ICSharpCode.Decompiler.IL.StObj.AcceptVisitor[C,T](ILVisitor`2 visitor, C context) in offset 0
       at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint) in offset 50
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Default(ILInstruction inst) in offset 0
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 14
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlock(Block block) in offset 44
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 14
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitIfInstruction(IfInstruction inst) in offset 0
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 14
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in offset 115
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in offset 137
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in offset 14
       at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in offset 0
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 436
    -- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 835
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(MethodDefinition methodDefinition, IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 78
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 567
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 84
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 84
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 154
       at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 98
       at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass22_0.<WriteCodeFilesInProject>b__1(IGrouping`2 file) in offset 58
       at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1() in offset 589
       at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) in offset 6
       at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object) in offset 134

I was looking through previous bug reports and found #1182.  I am getting a similar error, but the CI version in the link did not resolve the issue for me.  With the latest CI build, I am now getting:

    System.ArgumentNullException: Value cannot be null.
    Parameter name: assemblyResolver
       at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile moduleDefinition, IAssemblyResolver assemblyResolver, DecompilerSettings settings)
       at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, CancellationToken cancellationToken)
       at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
       at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
       at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
       at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
       at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass45_0.<SaveToDiskAsync>b__0()

Thanks,
-Theron

**Comment by siegfriedpammer** [comment]
I fear, we won't be able to fix the first exception without the binary + references. Could you please provide them? Thank you very much! Unfortunately, the exception is not related to the bug in #1182.

The second exception: When you downloaded the latest CI build, you got a build from the SRM branch, which is in pre-alpha stage currently. Thanks for reporting the exception, it is fixed now!

**Comment by wpafbo79** [comment]
Glad to help with the second exception.  These are the two files I am having problems with and the supporting reference files.  Let me know if you need something else.

[problemFiles.zip](https://github.com/icsharpcode/ILSpy/files/2182085/problemFiles.zip)
[supportFiles.zip](https://github.com/icsharpcode/ILSpy/files/2182110/supportFiles.zip)
