### ISSUE TITLE
v4.x: EnumUnderlyingTypeResolveException when opening up assembly

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1208]
ILSpy version 4.0.0.4173-alpha1
just try to open up assembly - 

```
ICSharpCode.Decompiler.Metadata.EnumUnderlyingTypeResolveException: Exception of type 'ICSharpCode.Decompiler.Metadata.EnumUnderlyingTypeResolveException' was thrown.
   at ICSharpCode.Decompiler.TypeSystem.TypeProvider.GetUnderlyingEnumType(IType type)
   at ICSharpCode.Decompiler.Metadata.CustomAttributeDecoder`1.DecodeNamedArgumentType(BlobReader& valueReader, Boolean isElementType)
   at ICSharpCode.Decompiler.Metadata.CustomAttributeDecoder`1.DecodeNamedArguments(BlobReader& valueReader, Int32 count)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.ReadBinarySecurityAttribute(BlobReader& reader, CustomAttributeTypedArgument`1 securityAction)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.AddSecurityAttributes(DeclarativeSecurityAttribute secDecl)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.AddSecurityAttributes(DeclarativeSecurityAttributeHandleCollection securityDeclarations)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.GetAssemblyAttributes()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectAttributeNamespaces(MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileModuleAndAssemblyAttributes()
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass34_0.<DecompileAsync>b__0()
```

Target: https://www.sendspace.com/file/lqne2s

**Comment by greenozon** [comment]
Upd: (observation):
when switching   C# -> IL -> C# 
a magic happens....
why is that :)

**Comment by siegfriedpammer** [comment]
> Upd: (observation):
when switching C# -> IL -> C#
a magic happens....
why is that :)

I guess, this is because, the ILLanguage implementation has a bug and it does not prevent ILSpy from loading references during first decompilation. :)
