### ISSUE TITLE
Assertion Failed in DecodeSignature()

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1214]
ILSpy version 4.0.0.4194-alpha1

```
ICSharpCode.ILSpy.AssertionFailedException
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage)
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.get_ReturnType()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass26_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

```

target:  (plain text)  https://www.sendspace.com/file/zc3l2u

**Comment by siegfriedpammer** [comment]
Looks like we're getting the parameters wrong (in both C# and IL):

ILSpy:
```
.method /* 0600014C */ public hidebysig newslot abstract virtual 
	instance void modreq([mscorlib]System.Runtime.CompilerServices.IsUdtReturn) erase (
		class Microsoft.VisualC.StlClr.Generic.ContainerRandomAccessIterator`1<!TValue>& _Where,
		class Microsoft.VisualC.StlClr.Generic.ContainerRandomAccessIterator`1<!TValue> modreq([mscorlib]System.Runtime.CompilerServices.IsByValue) ''
	) cil managed 
{
} // end of method IDeque`1::erase
```

```csharp
// Microsoft.VisualC.StlClr.IDeque<TValue>
using Microsoft.VisualC.StlClr.Generic;

void erase(ref ContainerRandomAccessIterator<TValue> _Where, ContainerRandomAccessIterator<TValue> P_1);
```

ildasm:
```
.method public hidebysig newslot abstract virtual 
        instance void modreq([mscorlib]System.Runtime.CompilerServices.IsUdtReturn) 
        erase(class Microsoft.VisualC.StlClr.Generic.ContainerRandomAccessIterator`1<!TValue>& A_1,
              class Microsoft.VisualC.StlClr.Generic.ContainerRandomAccessIterator`1<!TValue> modreq([mscorlib]System.Runtime.CompilerServices.IsByValue) _Where) cil managed
{
} // end of method IDeque`1::erase
```

Notice that the only entry in the Param table has Sequence == 2 and is therefore assigned to the second parameter by ildasm.

Interestingly, VS metadata-as-source does not show this method at all.

**Comment by siegfriedpammer** [comment]
Note: according to ECMA-335, II.22.33, "rules" 4 and 5:

>4. Sequence shall have a value >= 0 and <= number of parameters in owner method. A
Sequence value of 0 refers to the owner method’s return type; its parameters are then
numbered from 1 onwards [ERROR]
>5. Successive rows of the Param table that are owned by the same method shall be
ordered by increasing Sequence value - although gaps in the sequence are allowed
[WARNING]

Gaps are allowed, but we're currently mapping the parameter handles to the signature parameter types without handling gaps correctly.
