### ISSUE TITLE
Crash on project save

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1241]
ILSpy version 4.0.0.4254-beta1

On project save,
shows this error box then ILSpy crashes.

```
---------------------------
Sorry, we crashed
---------------------------
System.UnauthorizedAccessException: Access to the path 'D:\delme_\-' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)

   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<WriteResourceFilesInProject>d__31.MoveNext()

   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)

   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)

   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)

   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)

   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)

   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()
---------------------------
OK   
---------------------------

```

target: https://www.sendspace.com/file/7k17a7

**Comment by greenozon** [comment]
I've explored a bit the
**System.UnauthorizedAccessException**

and found this info:

An UnauthorizedAccessException means one of 4 things:

- The caller does not have the required permission.
- The file is an executable file that is in use.
- Path is a directory.
- Path specified a read-only file.


which one is ILSpy case?

**Comment by siegfriedpammer** [comment]
ILSpy escapes all invalid chars in namespace names, type names and resource names with '-'.

In this case we have a namespace that uses some obfuscated name (with just one character), thus a directory '-' is created. Later we try to export all resources, there again is a resource with only one invalid character as name (which gets normalized to '-'). ILSpy tries to create a file with the name '-' in a directory where there already exists the directory for the namespace '-', this leads to a collision and this exception.

I doubt that we'll ever be able to support all tricks obfuscators use. Unfortunately we cannot change the names of resources too much, because that prevents us from making the project recompilable.

**Comment by greenozon** [comment]
Thanks, now its clear
so I propose to catch this exception somewhere  (as for the moment ILSpy crashes -> exists)
and lets close this issue.
Agree that obfuscated bits needs different approach and definitely not by SRM one.

To summarize - is it possible not to crash and just issue some err/warning box?

**Comment by dgrunwald** [comment]
I think the crash was a bit of debug-mode logic that disables the exception handler when running a debug build (so that exceptions stay unhandled and break into the debugger). Release builds would have caught the exception.
