### ISSUE TITLE
Exception on load (from VS) after updating to 4.0 beta 1

### ISSUE THREAD

**Issue by warlock00** [icsharpcode/ILSpy#1248]
From VS - Open code in ILSpy
ILSpy 3.2 didn't do this. But after updating to ILSpy 4 beta 1, I get:

Error(s) loading plugin: 
Microsoft.VisualStudio.Composition.CompositionFailedException: Errors occurred during discovery. 
---> System.AggregateException: One or more errors occurred. 
---> Microsoft.VisualStudio.Composition.PartDiscoveryException: 
ReflectionTypeLoadException while enumerating types in assembly 
"C:\Users\d\AppData\Local\Microsoft\VisualStudio\15.0_9d4bb72c\Extensions\hxkf5bmx.di4\ILSpy.exe". 
Results will be incomplete. 
---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. 
Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass27_0.<CreateAssemblyDiscoveryBlockChain>b__0(Assembly a)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.DiscoveredParts.ThrowOnErrors()
   at Microsoft.VisualStudio.Composition.CompositionConfiguration.ThrowOnErrors()
   at ICSharpCode.ILSpy.App..ctor()

**Comment by warlock00** [comment]
This occurred during install, don't know if it is related.

09-Aug-18 11:33:41 AM - Beginning to install extension to Visual Studio Professional 2017...
09-Aug-18 11:33:41 AM - Upgrading 'ILSpy', version 3.2.0.3856 to version 4.0.0.4285.
09-Aug-18 11:33:44 AM - Install to Visual Studio Professional 2017 completed successfully. The extension has been installed to C:\USERS\D\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_9D4BB72C\EXTENSIONS\HXKF5BMX.DI4\
09-Aug-18 11:33:44 AM - Failure encountered during /updateConfiguration step. Ignoring failure and considering requested operation a success.

Exception: System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.<RunUpdateConfigurationAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VSIXInstaller.Utilities.<RunUpdateConfiguration>d__8.MoveNext()

**Comment by warlock00** [comment]
Not related. Fixed the installer error by running PowerShell as Administator and running VSlauncher isblah.vsix. Didn't fix exception.

**Comment by warlock00** [comment]
I copied Microsoft.DiaSymReader.dll from the zip installer to the plugin folder, and the problem was fixed.

**Comment by MABrunner** [comment]
Shouldn't this issue be kept open until the installer is fixed?
