### ISSUE TITLE
Merged compile of website, function with Optional parameter type Object causes  ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by halcyon1234** [icsharpcode/ILSpy#1283]
- ASP.Net Website project (new project is fine)
- VB.Net, haven't tested in C# yet
- Create, under app_code, a Class
- Public Shared Function DoSomething(ByVal thing as String, Optional ByVal obj as Object = Nothing) as String
- Just return a value in there
- Build -> Publish Website
- File Publish Options: Precompile During Publishing YES
- "Configure" - merge options, select Merge all outputs to a single assembly.  Pick the assembly name
- Publish to file system (wherever, doesn't matter)
- After publish, ILSpy the combined .dll
- Expand {} -
- Find the class you created
- Click on it

Expected: see the decompiled .dll as usual

What happens: System.ArgumentOutOfRangeException

Stack Trace:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: typeCode
   at System.Reflection.Metadata.BlobReader.ReadConstant(ConstantTypeCode typeCode)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.WriteConstant(MetadataReader metadata, Constant constant)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.WriteParameterAttributes(PEFile module, ParameterHandle handle)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleMethodBlock(PEFile module, MethodDefinitionHandle handle, GenericContext genericContext)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleMethod(PEFile module, MethodDefinitionHandle handle)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(PEFile module, TypeDefinitionHandle type)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass34_0.<DecompileAsync>b__0()

Seems to happen in ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs line 1028

**Comment by halcyon1234** [comment]
Sample project attached.  VS2012.  Has both source code and compiled.

ILSpy TestWebsiteOptionalParamDeployTarget\bin\TestMerged.dll - TestOptionalParameterAsObject to see the exception

(using DropBox because github won't let me upload a zip?)

https://www.dropbox.com/s/fke31swqqzjfr94/TestWebsiteOptionalParam.zip?dl=0

**Comment by siegfriedpammer** [comment]
This looks like a bug in System.Reflection.Metadata or the compiler. The problem is that the Type field of the entry in the Constant table has the type code `ELEMENT_TYPE_OBJECT` (0x1c) instead of the expected `NullReference` (0x12) value from `System.Reflection.Metadata.ConstantTypeCode`.

@tmat would you - by any chance - know what's going on?

**Comment by halcyon1234** [comment]
FYI: though the Type field is incorrect, this MAY be due to a bug in the compiler / something in that pipeline.  I've also opened a Visual Studio ticket with Microsoft:

https://developercommunity.visualstudio.com/content/problem/339639/compile-and-merge-class-with-function-with-optiona.html

**Comment by tmat** [comment]
Seems like aspnet_merge.exe is using ILMerge, which is likely emitting bad metadata.

**Comment by siegfriedpammer** [comment]
@tmat Thanks for the info!

Looks like we will have to catch these exceptions at some point.
