### ISSUE TITLE
v.4x: System.NullReferenceException in CSharpDecompiler.DetectBestEnumValueDisplayMode

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1323]
ILSpy version 4.0.0.4382-beta2

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DetectBestEnumValueDisplayMode(ITypeDefinition typeDef, PEFile module)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass34_0.<DecompileAsync>b__0()

```

**Comment by greenozon** [comment]
Corresponding IL for above issue:


```
.class nested public auto ansi sealed Enum0
	extends [mscorlib]System.Enum
{
	// Fields
	.field public specialname rtspecialname int32 value__
	.field public static literal valuetype ns0.Class0/Enum0 const_0
	.field public static literal valuetype ns0.Class0/Enum0 const_1
	.field public static literal valuetype ns0.Class0/Enum0 const_2
	.field public static literal valuetype ns0.Class0/Enum0 const_3

} // end of class Enum0
```
