### ISSUE TITLE
System.InvalidCastException: Cast from Boolean to Int64 not supported.

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1330]
ILSpy version 4.0.0.4392-beta2

```
System.InvalidCastException: Cast from Boolean to Int64 not supported.
   at ICSharpCode.Decompiler.Util.CSharpPrimitiveCast.CSharpPrimitiveCastUnchecked(TypeCode targetType, Object input)
   at ICSharpCode.Decompiler.Util.CSharpPrimitiveCast.Cast(TypeCode targetType, Object input, Boolean checkForOverflow)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertConstantValue(IType expectedType, IType type, Object constantValue)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertConstantValue(IType type, Object constantValue)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertParameter(IParameter parameter)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertMethod(IMethod method)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertEntity(IEntity entity)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass30_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

```

Idea: is it possible to add module/class/routine that was under analysis?
target has tons of items, don't know on which it crashing...

**Comment by siegfriedpammer** [comment]
Can you please try again with the latest master?
Would be nice if you could tell us, which method produces this exception.

**Comment by siegfriedpammer** [comment]
@greenozon Does the exception still occur?

**Comment by greenozon** [comment]
well done, closing!
