### ISSUE TITLE
Support disassembling .NET Compact Framework 3.5 assemblies

### ISSUE THREAD

**Issue by ninjaoxygen** [icsharpcode/ILSpy#1346]
When a .NET 3.x assembly is opened, the following exception occurs:

    System.ArgumentNullException: Value cannot be null.
    Parameter name: path2
       at System.IO.Path.Combine(String path1, String path2)
       at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.GetMscorlibBasePath(Version version)
       at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.GetCorlib(IAssemblyReference reference)
       at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.ResolveInternal(IAssemblyReference name)
       at ICSharpCode.ILSpy.LoadedAssembly.LookupReferencedAssemblyInternal(IAssemblyReference fullName, Boolean isWinRT)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at ICSharpCode.ILSpy.LoadedAssembly.LookupReferencedAssembly(IAssemblyReference reference)
       at ICSharpCode.ILSpy.LoadedAssembly.MyAssemblyResolver.Resolve(IAssemblyReference reference)
       at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions)
       at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
       at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
       at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
       at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass34_0.<DecompileAsync>b__0()
 
As 3.0 and 3.5 assemblies using the 2.0 mscorlib, the following case addition fixes it for me, in GetSubFolderForVersion, line 418

					case 2:
					case 3:
						return "v2.0.50727";

**Comment by siegfriedpammer** [comment]
This is strange, because there should be no mscorlib with major version == 3. Would it be possible for you to provide an example where the current implementation fails? Thank you!

**Comment by ninjaoxygen** [comment]
Attaching an example file that references the 3.5 mscorlib.dll

[TestNetCf35.zip](https://github.com/icsharpcode/ILSpy/files/2696166/TestNetCf35.zip)

**Comment by ninjaoxygen** [comment]
So the original patch was not the right thing to do - it actually loads the wrong mscorlib then.

After some more testing I find that if I fix the original exception by adding a null check, commit 4ef03611ddbcbffb7f40d5855a9a053f285ff386 then it load a v4.0 mscorlib.

Secondly I have added a check for the .NET Compact Framework SDK in commit e812a1f2309c45b7906abbf89cde79c3f2b2296d which now loads the correct mscorlib.
