### ISSUE TITLE
System.ArgumentException: Cannot find StaticResource: 0 while generating source code

### ISSUE THREAD

**Issue by Fulborg** [icsharpcode/ILSpy#1354]
While trying to generate source from attached DLL [Bib3.FCL.dll.zip](https://github.com/icsharpcode/ILSpy/files/2705959/Bib3.FCL.dll.zip), i'm getting an exception 
```
System.ArgumentException: Cannot find StaticResource: 0
Parameter name: identifier
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.GetStaticResource(Int16 identifier)
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.ReadPropertyWithStaticResourceIdentifier()
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.ReadInternal()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceFileHandler.WriteResourceToFile(LoadedAssembly assembly, String fileName, Stream stream, DecompilationOptions options)
   at ICSharpCode.ILSpy.CSharpLanguage.ILSpyWholeProjectDecompiler.WriteResourceToFile(String fileName, String resourceName, Stream entryStream)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<WriteResourceFilesInProject>d__31.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()
```
generated .csproj file is empty

**Comment by siegfriedpammer** [comment]
Fixed in #1419
