### ISSUE TITLE
v.4.x; System.BadImageFormatException: Read out of bounds.

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1368]
ILSpy version 4.0.0.4483-beta3

```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.BlobReader.ReadUTF8(Int32 byteCount)
   at System.Reflection.Metadata.BlobReader.ReadSerializedString()
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeArgument(BlobReader& valueReader, ArgumentTypeInfo info)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeFixedArguments(BlobReader& signatureReader, BlobReader& valueReader, Int32 count)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeValue(EntityHandle constructor, BlobHandle value)
   at System.Reflection.Metadata.CustomAttribute.DecodeValue[TType](ICustomAttributeTypeProvider`1 provider)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.CustomAttribute.DecodeValue()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.CustomAttribute.get_FixedArguments()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.HandleAttributes(IEnumerable`1 attributes, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileWholeModuleAsSingleFile()
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()
```

target:  hard to understand, as the exception stack does not contain the context of dll/etc
**btw, why? :)**

Hint:  tried to decompile v1.xxx assemblies from GAC  (sorted by version and selected 1.x items)

see the pic
I'll try to identify the guilty guy

![screenshot_35](https://user-images.githubusercontent.com/765343/50567371-d395db80-0d4c-11e9-9447-f253e1e0209d.png)

**Comment by greenozon** [comment]
The culprit found:

Microsoft.Ink.InkRecognizerContextClass

assembly:

// C:\Windows\assembly\GAC\Microsoft.Ink\1.0.2201.0__31bf3856ad364e35\Microsoft.Ink.dll
// Microsoft.Ink, Version=1.0.2201.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// Global type: <Module>
// Architecture: x86
// Runtime: v1.0.3705
// This assembly is signed with a strong name key.
// Hash algorithm: SHA1
// Public key: 0240048000940006200024005253413104001010b5fc90e727f67871e773a8fde8938c81dd42ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131aebd333c5ee6021672d9718ea31a8aebdda072f25d87dba6fc9ffd598ed4da35e44c398c45437e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c3855da9
