### ISSUE TITLE
IndexOutOfRangeException decompiling a C++/CLI DLL

### ISSUE THREAD

**Issue by vatsan-madhavan** [icsharpcode/ILSpy#1408]
We have been noticing that occasionally ILSpy is unable to decompile C++/CLI assemblies like (WPF's) PresentationCore.dll. 

Initially we thought that it might have been a compiler or a linker bug (JustDecompile also had trouble decompiling the DLL), but turns out that (a) the DLL is fine, and (b) the PDB is what ILSpy seems to have a problem with and (c) the PDB is also well formed per folks in the C++ compiler/linker teams. We also found that dotPeek is able to handle these assemblies ok. 

Any ideas on what is going on? 

[not-bad-presentationcore.zip](https://github.com/icsharpcode/ILSpy/files/2814406/not-bad-presentationcore.zip)

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Cci.Pdb.BitAccess.ReadInt32(Int32& value)
   at Microsoft.Cci.Pdb.DbiSecCon..ctor(BitAccess bits)
   at Microsoft.Cci.Pdb.DbiModuleInfo..ctor(BitAccess bits, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadDbiStream(BitAccess bits, DbiModuleInfo[]& modules, DbiDbgHdr& header, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.NativePdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.NativePdbReader.ProcessDebugHeader(ImageDebugHeader header)
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at ICSharpCode.Decompiler.PdbProvider.Cecil.MonoCecilDebugInfoProvider..ctor(PEFile module, String pdbFileName, String description)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(PEFile module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by lextm** [comment]
The call stack points to CCI https://github.com/Microsoft/cci/issues

**Comment by vatsan-madhavan** [comment]
Thanks for the hint @lextm. Based on feedback from the issue I'd opened on [Microsoft/cci](https://github.com/Microsoft/cci/issues/66#issuecomment-466552651), I was able to puzzle it out and resolve it.
