### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.Single'

### ISSUE THREAD

**Issue by tellowkrinkle** [icsharpcode/ILSpy#1479]
When trying to decompile `Assembly-CSharp.dll` from [Assembly-CSharp.zip](https://github.com/icsharpcode/ILSpy/files/3050891/Assembly-CSharp.zip), the following exception is thrown:
```
System.AggregateException: One or more errors occurred. (Error decompiling Assets.Scripts.Core.Audio.AudioController
) ---> ICSharpCode.Decompiler.DecompilerException: Error decompiling Assets.Scripts.Core.Audio.AudioController
 ---> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Single'.
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertFloatingPointLiteral(IType type, Object constantValue) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Syntax\TypeSystemAstBuilder.cs:line 1020
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertConstantValue(IType expectedType, IType type, Object constantValue) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Syntax\TypeSystemAstBuilder.cs:line 775
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertParameter(IParameter parameter) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Syntax\TypeSystemAstBuilder.cs:line 1265
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertMethod(IMethod method) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Syntax\TypeSystemAstBuilder.cs:line 1614
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1139
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1013
   --- End of inner exception stack trace ---
...
```

**Comment by tellowkrinkle** [comment]
Appears to be caused by an integer default value for a float argument, a program decompiled by an older version of ILSpy can be seen [here](https://github.com/07th-mod/higurashi-assembly/blob/4dc2d6f66bed05ff8326e5d498988cb94fd7e3f8/Assets.Scripts.Core.Audio/AudioController.cs#L406).  I couldn't get my version of the compiler to generate a crashing dll, so I would guess it's specific to whatever version of mono was used to compile that one.

**Comment by siegfriedpammer** [comment]
Thank you for reporting this! I've seen this one previously reported [here](https://twitter.com/mutaguchi/status/1108767988373557253), but was unable to get a repro.
