### ISSUE TITLE
ilspycmd 5.0.0-preview 1 fails with System.InvalidOperationException: Failed to compare two elements in the array

### ISSUE THREAD

**Issue by clguimanMSFT** [icsharpcode/ILSpy#1480]
Ran ilspycmd assembly.dll -o d:\temp\decompile -d
```
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, Comparison`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.WritePdb(PEFile file, CSharpDecompiler decompiler, DecompilerSettings settings, Stream targetStream, Boolean noLogo)
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.GeneratePdbForAssembly(String assemblyFileName, String pdbFileName, String[] referencePaths, CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 193
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 87
```

I can share the assembly in a private email.

**Comment by siegfriedpammer** [comment]
Please send an email to siegfried.pammer@gmail.com, thank you very much!

**Comment by clguimanMSFT** [comment]
done
