### ISSUE TITLE
AssertionFailedException in BamlDecompiler.Baml.SizedBamlRecord.Read

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1483]
ILSpy version 5.0.0.4733-preview1

go to any .g.baml record from resources:

```
ICSharpCode.ILSpy.AssertionFailedException
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage)
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at ILSpy.BamlDecompiler.Baml.SizedBamlRecord.Read(BamlBinaryReader reader)
   at ILSpy.BamlDecompiler.Baml.BamlReader.ReadDocument(Stream str, CancellationToken token)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadBaml(AvalonEditTextOutput output, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.<>c__DisplayClass1_1.<View>b__2()
```

target: https://www.sendspace.com/file/90ggfw

PS works (decodes) fine in dnSpy 604

**Comment by siegfriedpammer** [comment]
I get the same assertion in dnSpy. You probably did not use a debug build of dnSpy (thus no assertion).
Not sure how the BAML was generated, but the length of the record is definitely wrong, the BAML says it's 6 however the actual length of the record is 8: 2 bytes (short) + 4 bytes (string) + 1 byte (prefixed string length) + 1 byte (record length).

You can safely ignore this assertion.

**Comment by greenozon** [comment]
dnSpy project does not release debug builds, are you building by hands?
most probably baml was a bit eaten by obfuscator with a known aim to make life harder :)
and yeah - thanks for details on the issue.
