### ISSUE TITLE
Add more context into exception message when decompiling multiple items

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1486]
ILSpy version 5.0.0.4733-preview1

Sometimes when one decompiles lots of assemblies at the same time its not easy to understand what exactly item is guilty, eg:

```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.BlobReader.ReadByte()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.AddSecurityAttributes(DeclarativeSecurityAttribute secDecl)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.AddSecurityAttributes(DeclarativeSecurityAttributeHandleCollection securityDeclarations)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.GetAttributes()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileWholeModuleAsSingleFile(Boolean sortTypes)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileWholeModuleAsSingleFile()
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()

```

there were like 20-30 assemblies in the left tree view...
Would be more user friendly to catch this case and print originating assembly under analysis
what you think

**Comment by siegfriedpammer** [comment]
Did the improvements made in 4e173cc885512ac26f8692a7ee373bf10d0226af solve this issue for you? Thank you!

**Comment by greenozon** [comment]
Yeah,
thanks a bunch!
closing
