### ISSUE TITLE
AssertionFailedException in Decompiler.CSharp.Transforms.IntroduceUsingDeclarations.Run

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1487]
ILSpy version 5.0.0.4733-preview1

issue happens only if dropping 3 items to the left pane, if two or one - no issue!
that's a bit strange and unexpected

```
ICSharpCode.ILSpy.AssertionFailedException: Should not insert using declaration for namespace that is missing from the superset: ..........
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage)
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceUsingDeclarations.Run(AstNode rootNode, TransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass30_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

```

https://www.sendspace.com/file/s6a0d2

**Comment by siegfriedpammer** [comment]
This happens while trying to decompile `Infragistics.Win.UltraWinGrid.UltraGridColumn.GetDefaultEditor` in `infragistics.win.ultrawingrid.v3.2.dll`. The problem is the following:

Suppose we have 4 different classes `N1.A`, `N2.B`, `N1.C`, `N1.D`. Note that A, C, D are in the same namespace, however, B is in a different namespace. The inheritance tree is the following: A is base of B and B is base of C and D.

Now we have the following code: `A a = condition ? (A)instanceC : (A)instanceD;` which gets decompiled as `A a = condition ? (B)instanceC : (B)instanceD;`. If `N2` is not referenced by some other part of the code in  the IL, it is missing from our approximated set of required namespaces, which makes the assertion fail.

I don't see a good way to fix this, except maybe changing the expression builder to emit casts to the expected type (i.e. A in this case) rather than the next common base type of both expressions.

**Comment by dgrunwald** [comment]
There's no guarantee a "target type" exists in IL; we might be dealing with an implicitly typed stack slot.

I think the namespace-set approximation will have to take base classes into account.

**Comment by dgrunwald** [comment]
Of course in cases where a suitable type hint exists, we should use that; but there's no guarantee that the expression builder can always use a type hint; it will sometimes need to fall back to a base class, so the namespace-set approximation needs to take that into account.
