### ISSUE TITLE
System.BadImageFormatException: Read out of bounds.

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1488]
ILSpy version 5.0.0.4733-preview1

no issues in dnSpy

```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.BlobReader.ReadByte()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.AddSecurityAttributes(DeclarativeSecurityAttribute secDecl)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AttributeListBuilder.AddSecurityAttributes(DeclarativeSecurityAttributeHandleCollection securityDeclarations)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.GetAttributes()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass30_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

```

target:  https://www.sendspace.com/file/ubt8kz

**Comment by greenozon** [comment]
this is the guy from #1486
