### ISSUE TITLE
Command Line Decompiler: Unhandled Exception breaks decompilation

### ISSUE THREAD

**Issue by briveramelo** [icsharpcode/ILSpy#1494]
Hi all! First time posting here, so I hope you find this helpful. I truly appreciate this community and I hold nothing but the best intentions with my contributions here.

Using ilspycmd 4.0.0.4521
I found this show-stopping error in 2 separate locations when decompiling a Unity project .dll

https://github.com/icsharpcode/ILSpy/blob/3abb548e1e48e7a11937403fef9c9c1b6ff704e9/ICSharpCode.Decompiler/CSharp/Syntax/TypeSystemAstBuilder.cs#L1090

Stack Trace
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Error decompiling <<SOMECLASS>>..cctor
) ---> ICSharpCode.Decompiler.DecompilerException: Error decompiling <<SOMECLASS>>..cctor
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.<>c__DisplayClass109_0.<TryExtractExpression>g__MakeFieldReference|0()
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.<>c__DisplayClass109_0.<TryExtractExpression>g__ExtractExpression|1(Int64 n, Int64 d)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.TryExtractExpression(IType mathType, IType type, Object literalValue, String memberName, Boolean isDouble)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertFloatingPointLiteral(IType type, Object constantValue)
   at ICSharpCode.Decompiler.CSharp.Syntax.TypeSystemAstBuilder.ConvertConstantValue(IType expectedType, IType type, Object constantValue)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitLdcF4(LdcF4 inst, TranslationContext context)
   at ICSharpCode.Decompiler.IL.LdcF4.AcceptVisitor[C,T](ILVisitor`2 visitor, C context)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint)
   at ICSharpCode.Decompiler.CSharp.CallBuilder.BuildArgumentList(ExpectedTargetDetails expectedTargetDetails, ResolveResult target, IMethod method, Int32 firstParamIndex, IReadOnlyList`1 callArguments, IReadOnlyList`1 argumentToParameterMap)
   at ICSharpCode.Decompiler.CSharp.CallBuilder.Build(OpCode callOpCode, IMethod method, IReadOnlyList`1 callArguments, IReadOnlyList`1 argumentToParameterMap, IType constrainedTo)
   at ICSharpCode.Decompiler.CSharp.CallBuilder.Build(CallInstruction inst)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitNewObj(NewObj inst, TranslationContext context)
   at ICSharpCode.Decompiler.IL.NewObj.AcceptVisitor[C,T](ILVisitor`2 visitor, C context)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitStObj(StObj inst, TranslationContext context)
   at ICSharpCode.Decompiler.IL.StObj.AcceptVisitor[C,T](ILVisitor`2 visitor, C context)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Default(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass30_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, CancellationToken cancellationToken)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, CancellationToken cancellationToken)
   at ICSharpCode.Decompiler.Console.Program.DecompileAsProject(String assemblyFileName, String outputDirectory) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\Program.cs:line 127
   at ICSharpCode.Decompiler.Console.Program.<>c__DisplayClass0_0.<Main>b__1() in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\Program.cs:line 56
   at ICSharpCode.Decompiler.Console.Program.Main(String[] args) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\Program.cs:line 35
```

where SOMECLASS is defined like so
```
public static class SOMECLASS : object
	{
		private static Color[] colors = new Color[2];

		static SOMECLASS ()
		{
			SOMECLASS.colors[0] = Color.green;
			SOMECLASS.colors[1] = new Color(0.564601f, 0.3155463f, 0.21424613f);
		}
                ...
        }
```

It seems the TypeSystemAstBuilder throws an error from the Linq library `Single()` method when no fields are found for matching field names in the mathType. 

This unhandled exception means that no .cs files are produced and the project is not generated. I would consider this a critical error, and I would recommend simply not adding a resolve result if no matching field names can be found.

I personally hesitate to make any change because this error might be the tip of a bigger issue or perhaps a more recent patch, and there's likely much more going on than what I can see just peeking into this codebase

**Comment by briveramelo** [comment]
This issue appears resolved in the 5.0.0-preview version of ilspycmd
