### ISSUE TITLE
Fails to load .Net Standard 2.0 assembly (System.OutOfMemoryException)

### ISSUE THREAD

**Issue by colgreen** [icsharpcode/ILSpy#1495]
I have an assembly that targets .NET Standard 2.0, and:

- Is being compiled in VS2019
- On a PC with .NET 4.8 installed.

 Loading the dll into ILSpy produces the following error (in the right hand pane):

```
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

My initial suspicion is that this is related to .NET 4.8, but will investigate further and add further details if I find anything. 

I am attaching a zipped copy of the problem assembly.

[SharpNeatLib.zip](https://github.com/icsharpcode/ILSpy/files/3100055/SharpNeatLib.zip)

----
**UPDATE** I should have read the call stack; the problem is related to the assembly's pdb file. If I delete that file then the dll loads OK. Also, I uninstalled .NET Framework 4.8 and compiled within VS2017, and still get the same issue. 

Attaching zip of dll and pdb.

[SharpNeatLib-net472-dll-pdb.zip](https://github.com/icsharpcode/ILSpy/files/3100075/SharpNeatLib-net472-dll-pdb.zip)

**Comment by siegfriedpammer** [comment]
I cannot reproduce the problem in ILSpy 5. Could you please try the latest nightly build? https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy_binaries.zip?branch=master&job=Configuration%3A+Release Thank you!

**Comment by colgreen** [comment]
Yeh that version works fine... I didn't realise the PC I was using had a rather old version (2.4.0.1963).

Apologies and thank for your time/help.
