### ISSUE TITLE
XmlDocumentationProvider  Unable to load some XML files to have special characters

### ISSUE THREAD

**Issue by maikebing** [icsharpcode/ILSpy#1512]
![bug2](https://user-images.githubusercontent.com/3445167/57594406-7d466e00-7572-11e9-8eff-a240861aad5e.PNG)

[Polls.zip](https://github.com/icsharpcode/ILSpy/files/3171033/Polls.zip)

`var xmlDoc = new XmlDocumentationProvider(@"Polls.xml");`

The output character buffer is too small to contain decoded characters, and the operation "Unicode" encoding "UTF-8" returns "System.Text.DecoderExceptionFallback". Parameter name: chars

   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.Convert(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at System.Text.DecoderNLS.Convert(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.LinePositionMapper.GetPositionForLine(Int32 line)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List`1 indexList)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader)
   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider..ctor(String fileName)

**Comment by maikebing** [comment]
![bug](https://user-images.githubusercontent.com/3445167/57594338-11fc9c00-7572-11e9-9960-c67e8ce1a5d1.PNG)

**Comment by maikebing** [comment]
I wrote the following code, but I don't get an error, I don't know exactly what caused it.
```
 byte[] input = new byte[] { 172 };
            char[] output = new char[] { (char)32};
            int bytesUsed=1, charsUsed=0;
            bool completed;
            System.Text.UTF8Encoding.UTF32.GetDecoder().Convert(input, 0, 1, output, 0, 1, false, out bytesUsed, out charsUsed, out completed);
```

**Comment by wiz0u** [comment]
I experienced this issue with the Telegram.Bot nuget package as well
