### ISSUE TITLE
Issue saving project to disk

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1601]
ILSpy version 5.0.0.4970-preview3

This happens even I said  - "overwrite OK"

```
System.IO.IOException: Cannot create "C:\........." because a file or directory with the same name already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<WriteResourceFilesInProject>d__31.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()

```

https://www.sendspace.com/file/axgrv0

**Comment by dgrunwald** [comment]
I cannot reproduce this.

The code in question is calling [Directory.CreateDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.createdirectory?view=netframework-4.8#System_IO_Directory_CreateDirectory_System_String_) which is not supposed to crash when the directory already exists.

**Comment by greenozon** [comment]
that's right,
I"m not able to reproduce this issue anymore...
tried on ILSpy version 5.0.0.4988-preview3

I"ve one idea - usually I"m decompiling lots of inputs into one directory, so maybe there was a kind of OS limit reached.... who knows
but I"m cleaning that dir from time to time, so.. thats just a guess.

Now, as it is not possible to decompile > 1 assembly at a time (some new bug was added recently)
ref to #1598  - I doubt its feasable in the near time.

**Comment by riQQ** [comment]
Maybe if there's already a file with the desired folder name?

**Comment by siegfriedpammer** [comment]
@greenozon as #1598 is now fixed, could you try to reproduce this issue again? Thank you very much!

**Comment by greenozon** [comment]
can't repro, closing
thanks for reminder
