### ISSUE TITLE
assert at ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase)//Container should not have any unreachable blocks

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1621]
Tested with 5.0.0.5049-preview4.

Assertion Failed
Container should not have any unreachable blocks

   at ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase)
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
   at ICSharpCode.Decompiler.IL.ILFunction.CheckInvariant(ILPhase phase)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext deco...

It can be reproduce with 
an old version of [System.Private.DataContractSerialization](https://www.nuget.org/packages/System.Private.DataContractSerialization/4.3.0/)/string System.Xml.ValueHandle.GetString()

or the below code.
```csharp
        private string TestSwitch(int x)
        {
            if (x == 5)
            {
                return "5";
            }

            switch (x)
            {
                case 1: return "1";
                case 2:
                case 6:
                case 7:
                    return "2-6-7";
                case 3: return "3";
                case 4: return "4";
                case 5: return "unreachable";//this line
                default: throw new Exception();
            }
        }
```

**Comment by siegfriedpammer** [comment]
I was able to fix the assertion by adding

	if (matchValues.IsEmpty)
		return false;

at line 183 https://github.com/icsharpcode/ILSpy/blob/f49cc11c76147edfb830263e0558ecfcc43724ad/ICSharpCode.Decompiler/IL/ControlFlow/SwitchAnalysis.cs#L182-L187

However, I am not an expert in that part of the decompiler, so I am not going to add that without checking back with you @dgrunwald.

**Comment by siegfriedpammer** [comment]
This causes SwitchDetection to not inline the `return "5";` block into the switch, so the `return "unreachable";` block is not made unreachable.

**Comment by dgrunwald** [comment]
In "remove dead code" mode we may want to instead eliminate the unreachable block(s), but for normal mode this looks like the correct fix.
