### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1625]
ILSpy version 5.0.0.5049-preview4

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ILSpy.BamlDecompiler.Baml.KnownThings.ResolveAssembly(String name)
   at ILSpy.BamlDecompiler.Baml.KnownThings.InitAssemblies()
   at ILSpy.BamlDecompiler.Baml.KnownThings..ctor(IDecompilerTypeSystem typeSystem)
   at ILSpy.BamlDecompiler.Baml.BamlContext..ctor(IDecompilerTypeSystem typeSystem)
   at ILSpy.BamlDecompiler.Baml.BamlContext.ConstructContext(IDecompilerTypeSystem typeSystem, BamlDocument document, CancellationToken token)
   at ILSpy.BamlDecompiler.XamlContext.Construct(IDecompilerTypeSystem typeSystem, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions)
   at ILSpy.BamlDecompiler.XamlDecompiler.Decompile(IDecompilerTypeSystem typeSystem, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions, List`1 assemblyReferences)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceFileHandler.WriteResourceToFile(LoadedAssembly assembly, String fileName, Stream stream, DecompilationOptions options)
   at ICSharpCode.ILSpy.CSharpLanguage.ILSpyWholeProjectDecompiler.WriteResourceToFile(String fileName, String resourceName, Stream entryStream)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<WriteResourceFilesInProject>d__35.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()

```

https://www.sendspace.com/file/ers2qe

**Comment by siegfriedpammer** [comment]
Sorry, I cannot reproduce this. I used an empty assembly list to decompile the whole assembly.

**Comment by greenozon** [comment]
Tested on ILSpy version 5.0.0.5057-preview4
not able to reproduce as well, closing
