### ISSUE TITLE
assert at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() 

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1629]
Tested with 5.0.0.5059-preview4

@dgrunwald Similar to #1619, but `netcoreapp 3.0.0-preview7` should already use the new format?

1. Open `System.Private.CoreLib.dll` from netcoreapp 3.0.0-preview7;
2. C# 8.0;
3. Go to class `Dictionary<TKey, TValue>`, and see some assert;
4. Expand the left treeList, and see some other assert;

Some different stacks
<details>

```cs
ICSharpCode.ILSpy.AssertionFailedException
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType()
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type)
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.ArrayType.VisitChildren(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.TypeVisitor.VisitArrayType(ArrayType type)
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitArrayType(ArrayType type)
   at ICSharpCode.Decompiler.TypeSystem.ArrayType.AcceptVisitor(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataField.DecodeTypeAndVolatileFlag()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataField.get_Type()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataField.ICSharpCode.Decompiler.TypeSystem.IMember.get_ReturnType()
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.<>c__DisplayClass62_0.<ResolveFieldReference>b__0(IField f)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.<ApplyFilter>d__105`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.ResolveFieldReference(MemberReferenceHandle memberReferenceHandle, GenericContext context)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.ResolveEntity(EntityHandle entityHandle, GenericContext context)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesFromMethodBody(MethodBodyBlock method, MetadataModule module)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileProperty(IProperty property, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.PropertyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass36_0.<DecompileAsync>b__0()
```
or 
```cs
ICSharpCode.ILSpy.AssertionFailedException
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType()
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type)
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.ArrayType.VisitChildren(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.TypeVisitor.VisitArrayType(ArrayType type)
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitArrayType(ArrayType type)
   at ICSharpCode.Decompiler.TypeSystem.ArrayType.AcceptVisitor(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.get_ReturnType()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.MethodTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass36_0.<DecompileAsync>b__0()
```
or
```cs
ICSharpCode.ILSpy.AssertionFailedException
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType()
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type)
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor)
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.get_ReturnType()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.MethodTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass36_0.<DecompileAsync>b__0()
```

</details>

-----

BTW: ***Seems an deadlock happen when I expand the left treeList in C#1.0 with assert***
1. Close and restart ILSpy;
2. Switch to C#1.0;
3. Expand `Dictionary<TKey, TValue>`(Require be the first time after start ILSpy);
4. Choose throw;
5. Deadlock in `ILSpyTraceListener.Fail`->`thread.Join();`

**Comment by dgrunwald** [comment]
Looks like that assembly is built with
  `[module: NullablePublicOnly(IncludesInternals: false)]`
which means private members are lacking nullability annotations.
We currently don't handle this attribute, and instead try to apply the `NullableContext` to all members without an explicit `NullableAttribute`.
