### ISSUE TITLE
Error on saving solution with multiple assemblies at a time

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1663]
ILSpy version 5.0.0.5093-preview4

as mentioned in previous issue, this error is a bit strange
it happens only if you save all 3  as a signle operation
not happening when saving separtely each!

```
Failed to decompile the assembly 'C:\-------Generator.dll':
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp----------------------------------------V--allocator-PEAVGRe\-lambda_d951b2ca66984381cd319dfda8800370-.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass34_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, CancellationToken cancellationToken)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.SolutionWriter.WriteProject(LoadedAssembly loadedAssembly, Language language, String targetDirectory, CancellationToken ct)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\delme\GDrawingGenerator\-GenerateDynamicReinforcement-GDrawingGeneratorImpl----FQEAAXPEAVObjectDatabaseInterface-Native-Core-Bim-Graitec--AEBJAEBV--vector-PEAVGReinfBarObjectData-Native-Core-Bim-Graitec--V--allocator-PEAVGRe\-lambda_d951b2ca66984381cd319dfda8800370-.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass34_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

..............
```

https://www.sendspace.com/file/127w5m

**Comment by siegfriedpammer** [comment]
I just checked whether this still occurs. It doesn't for me with the current master. Can you confirm?

**Comment by greenozon** [comment]
Yes, it's still reproducible on my side
used following ILSpy version: ILSpy version 6.2.0.6053-preview1

https://www.sendspace.com/file/2z2thu

and having multiple issues like above

steps - select all and drop into IL, then save all.

My gut feeling says that this is most probably due to mixed mode assemblies...

Expectation: save to disk, not throw exceptions like above

**Comment by siegfriedpammer** [comment]
> steps - select all and drop into IL, then save all.

so you are trying to create a solution consisting of IL projects? This is rather unexpected and probably the source of weird crashes...

**Comment by siegfriedpammer** [comment]
I have fixed some bugs in the relevant parts of ILSpy. Can you please try the latest version? Thanks!

**Comment by greenozon** [comment]
Thanks
there is one assembly GDrawingGenerator.dll (from above archive)
it generates following exception why trying to save as project

System.IO.DirectoryNotFoundException: Could not find a part of the path...

**Comment by siegfriedpammer** [comment]
Sorry, again I cannot reproduce this. It seems it is depending on where you save the project to, whether the target directory is empty, which language do you have selected in ILSpy, etc.
Can you please be very explicit and detailed in your problem description? Thank you!

**Comment by greenozon** [comment]
Issue gone once I did the menu operation:
View - Options - Reset to defaults - Yes - OK
C#, C# 7.3
feel free to close

**Comment by siegfriedpammer** [comment]
OK, thanks!
