### ISSUE TITLE
Can't browse .net assembly

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1664]
ILSpy version 5.0.0.5096-preview4

in fact this is .net assembly
but marked by yellow exclamation sign and showing this to the right -

```
// C:\Temp\err87.dll
// This file does not contain a managed assembly.

System.BadImageFormatException: Illegal tables in compressed metadata stream.
   at System.Reflection.Metadata.MetadataReader.ReadMetadataTableHeader(BlobReader& reader, HeapSizes& heapSizes, Int32[]& metadataTableRowCounts, TableMask& sortedTables)
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
   at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, Stream stream, PEStreamOptions streamOptions, MetadataReaderOptions metadataOptions)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

https://www.sendspace.com/file/a1ve68

Note: dnSpy is showing all the ns/classes/etc in the left tree pane..

**Comment by dgrunwald** [comment]
That means it's not actually a valid .NET assembly.
If an assembly is obfuscated so badly that `System.Reflection.Metadata` will refuse to load it, we'll never support it in ILSpy.

**Comment by greenozon** [comment]
agree,

just to add some facts - 
here is normal assembly  (any other randomly choosen) - 

![image](https://user-images.githubusercontent.com/765343/63636743-245f9900-c67c-11e9-82aa-a7d650dd8529.png)


here is assembly under question

![image](https://user-images.githubusercontent.com/765343/63636748-2fb2c480-c67c-11e9-8a1b-1b440b8f8efe.png)


pics are from dnSpy

I guess blocks in red are stoppers for system loader
