### ISSUE TITLE
Error when saving code

### ISSUE THREAD

**Issue by asdf23** [icsharpcode/ILSpy#1700]
I'm receiving the following error
```
System.ArgumentException: Cannot find StaticResource: 0
Parameter name: identifier
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.GetStaticResource(Int16 identifier)
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.ReadPropertyWithStaticResourceIdentifier()
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.ReadInternal()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceFileHandler.WriteResourceToFile(LoadedAssembly assembly, String fileName, Stream stream, DecompilationOptions options)
   at ICSharpCode.ILSpy.CSharpLanguage.ILSpyWholeProjectDecompiler.WriteResourceToFile(String fileName, String resourceName, Stream entryStream)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<WriteResourceFilesInProject>d__31.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass46_0.<SaveToDiskAsync>b__0()
```
 
I need to look into if there is any sort of licensing issues giving the assembly that was used to generate this error.

**Comment by greenozon** [comment]
similar to this one?
#1354

**Comment by siegfriedpammer** [comment]
@asdf23 you are using an old version, please try the latest release of ILSpy.

**Comment by asdf23** [comment]
I'm using ILSpy version 4.0.1.4530

**Comment by siegfriedpammer** [comment]
Yes, this is likely fixed in the latest release candidate of ILSpy 5.0.

**Comment by asdf23** [comment]
Is there a pre-release I can download? I can test it

**Comment by asdf23** [comment]
Yes that fixes the issue I was seeing
