### ISSUE TITLE
ILSpyAddin: Crash when used in metadata definition

### ISSUE THREAD

**Issue by wiz0u** [icsharpcode/ILSpy#1721]
When navigating to .NET system library definition (using F12 or ctrl-click on a symbol), then using ILSpyAddIn to view a decompiled method, it crashes (see stacktrace from Event Viewer below)

Step to reproduce:

*   Under VS2019, create a new project "Windows Forms App (.NET Core)"
*   In Program.Main(), click on `Application.Run`
* Navigate to definition (with F12 or Ctrl-click on symbol)
* This opens a 'metadata' view of the Application class
* Right-click on a member > "Open code in ILSpy"
* Crash

ILSpy/ILSpyAddIn 5.0.0.5124

	Application: devenv.exe
	Framework Version: v4.0.30319
	Description: The process was terminated due to an unhandled exception.
	Exception Info: System.NullReferenceException
	   at ICSharpCode.ILSpy.AddIn.Commands.OpenCodeItemCommand+<OnExecute>d__5.MoveNext()
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
	   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
	   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
	   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
	   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by wiz0u** [comment]
This seems not specific to .NET Core apps

**Comment by Rpinski** [comment]
Which exact VS version do you use? I could not reproduce the issue, because the "Open code in ILSpy" item doesn't appear in metadata views at all.

**Comment by wiz0u** [comment]
VS Community 2019 16.3.1

**Comment by wiz0u** [comment]
![image](https://user-images.githubusercontent.com/11647984/65819412-98153880-e21c-11e9-9539-5b2052fe1d99.png)

**Comment by wiz0u** [comment]
I moved the "Open code in ILSpy" item on top of the context menu using the "Customize..." menu, could this be the issue?

**Comment by christophwille** [comment]
I just tried with latest from https://ci.appveyor.com/project/icsharpcode/ilspy/builds/27736391/job/7ph9sj7rt06mof3t/artifacts and I too do not see Open in ILSpy on the context menu.

**Comment by Rpinski** [comment]
@wiz0u After several attempts and restarts I've finally managed to reproduce your case. We don't have any analyzable data in metadata view and tell VS to hide our menu item. But VS sometimes still shows it, maybe due to menu customization.
As a workaround I will add an additional check here to prevent the crash, but actually this is a VS bug from my view.
