### ISSUE TITLE
DotNetCorePathFinder should handle Microsoft.AspNetCore.All missing

### ISSUE THREAD

**Issue by huoyaoyuan** [icsharpcode/ILSpy#1750]
#### Version used
5.0.1.5145 from VS extension
#### Reproducing
Right click in VS and select "Open output in ILSpy" on .NET Standard library project. Doesn't reproduce on .NET Core console application or `netstandard.dll` itself.
Select decompilation to C#.
#### Behavior
```
System.IO.DirectoryNotFoundException: Cannot find part of path "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All"
  (Framework core)
  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder.GetClosestVersionFolder(String basePath, Version version)
  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder.FallbackToDotNetSharedDirectory(IAssemblyReference name, Version version)
  at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.FindAssemblyFile(IAssemblyReference name)
  at ICSharpCode.ILSpy.LoadedAssembly.LookupReferencedAssemblyInternal(IAssemblyReference fullName, Boolean isWinRT)
  (Bootstrap code)
```
#### Expected
`Microsoft.AspNetCore.All` is deprecated from 3.0. VS installer cannot fully uninstall previous versions. If you update sdk from VS, the folder is still present. However, if you do a clean install for all .NET Core components, the folder won't exist.

The library doesn't use asp.net at all. For conciseness, the asp.net folder shouldn't get touched.

For robustness, the reference finder should expect anything to fail, not only for the deprecated package.

**Comment by christophwille** [comment]
@Rpinski is this related to the added better detection of ref asm in 5.0.1?
