### ISSUE TITLE
Error decompiling .NET Core 3.0 assembly in Linux

### ISSUE THREAD

**Issue by rafael-teixeira** [icsharpcode/ILSpy#1757]
Hello,

I am facing an issue trying to decompile .NET Core app that was published for Linux. In fact, this assembly has no explicitly dependency to any Microsoft.WindowsDesktop.App packages and this part of .NET Core 3.0 runtime (Microsoft.WindowsDesktop.App) is not installed on Linux.

```
rafaelt@LinuxDebuggingVm:~/Demo-CrashApp$ ilspycmd Demo-NETCoreApplicationError.dll
System.IO.DirectoryNotFoundException: Could not find a part of the path /usr/share/dotnet/shared/Microsoft.WindowsDesktop.App.
   at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories()
   at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder.GetClosestVersionFolder(String basePath, Version version)
   at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder.FallbackToDotNetSharedDirectory(IAssemblyReference name, Version version)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.FindAssemblyFile(IAssemblyReference name)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.Resolve(IAssemblyReference name)
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions)
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.GetDecompiler(String assemblyFileName, String[] referencePaths) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 127
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.Decompile(String assemblyFileName, TextWriter output, String[] referencePaths, String typeName) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 169
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 63.
```

**.NET Core version**
rafaelt@LinuxDebuggingVm:~/Demo-CrashApp$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by siegfriedpammer** [comment]
Probably related to #1750
