### ISSUE TITLE
Decompile whole Assembly from nuget package is much more slower than directly from dll?

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1762]
Tested with ILSpy 5.0.1/master and `ICSharpCode.Decompiler` 5.0.1 from nuget.

x|5.0.1(Rel)|master(Rel)+patch1|master(Rel)+patch1+patch2
----|----|----|----
DLL|9.6s|6.8s|6.0s
NUGET|227.8s|52.6s|6.8s

Most time is taken by `PEReaderExtensions.GetMethodBody()`, and cancellationToken not work at the stage.
```
at mscorlib.dll!System.IO.MemoryStream.Read(byte[] buffer, int offset, int count)
at System.Reflection.Metadata.dll!System.Reflection.Internal.StreamExtensions.CopyTo(System.IO.Stream source, byte* destination, int size)
at System.Reflection.Metadata.dll!System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(System.IO.Stream stream, bool isFileStream, long start, int size)
at System.Reflection.Metadata.dll!System.Reflection.Internal.StreamMemoryBlockProvider.GetMemoryBlockImpl(int start, int size)
at System.Reflection.Metadata.dll!System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(int index)
at System.Reflection.Metadata.dll!System.Reflection.PortableExecutable.PEReader.GetSectionData(int relativeVirtualAddress)
at System.Reflection.Metadata.PEReaderExtensions.GetMethodBody() from ICSharpCode.Decompiler.CSharp.CSharpDecompiler.GetCodeMappingInfo()
at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.ReadCodeMappingInfo(ICSharpCode.Decompiler.Metadata.PEFile module, ICSharpCode.Decompiler.Metadata.CodeMappingInfo info, System.Reflection.Metadata.MethodDefinitionHandle parent, System.Reflection.Metadata.MethodDefinitionHandle part, System.Collections.Generic.Queue<System.Reflection.Metadata.MethodDefinitionHandle> connectedMethods, System.Collections.Generic.HashSet<System.Reflection.Metadata.TypeDefinitionHandle> processedNestedTypes)
at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.GetCodeMappingInfo(ICSharpCode.Decompiler.Metadata.PEFile module, System.Reflection.Metadata.EntityHandle member)
at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(ICSharpCode.Decompiler.TypeSystem.IEntity entity, ICSharpCode.Decompiler.TypeSystem.MetadataModule module, ICSharpCode.Decompiler.Metadata.CodeMappingInfo mappingInfo)
at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(ICSharpCode.Decompiler.TypeSystem.IEntity entity, ICSharpCode.Decompiler.TypeSystem.MetadataModule module, System.Collections.Generic.HashSet<string> namespaces)
at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(System.Reflection.Metadata.EntityHandle entity, ICSharpCode.Decompiler.TypeSystem.MetadataModule module, System.Collections.Generic.HashSet<string> namespaces)
at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(System.Collections.Generic.IEnumerable<System.Reflection.Metadata.TypeDefinitionHandle> types)
at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.WriteCodeFilesInProject.AnonymousMethod__2(System.Linq.IGrouping<string, System.Reflection.Metadata.TypeDefinitionHandle> file)
```

Not sure, but maybe `mappingInfo` should also be pass in here? Shown as `patch1` in the above table.
https://github.com/icsharpcode/ILSpy/blob/59b7e0c986e51d9f563ac7f24000f4cd09b76f96/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs#L123-L132

***Updated:***
Shown as `patch2` in the above table.
https://github.com/icsharpcode/ILSpy/blob/ba22906b3bf7e8b93a4f49c7ea8999b157b328fa/ILSpy/LoadedAssembly.cs#L157-L165
```cs
			if (state is Stream stream) {
				// Read the module from a precrafted stream
				module = new PEFile(fileName, stream, stream is MemoryStream ? PEStreamOptions.PrefetchEntireImage : PEStreamOptions.Default, metadataOptions: options);
			} else {
```

**Comment by siegfriedpammer** [comment]
I am curious which assembly you used for comparison. Could you post the code you used? Thank you very much for testing and fixing this.

**Comment by yyjdelete** [comment]
Just tested with `ICSharpCode.Decompiler` itself, just open the .nuget or unpacked dll from ILSpy.exe and click `Save Code` manually.
https://www.nuget.org/api/v2/package/ICSharpCode.Decompiler/5.0.1.5145
