### ISSUE TITLE
ArgumentOutOfRangeException in `AvalonEdit.Document.TextDocument.GetLineByOffset` random happen with double click

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1862]
Test in master
<del>It's also possible to reproduce in v5.0.1 but not v5.0.0.</del>

Seems an concurrent issue that random happen between jump and select, and the select event is fired on an different document after the document is changed and not the old one.
<del>Maybe related to 83ea3449d181818dde01988e625eb83b61018c4e, since it's the only related change between v5.0.0 and v5.0.1, but I don't know the reason.</del>
The `textArea_MouseLeftButtonUp` version only happen for >=5.0.1, but `textArea_MouseMove` seems happen on all versions.

***I used to have about 1/3 chance to reproduce it, but I'm unable to reproduce it not. I just report it, in case someone know the reason and the way to fix it.***
1. Fouble click and jump from any long file to an short file. For example, open `System.IO.Stream` and double click `IDisposable` in interfaces list.

```cs
System.ArgumentOutOfRangeException: 0 <= offset <= 255

Parameter name: offset

The actual value is 535.
   at ICSharpCode.AvalonEdit.Document.TextDocument.GetLineByOffset(Int32 offset)
   at ICSharpCode.AvalonEdit.Document.TextDocument.GetLocation(Int32 offset)
   at ICSharpCode.AvalonEdit.Editing.Selection.Create(TextArea textArea, Int32 startOffset, Int32 endOffset)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.ExtendSelectionToMouse(MouseEventArgs e)
//<--- or textArea_MouseMove
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.textArea_MouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by yyjdelete** [comment]
Seems `TextArea.MouseSelectionMode = MouseSelectionMode.None;` should also be apply in one of the below place(reset mouse selection when document changed), not sure which one is better.

`DecompilerTextView.ShowOutput(...)`
https://github.com/icsharpcode/ILSpy/blob/83ea3449d181818dde01988e625eb83b61018c4e/ILSpy/TextView/DecompilerTextView.cs#L388
or `TextArea.OnDocumentChanged(...)` in AvalonEdit(there is already a comment here but not handle for mouse)
https://github.com/icsharpcode/AvalonEdit/blob/396fabc0cd0fbac504634c06749863e80fa7ddea/ICSharpCode.AvalonEdit/Editing/TextArea.cs#L224-L227
