### ISSUE TITLE
Failed to translate DisplayClass in some special local function

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1913]
Tested with `6.0.0.5559-preview2`

### Orig Code
```cs
using System;

namespace ConsoleApp4
{
    public class CZZZ
    {
        static int count;

        static void Main()
        {
            Console.WriteLine(M1());
            Console.WriteLine(M2());
        }
        public static int M1()
        {
            count = 0;
            int _x;
            return M1_x();

            int M1_x()
            {
                TryGetX(out _x);
                if (++count == 1)
                {
                    M1_x();
                }
                return _x;
            }
        }

        public static int M2()
        {
            int _x;
            M2_x();
            return _x;

            void M2_x()
            {
                _x = 0;
            }
        }

        private static bool TryGetX(out int x)
        {
            x = count;
            return true;
        }
    }
}
```

### Actual
`M1`: `InvalidOperationException: Sequence contains no elements`, maybe related to #1781
```cs
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.IsClosure(ILTransformContext context, ILVariable variable, ITypeDefinition& closureType, ILInstruction& initializer)
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.Run(ILFunction function, ILTransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
```

`M1`: After modified `variable.HasInitialValue` to `variable.AddressCount > 0`(which also fix #1781) in `TransformDisplayClassUsage.cs`, it not throw exception.
https://github.com/icsharpcode/ILSpy/blob/d8a08822b728bbd708784804870ea6e89c5994bb/ICSharpCode.Decompiler/IL/Transforms/TransformDisplayClassUsage.cs#L167

But the scope of `_x` will be changed, and it will return 0 instead of 1 in new code.
```cs
public static int M1()
{
	count = 0;
	return M1_x();
	int M1_x()
	{
		TryGetX(out int _x);
		if (++count == 1)
		{
			M1_x();
		}
		return _x;
	}
}
```

`M2`: Maybe an variant of `M1`, it will not throw `InvalidOperationException`, but will hit some assert and see the `return` is lost.
```cs
public static int M2()
{
	M2();
	int _x;
//<--see the `return` is lost.
	void M2()
	{
		_x = 0;
	}
}
```

**Comment by siegfriedpammer** [comment]
For the method `M2` I have added a fix to prevent removing the return statement.

@dgrunwald Do you have any idea how we could extend the `DeclareVariables` step to support correctly declaring variables captured in local functions that do not have any use-sites except the calls to the local function?
