### ISSUE TITLE
System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1950]
```
Error decompiling @0600022C System.DataSqLite.Dapper.SqlMapper.GridReader.MultiReadInternal
 ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) in offset 11
   at System.Collections.Generic.Dictionary`2.Remove(TKey key) in offset 8
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.<>c__DisplayClass35_0.<ReconstructTryFinallyBlocks>g__CreateTryBlock|1(Block block, Int32 state) in YieldReturnDecompiler.cs:line 1005
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.ReconstructTryFinallyBlocks(ILFunction iteratorFunction) in YieldReturnDecompiler.cs:line 957
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.Run(ILFunction function, ILTransformContext context) in YieldReturnDecompiler.cs:line 170
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1320
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1363
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1259
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 889
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in CSharpDecompiler.cs:line 852
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options) in CSharpLanguage.cs:line 149
   at ICSharpCode.ILSpy.TreeNodes.MethodTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in MethodTreeNode.cs:line 88
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in DecompilerTextView.cs:line 782
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass48_0.<DecompileAsync>b__0() in DecompilerTextView.cs:line 758
```

[file.zip](https://github.com/icsharpcode/ILSpy/files/4305724/file.zip)

**Comment by dgrunwald** [comment]
`GridReader.<MultiReadInternal>d__44<TReturn>` seems broken:
`MoveNext` looks like the usual foreach loop with a `yield return` inside the loop body.
At the end of the iteration, this disposes the wrapped enumerator via `<>m__Finally2`.

But the `Dispose` method doesn't match this: in state 1 it needs to call the finally blocks to dispose the wrapped enumerator + call `NextResult` if the wrapping enumerator is disposed early. But the code to do this is missing from `Dispose`. This also means that despite appearing in a `finally` block in the original C#, the `NextResult` method call will not happen if there's an exception.
This seems like a compiler bug in whichever C# compiler was used to compile the binary provided.

The result is a broken enumerator that cannot be decompiled to C# `yield return`.

**Comment by dgrunwald** [comment]
New output:
```
private IEnumerable<TReturn> MultiReadInternal<TReturn>(Type[] types, Func<object[], TReturn> map, string splitOn)
{
	Identity identity = this.identity.ForGrid(typeof(TReturn), types, gridIndex);
	try
	{
		IEnumerator<TReturn> enumerator = ((IDbConnection)null).MultiMapImpl(default(CommandDefinition), types, map, splitOn, reader, identity, finalize: false).GetEnumerator();
		try
		{
			while (enumerator.MoveNext())
			{
				yield return enumerator.Current;
			}
			((<MultiReadInternal>d__44<TReturn>)/*Error near IL_00a1: stateMachine*/).<>m__Finally2();
			((<MultiReadInternal>d__44<TReturn>)/*Error near IL_00ae: stateMachine*/).<>m__Finally1();
		}
		finally
		{
			/*Error: Could not find finallyMethod for state=-4.
Possibly this method is affected by a C# compiler bug that causes the finally body
not to run in case of an exception or early 'break;' out of a loop consuming this iterable.*/;
		}
	}
	finally
	{
		/*Error: Could not find finallyMethod for state=-3.
Possibly this method is affected by a C# compiler bug that causes the finally body
not to run in case of an exception or early 'break;' out of a loop consuming this iterable.*/;
	}
}
```
