### ISSUE TITLE
Missing ContainsKey in PortablePdbWriter.cs

### ISSUE THREAD

**Issue by mohemiv** [icsharpcode/ILSpy#1957]
ILSpy version 6.0.0.5559-preview2
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.<>c__DisplayClass7_0.<WritePdb>g__ProcessMethod|5(MethodDefinitionHandle method, DocumentHandle document, List`1 sequencePoints, SyntaxTree syntaxTree)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.WritePdb(PEFile file, CSharpDecompiler decompiler, DecompilerSettings settings, Stream targetStream, Boolean noLogo)
   at ICSharpCode.ILSpy.GeneratePdbContextMenuEntry.<>c__DisplayClass3_0.<GeneratePdbForAssembly>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by siegfriedpammer** [comment]
This exception occurs when a method is processed multiple times. For example, when (due to a bug) a method that is used in another method is wrongly detected as a lambda/delegate and then processed multiple times by the DebugInfoGenerator. See #1926 for a discussion of a possible fix.

**Comment by JarLob** [comment]
Attaching a standard dll from GAC that triggers the exception on PDB generation. [System.Data.dll.zip](https://github.com/icsharpcode/ILSpy/files/4948206/System.Data.dll.zip)

**Comment by siegfriedpammer** [comment]
Since 5a8b488e99415c1e1b5c2f44820be666c491b91a this exception is now a debug assertion. Duplicate definitions of sequence points are now ignored. The first definition "wins".
