### ISSUE TITLE
InvalidOperationException: Sequence contains no elements. in TextView.DecompilerTextViewState.SaveFoldingsState

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1971]
Test with master

That happens when open an empty xml file in resource and then switch to any other node.

```cs
System.InvalidOperationException: Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at ICSharpCode.ILSpy.TextView.DecompilerTextViewState.SaveFoldingsState(IEnumerable`1 foldings)

   at ICSharpCode.ILSpy.TextView.DecompilerTextView.GetState()

   at ICSharpCode.ILSpy.TextView.DecompilerTextView.ICSharpCode.ILSpy.ViewModels.IHaveState.GetState()

   at ICSharpCode.ILSpy.ViewModels.TabPageModel.GetState()

   at ICSharpCode.ILSpy.MainWindow.DecompileSelectedNodes(DecompilerTextViewState newState, Boolean recordHistory)

   at ICSharpCode.ILSpy.MainWindow.TreeView_SelectionChanged(Object sender, SelectionChangedEventArgs e)
```

**Comment by CreateAndInject** [comment]
I met this issue without any xml, I just view some .baml, but I can't reproduce it(I didn't update to this commit), is this any way to reproduce it with some wpf .baml?
