### ISSUE TITLE
Not possible to save project with very long names

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2038]
ILSpy version 6.0.0.5800-preview4

Proposal is to trim down such long names when exporting into project (as the OS has the limitation of 256 chars total)

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\------------------------------------------------------------------------------------------------------------------------------------------------------------\-lambda_d951b2ca66984381cd319dfda8800370-.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass39_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

```

https://www.sendspace.com/file/koowft

**Comment by siegfriedpammer** [comment]
This does not crash on my system. The path is longer than 250 characters. Which operating system are you using. If I recall correctly, ILSpy already supports paths longer than 250 characters.

**Comment by greenozon** [comment]
W7 x64
the question is to WInAPI I guess which allows up to MAX_PATH symbolx (260?)

**Comment by dgrunwald** [comment]
ILSpy has support for [long paths on Windows 10](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/).

**Comment by greenozon** [comment]
the article says that only starting from .NET 4.6.2 it was opened
what about those uses who are using older .net?

also I guess the mixed mode assemlbies might  have such a long names (due to STL + nam decorations) that it easily might be > 1K of symbols or even bigger

Not sure if users would like to have such a long filenames on their FS...

To summarize: the proposal is to trim down long filenames to some considerable length

(tested on dnSpy - it trims to 64 bytes)

**Comment by siegfriedpammer** [comment]
> the article says that only starting from .NET 4.6.2 it was opened
what about those uses who are using older .net?

ILSpy is currently targeting .NET 4.7.2, it won't run on older versions.
https://github.com/icsharpcode/ILSpy/blob/e3258bd322198c4cac7e62b99664884f1a9b495a/ILSpy/ILSpy.csproj#L5

> To summarize: the proposal is to trim down long filenames to some considerable length

Yes, I think we could do something like that.

**Comment by dgrunwald** [comment]
The current filename logic already prevents names from exceeding 200 chars.
I don't think we should decrease that amount unless we make it dependent on long path support in Windows.

**Comment by siegfriedpammer** [comment]
Is there anything we can/should do to improve the situation or can we close this issue? Currently, there is no solution we have decided on...

**Comment by dgrunwald** [comment]
I see two options:
1. Check the LongPathsEnabled registry key and shorten names more aggressively if it isn't set.
2. Just close this issue and expect users to set the registry key.
