### ISSUE TITLE
Illegal tables in compressed metadata stream

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2042]
ILSpy version 6.0.0.5800-preview4

Not sure if such kind of issue is up to ILSpy, just wanted to make sure
So, in case something was changed in .net direcotory of PE binary,
what's the expected behaviour of ILSpy?

for the moment it throws the below exception, but probably it'll make sense to show at least PE sections/whaterver else coudl be read out?
dnSpy parses this file normally and shows everything including .net types/methods/etc

```
System.BadImageFormatException: Illegal tables in compressed metadata stream.
   at System.Reflection.Metadata.MetadataReader.ReadMetadataTableHeader(BlobReader& reader, HeapSizes& heapSizes, Int32[]& metadataTableRowCounts, TableMask& sortedTables)
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
   at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, Stream stream, PEStreamOptions streamOptions, MetadataReaderOptions metadataOptions)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ICSharpCode.ILSpy.LoadedAssembly.GetPEFileOrNull()
```

**Comment by siegfriedpammer** [comment]
This is a limitation of System.Reflection.Metadata. We cannot do anything about it. The only possibility would be to use dnlib (which is what dnSpy uses). Not sure, if anyone from Microsoft would be interested in making SRM more resilient.

See #1231 for a discussion about such issues.

**Comment by greenozon** [comment]
Thanks for commenting this out
