### ISSUE TITLE
Error decompiling .NET Core 4.0 assembly in Linux

### ISSUE THREAD

**Issue by poggersplayzyt** [icsharpcode/ILSpy#2089]
Hello, 

I am encountering an issue trying to decompile .NET Core app that was made for Linux.

### Error message shown

```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinderExtensions.DetectTargetFrameworkId(PEReader assembly, String assemblyPath)
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.DecompileAsProject(String assemblyFileName, String outputDirectory) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 179
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 83
```

### Details
* Product in use: e.g. ICSharpCode.Decompiler nuget package
* Version in use: e.g. 6.1

**Comment by linquize** [comment]
Do you mean .NET 5?

**Comment by poggersplayzyt** [comment]
Yes my bad.

**Comment by christophwille** [comment]
Does this happen with any .NET Core 5.0 assembly or is this specific to a more complex scenario?

**Comment by poggersplayzyt** [comment]
> Does this happen with any .NET Core 5.0 assembly or is this specific to a more complex scenario?

A more complex scenario.

**Comment by dgrunwald** [comment]
The only thing I can think of is that the assembly has an invalid attribute or reference.
Does this crash occur with an obfuscated assembly?
