### ISSUE TITLE
Uncatched FileNotFoundException

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2132]
### Steps to reproduce
1. Open ILSpy and open any nupkg;
2. Directly close ILSpy(with the nupkg selected);
3. Remove the nupkg file;
4. Reopen ILSpy;

### Error message shown
A dialog is shown, and the UI is empty(only the menu is shown) after close it.
Close and reopen ILSpy will remove the nupkg and works again.
```
---------------------------
Sorry, we crashed
---------------------------
System.IO.FileNotFoundException: The file "xxxx.nupkg" could not be found.
Filename:"xxxx.nupkg"

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
   at ICSharpCode.ILSpy.LoadedNugetPackage..ctor(String file)
   at ICSharpCode.ILSpy.AssemblyList.Open(String assemblyUri, Boolean isAutoLoaded)
   at ICSharpCode.ILSpy.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Details
* Product in use: e.g. ILSpy 
* Version in use: e.g. 6.1.0.5902

**Comment by siegfriedpammer** [comment]
I cannot reproduce this... it should not be possible to add a nupkg file directly to the assembly list. Can you provide more information on how you open the nupkg file? Thank you!

**Comment by yyjdelete** [comment]
Open any assembly from an .nupkg file, and close ilspy while the assembly is active(choose). Then it will be reopen when restart ilspy.

Seems callstack from this line https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/MainWindow.xaml.cs#L623

**Comment by siegfriedpammer** [comment]
Thank you very much!
