### ISSUE TITLE
ArgumentOutOfRangeException for some xmldoc

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2139]
### Steps to reproduce
1. Download Autofac 5.2.0 from https://www.nuget.org/api/v2/package/Autofac/5.2.0 and unzip it(.xml doc file is needed, and it will not be auto loaded from nuget file);
2. Open `lib/*/Autofac.dll` from the unpacked folder(any targetFramework is ok);
3. View class `Autofac.ContainerBuilder` and hover mouse cursor over the class name `ContainerBuilder`

### Error message shown

```
System.ArgumentOutOfRangeException: Index is out of range. Must be non-negative and smaller than the collection size.
param: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at ICSharpCode.AvalonEdit.Highlighting.RichTextModel.<GetHighlightedSections>d__19.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ICSharpCode.AvalonEdit.Highlighting.RichText..ctor(String text, RichTextModel model)
   at ICSharpCode.AvalonEdit.Highlighting.RichText.Concat(RichText[] texts)
   at ICSharpCode.ILSpy.TextView.DocumentationUIBuilder.AddCodeBlock(String textContent, Boolean keepLargeMargin)
   at ICSharpCode.ILSpy.TextView.DocumentationUIBuilder.<>c__DisplayClass77_0.<AddSection>b__0()
   at ICSharpCode.ILSpy.TextView.DocumentationUIBuilder.AddSection(Inline title, Action addChildren)
   at ICSharpCode.ILSpy.TextView.DocumentationUIBuilder.AddDocumentationElement(XmlDocumentationElement element)
   at ICSharpCode.ILSpy.TextView.DocumentationUIBuilder.AddDocumentationElement(XmlDocumentationElement element)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.CreateTooltipForEntity(IEntity resolved)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.GenerateTooltip(ReferenceSegment segment)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.TextViewMouseHover(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at ICSharpCode.AvalonEdit.Rendering.MouseHoverLogic.OnMouseHover(MouseEventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Details
* Product in use: ILSpy
* Version in use: 6.2.0.6062-preview1(and old versions)

**Comment by siegfriedpammer** [comment]
This happens when trying to render a `<code>` section with the following content:
```csharp
var builder = new ContainerBuilder();
            
             builder.RegisterType<Logger>()
                 .As<ILogger>()
                 .SingleInstance();
            
             builder.Register(c => new MessageHandler(c.Resolve<ILogger>()));
            
             var container = builder.Build();
             // resolve components from container...
```

However I have no idea, why it goes out of bounds... all bounds checks seem to be correct...

**Comment by yyjdelete** [comment]
Seems it should be 
```cs
// remove everything not before offset:
while (stateChangeOffsets.Count > 0 && stateChangeOffsets.Last() >= offset) {
```
 here.

https://github.com/icsharpcode/AvalonEdit/blob/396fabc0cd0fbac504634c06749863e80fa7ddea/ICSharpCode.AvalonEdit/Highlighting/RichTextModel.cs#L150-L167

**Comment by dgrunwald** [comment]
For the fix in ILSpy we'll need to update AvalonEdit.
