### ISSUE TITLE
PDB Generation is confused by enhanced using statements

### ISSUE THREAD

**Issue by cateyes99** [icsharpcode/ILSpy#2177]
### Steps to reproduce
1. Tried both **ILSpy** & **ilspycmd** to generate **PDB** for `Newtonsoft.Json.dll 12.0.3`, found both throwing `System.ArgumentOutOfRangeException` and resulted in producing a size 0 `Newtonsoft.Json.pdb`.

2. Tried the same for `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Linq.dll` & `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Linq.Expressions.dll` as well, got the same issue.

### Error message shown
- When using ILSpy, here is what it shows:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: value
   at System.Reflection.Throw.ValueArgumentOutOfRange()
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.EncodeSequencePoints(MetadataBuilder metadata, Int32 localSignatureRowId, List`1 sequencePoints)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.<>c__DisplayClass2_0.<WritePdb>g__ProcessMethod|7(MethodDefinitionHandle method, DocumentHandle document, List`1 sequencePoints, SyntaxTree syntaxTree)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.WritePdb(PEFile file, CSharpDecompiler decompiler, DecompilerSettings settings, Stream targetStream, Boolean noLogo)
   at ICSharpCode.ILSpy.GeneratePdbContextMenuEntry.<>c__DisplayClass3_0.<GeneratePdbForAssembly>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
![image](https://user-images.githubusercontent.com/19678455/94494712-4ac31100-024c-11eb-9f96-7b5d9c8c5ad4.png)

- When using command `ilspycmd Newtonsoft.Json.dll -genpdb`, I got:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
   at System.Reflection.Throw.ValueArgumentOutOfRange()
   at System.Reflection.Metadata.BlobWriterImpl.WriteCompressedInteger(BlobBuilder writer, UInt32 value)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.EncodeSequencePoints(MetadataBuilder metadata, Int32 localSignatureRowId, List`1 sequencePoints)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.<>c__DisplayClass2_0.<WritePdb>g__ProcessMethod|7(MethodDefinitionHandle method, DocumentHandle docuandle method, DocumentHandle document, List`1 sequencePoints, SyntaxTree syntaxTree)
   at ICSharpCode.Decompiler.DebugInfo.PortablePdbWriter.WritePdb(PEFile file, CSharpDecompiler decompiler, DecompilerSettings settings, Stream targetStream,gs settings, Stream targetStream, Boolean noLogo)
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.GeneratePdbForAssembly(String assemblyFileName, String pdbFileName, CommandLineApplication app) in D:\GimandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 216
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProde.Decompiler.Console\IlspyCmdProgram.cs:line 109
```

- At the end, both produces a size 0 `Newtonsoft.Json.pdb`.
![image](https://user-images.githubusercontent.com/19678455/94494987-04ba7d00-024d-11eb-8f4b-33c7ee5420cc.png)

### Details
* Product in use: _ILSpy / ICSharpCode.Decompiler nuget package_
* Version in use: _6.2.0.6124_
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by cateyes99** [comment]
Today I tried **JetBrains**' `dotPeek 64-bit 2020.2.3`, and it generated **PDB** successfully for `Newtonsoft.Json.dll 12.0.3`. As a result, I managed to debug from my _.NET Core C# Web API project_ into `Newtonsoft.Json.dll 12.0.3` by using the generated **PDB**!

**Comment by siegfriedpammer** [comment]
Triage: this is caused by the use of enhanced using statements. The omission of the block syntax needs to be special-cased in PDB generation as well.
