### ISSUE TITLE
System.BadImageFormatException: Read out of bounds.

### ISSUE THREAD

**Issue by poggersplayzyt** [icsharpcode/ILSpy#2198]
### Steps to reproduce
0. Do `mkdir out`
1. Do `ilspycmd -p -o out syn-launcher-v2.1.6b.bin`
2. Get this error.

### Error message shown

```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions)
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile mainModule, IAssemblyResolver assemblyResolver, DecompilerSettings settings)
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.GetDecompiler(String assemblyFileName) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 148
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.Decompile(String assemblyFileName, TextWriter output, String typeName) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 191
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 123
```

### Details
* Product in use: e.g. ICSharpCode.Decompiler nuget package
* Version in use: ICSharpCode.Decompiler: 6.2.0.6124

The binary/assembly is here:
http://cdn.synapse.to/synapsedistro/distro/syn-launcher-v2.1.6b.bin
File Info:
`syn-launcher-v2.1.6b.bin: PE32 executable (GUI) Intel 80386 Mono/.Net assembly, for MS Windows`

**Comment by siegfriedpammer** [comment]
This assembly is obfuscated and completely broken. ILSpy won't be able to open it.
