### ISSUE TITLE
Xaml write error

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2216]
### Input code
ILSpy version 7.0.0.6209-preview1

save as code

### Erroneous output
```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILSpy.BamlDecompiler.Xaml.XamlExtension.WriteObject(StringBuilder sb, XamlContext ctx, XElement ctxElement, Object value)
   at ILSpy.BamlDecompiler.Xaml.XamlExtension.ToString(XamlContext ctx, XElement ctxElement)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.RewriteElement(XamlContext ctx, XElement parent, XElement elem)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.ProcessElement(XamlContext ctx, XElement elem)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.ProcessElement(XamlContext ctx, XElement elem)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.ProcessElement(XamlContext ctx, XElement elem)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.ProcessElement(XamlContext ctx, XElement elem)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.ProcessElement(XamlContext ctx, XElement elem)
   at ILSpy.BamlDecompiler.Rewrite.MarkupExtensionRewritePass.Run(XamlContext ctx, XDocument document)
   at ILSpy.BamlDecompiler.XamlDecompiler.Decompile(IDecompilerTypeSystem typeSystem, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions, List`1 assemblyReferences)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceFileHandler.WriteResourceToFile(LoadedAssembly assembly, String fileName, Stream stream, DecompilationOptions options)
   at ICSharpCode.ILSpy.CSharpLanguage.ILSpyWholeProjectDecompiler.WriteResourceToFile(String fileName, String resourceName, Stream entryStream)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<WriteResourceFilesInProject>d__46.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass60_0.<SaveToDiskAsync>b__0()

```
https://www.sendspace.com/file/3lkc3b

**Comment by siegfriedpammer** [comment]
I just tried to reproduce this using the current master, however, I was unable to do so. Could you please try again on your side? It decompiles fine on my machine. Thanks!

**Comment by greenozon** [comment]
Thanks for re-testing
I've also tried on build ILSpy version 7.0.0.6286-preview2
issue gone
so closing
