### ISSUE TITLE
Exception to open dll.

### ISSUE THREAD

**Issue by darkragna** [icsharpcode/ILSpy#2239]
### Steps to reproduce
1. Just to drag to ILSpy.

### Error message shown

```
System.BadImageFormatException: Not enough space for Metadata stream.
   at System.Reflection.Metadata.MetadataReader.InitializeStreamReaders(MemoryBlock& metadataRoot, StreamHeader[] streamHeaders, MetadataStreamKind& metadataStreamKind, MemoryBlock& metadataTableStream, MemoryBlock& standalonePdbStream)
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
   at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

### Details

DLL: [Drive Google](https://drive.google.com/file/d/1dckZlEHF5IumJHWYftyhYIOtW_qMBd5M/view?usp=sharing)

**Comment by siegfriedpammer** [comment]
This exception is not unhandled. The assembly is obfuscated and/or completely broken and cannot be opened by ILSpy.
