### ISSUE TITLE
Suddenly I cannot open any ILSpy version as they all crash

### ISSUE THREAD

**Issue by hamarb123** [icsharpcode/ILSpy#2248]
### Steps to reproduce
1. Open ILSpy (gives 1 long error that stays and slightly changes whenever I try to do something)
2. Click on an assembly (this step is not always necessary to get the error, but I got the error message from here)

### Error message shown
They are basically all the same (only about 2 'words' change),  but here is one of them:
```
ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Error delay-loading highlighting definition ---> System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Xml.XmlConfiguration.XmlReaderSection.get_ProhibitDefaultUrlResolver()
   at System.Xml.Schema.Parser..ctor(SchemaType schemaType, XmlNameTable nameTable, SchemaNames schemaNames, ValidationEventHandler eventHandler)
   at System.Xml.Schema.XmlSchemaSet.ParseSchema(String targetNamespace, XmlReader reader)
   at System.Xml.Schema.XmlSchemaSet.Add(String targetNamespace, XmlReader schemaDocument)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadSchemaSet(XmlReader schemaInput)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.V2Loader.get_SchemaSet()
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.V2Loader.LoadDefinition(XmlReader reader, Boolean skipValidation)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader, Boolean skipValidation)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c.<.ctor>b__13_1()
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetDefinition()
   --- End of inner exception stack trace ---
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetDefinition()
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetNamedColor(String name)
   at ICSharpCode.ILSpy.CSharpHighlightingTokenWriter..ctor(TokenWriter decoratedWriter, ISmartTextOutput textOutput, ILocatable locatable)
   at ICSharpCode.ILSpy.CSharpLanguage.WriteCode(ITextOutput output, DecompilerSettings settings, SyntaxTree syntaxTree, IDecompilerTypeSystem typeSystem)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass48_0.<DecompileAsync>b__0()
```

### Details
* Product in use: ILSpy
* Versions it happens on (these are all of the versions I happen to have in my downloads folder): ILSpy version 7.0.0.6225-preview1 (log from this one), ILSpy version 6.2.1.6137, ILSpy version 6.0.0.5671-preview3, ILSpy version 5.0.2.5153, ILSpy version 4.0.1.4530, ILSpy version 3.0.1.3459
* Once I did something weird and accidentally got 50 error messages (haven't been able to replicate)

I think that I just have some corrupted files (app data), if you could help me work out where they may be I'll just delete them. It has never happened before, I think I've probably used the program in the last week on one of those versions and nothing was broken then.

**Comment by christophwille** [comment]
Use %appdata%\icsharpcode in Explorer. That opens the directory where ILSpy.xml lives. Simply rename it to get a brand-new one.

**Comment by hamarb123** [comment]
Thanks for your reply, I've now tried that, and it gave me a new list of assemblies, but it still has the same error no matter which version I tried opening it in :(
Is there anything else that I can try

**Comment by siegfriedpammer** [comment]
A bit of googling shows that this seems to be a problem when trying to execute an assembly from a network share or similar. If it is not loaded from a network share, did you "unblock" all executables after download?

**Comment by hamarb123** [comment]
> A bit of googling shows that this seems to be a problem when trying to execute an assembly from a network share or similar. If it is not loaded from a network share, did you "unblock" all executables after download?

They are on a network share, is there any way to 'unblock' the network share?
Thanks for your help!

**Comment by hamarb123** [comment]
I currently have 'net use A: "\\network\share\path\to\Hamish 4TB" /persistent:yes' run as system on reboot automatically because I was having problems with Visual Studio and these silly network share unblocking things.

**Comment by siegfriedpammer** [comment]
I don't know... so ILSpy works properly, if loaded from a local disk? The "unblock" feature I was talking about is described here: https://github.com/icsharpcode/ILSpy/issues/798#issuecomment-351256927

**Comment by hamarb123** [comment]
I think I have to have it copied locally :(, thanks for your help though!
