### ISSUE TITLE
C# decompiler doesn't support WinRT metadata

### ISSUE THREAD

**Issue by kennykerr** [icsharpcode/ILSpy#2306]
### Steps to reproduce
1. Open a WinRT winmd like C:\Windows\System32\WinMetadata\Windows.Foundation.winmd
2. Search for an interface like "IAsyncAction"

### Error message shown

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.ResolveModule(AssemblyReferenceHandle handle)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.GetDeclaringModule(TypeReferenceHandle handle)
   at ICSharpCode.Decompiler.TypeSystem.TypeProvider.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.ResolveType(EntityHandle typeRefDefSpec, GenericContext context, TypeSystemOptions customOptions, Nullable`1 typeAttributes, Nullability nullableContext)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.get_DirectBaseTypes()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.BaseTypeCollector.CollectBaseTypes(IType type)
   at ICSharpCode.Decompiler.TypeSystem.TypeSystemExtensions.GetAllBaseTypes(IType type)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesForTypeReference(IType type)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0()
```

![image](https://user-images.githubusercontent.com/9845234/108396501-c3ab1100-71cb-11eb-9917-eea396eb6991.png)

**Comment by steamos** [comment]
This appears to be due to line 316 in ICSharpCode.Decompiler\TypeSystem\MetadataModule.cs:

`		public IModule ResolveModule(AssemblyReferenceHandle handle)
		{
			if (handle.IsNil)
				return null;

			if (referencedAssemblies == null)
				return ResolveModuleUncached(handle);
			int row = MetadataTokens.GetRowNumber(handle);
			if (row == -1)
				row = GetRowNumberByMetadataReader(handle);
			Debug.Assert(row != 0);
			if (row >= referencedAssemblies.Length)
				HandleOutOfRange(handle);
			var module = LazyInit.VolatileRead(ref referencedAssemblies[row]);
			if (module != null)
				return module;
			module = ResolveModuleUncached(handle);
			return LazyInit.GetOrSet(ref referencedAssemblies[row], module);
		}
`

Remark from MSDN:
`One based row number, or -1 if handle can only be interpreted in a context of a specific MetadataReader. See GetRowNumber(MetadataReader, EntityHandle).`

**Comment by siegfriedpammer** [comment]
Yes, seems like we missed some places were we need to handle Windows Runtime projections explicitly... (see also the "Apply Windows Runtime projections on loaded assemblies" setting)

**Comment by steamos** [comment]
> Yes, seems like we missed some places were we need to handle Windows Runtime projections explicitly... (see also the "Apply Windows Runtime projections on loaded assemblies" setting)

I can add that to my PR if you'd like?

**Comment by siegfriedpammer** [comment]
> > Yes, seems like we missed some places were we need to handle Windows Runtime projections explicitly... (see also the "Apply Windows Runtime projections on loaded assemblies" setting)
> 
> I can add that to my PR if you'd like?

I think, in that particular case it is sufficient to use the other overload, as discussed in the PR.

**Comment by kennykerr** [comment]
Thanks all, much appreciated!
