### ISSUE TITLE
Unhandled FileNotFoundException when doing a string search when an assembly file is deleted

### ISSUE THREAD

**Issue by Jehoel** [icsharpcode/ILSpy#2340]
### Steps to reproduce
1. Open ILSpy **7.0.0.6372-preview3**, add an assembly .dll file to the Assemblies list.
2. Close ILSpy.
3. Delete or move that assembly .dll file in your filesystem.
4. Restart ILSpy. Observe the yellow warning triangle next to the assembly .dll in the assembly list.
5. Open the search pane and perform a search.
6. You'll get this modal error popup:

### Error message shown

```
---------------------------
Sorry, we crashed
---------------------------
System.IO.FileNotFoundException: Could not find file 'C:\git\others\IdentityServer4\samples\Quickstarts\3_AspNetCoreAndApis\src\MvcClient\bin\Debug\netcoreapp3.1\Microsoft.AspNetCore.Authentication.OpenIdConnect.dll'.

File name: 'C:\git\others\IdentityServer4\samples\Quickstarts\3_AspNetCoreAndApis\src\MvcClient\bin\Debug\netcoreapp3.1\Microsoft.AspNetCore.Authentication.OpenIdConnect.dll'

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at ICSharpCode.ILSpy.LoadedAssembly.<LoadAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ICSharpCode.ILSpy.AssemblyList.<GetAllAssemblies>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.ILSpy.SearchPane.<StartSearch>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

![image](https://user-images.githubusercontent.com/1693078/111562782-0244d480-8754-11eb-9bf5-21a6879f5b6f.png)

### Details
* Product in use: **ILSpy.exe**
* Version in use: **ILSpy version 7.0.0.6372-preview3**

**Comment by Jehoel** [comment]
I've made a patch for this in my PR:  https://github.com/icsharpcode/ILSpy/pull/2341
