### ISSUE TITLE
NullReferenceException in AwaitInCatchTransform.MatchAwaitCatchHandler()

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2366]
It's something new in 7.0rc1 and maybe related to 76227af89df5570fd23b68e748c4296595860f9b

### Input code
```cs
private async Task Test()
{
	while (true)
	{
		try
		{
			await Task.CompletedTask;
		}
		catch { }
	}
}
```

### Erroneous output
```c#
System.NullReferenceException
   at ICSharpCode.Decompiler.IL.ControlFlow.AwaitInCatchTransform.MatchAwaitCatchHandler(TryCatchHandler handler, Int32& id, ILVariable& identifierVariable, Block& realEntryPoint, ILInstruction& nextBlockOrExitContainer, ILInstruction& jumpTableEntry, ILVariable& objectVariable)
   at ICSharpCode.Decompiler.IL.ControlFlow.AwaitInCatchTransform.AnalyzeHandlers(InstructionCollection`1 handlers, ILVariable& catchHandlerIdentifier, List`1& transformableCatchBlocks)
   at ICSharpCode.Decompiler.IL.ControlFlow.AwaitInCatchTransform.Run(ILFunction function, ILTransformContext context)
   at ICSharpCode.Decompiler.IL.ControlFlow.AsyncAwaitDecompiler.Run(ILFunction function, ILTransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
```

### Details
* Product in use: ILSpy
* Version in use: 7.0.0.6473-rc1

**Comment by yyjdelete** [comment]
```cs
private async Task Test2()
{
	try
	{
		await Task.CompletedTask;
	}
	catch (NullReferenceException)
	{
		await Task.CompletedTask;
	}
	catch (InvalidOperationException)
	{
		await Task.CompletedTask;
	}
	catch (ArgumentException)
	{
		await Task.CompletedTask;
	}
}
```

```cs
System.NullReferenceException
   at ICSharpCode.Decompiler.IL.Branch.GetExecutesFinallyBlock(ILInstruction inst, BlockContainer container)
   at ICSharpCode.Decompiler.IL.Branch.get_TriggersFinallyBlock()
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.VisitBranch(Branch inst)
   at ICSharpCode.Decompiler.IL.Branch.AcceptVisitor(ILVisitor visitor)
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.Default(ILInstruction inst)
   at ICSharpCode.Decompiler.IL.ILVisitor.VisitSwitchSection(SwitchSection inst)
   at ICSharpCode.Decompiler.IL.SwitchSection.AcceptVisitor(ILVisitor visitor)
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.VisitSwitchInstruction(SwitchInstruction inst)
   at ICSharpCode.Decompiler.IL.SwitchInstruction.AcceptVisitor(ILVisitor visitor)
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.Default(ILInstruction inst)
   at ICSharpCode.Decompiler.IL.ILVisitor.VisitBlock(Block block)
   at ICSharpCode.Decompiler.IL.Block.AcceptVisitor(ILVisitor visitor)
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.VisitBlockContainer(BlockContainer container)
   at ICSharpCode.Decompiler.IL.BlockContainer.AcceptVisitor(ILVisitor visitor)
   at ICSharpCode.Decompiler.FlowAnalysis.DefiniteAssignmentVisitor.VisitILFunction(ILFunction inst)
   at ICSharpCode.Decompiler.IL.ILFunction.AcceptVisitor(ILVisitor visitor)
   at ICSharpCode.Decompiler.IL.Transforms.RemoveDeadVariableInit.ResetHasInitialValueFlag(ILFunction function, ILTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.RemoveDeadVariableInit.Run(ILFunction function, ILTransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext)
```
