### ISSUE TITLE
Process terminated. Assertion failed - in ``TransformDisplayClassUsage.VariableToDeclare``

### ISSUE THREAD

**Issue by marwie** [icsharpcode/ILSpy#2405]
### Steps to reproduce
1.  Download the dll [Unity2017.3.0b1.zip](https://github.com/icsharpcode/ILSpy/files/6454984/Unity2017.3.0b1.zip)
2.  Run the following command with the correct paths ``path\to\ilspycmd.exe path/to/UnityEditor.dll -o path/to/output/directory -p --languageversion Latest ``

### Error message shown
```csharp
Process terminated. Assertion failed.
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.VariableToDeclare..ctor(DisplayClass container, IField field, ILVariable declaredVariable) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 69
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.HandleMonoStateMachine(ILFunction function, ILVariable thisVariable) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 658
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.AnalyzeVariable(ILVariable v) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 249
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.<AnalyzeFunction>g__VisitFunction|7_0(ILFunction f) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 140
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.<AnalyzeFunction>g__Visit|7_2(ILInstruction inst) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 161
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.AnalyzeFunction(ILFunction function) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 170
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.ICSharpCode.Decompiler.IL.Transforms.IILTransform.Run(ILFunction function, ILTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 118
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1495
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IProperty property, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1743
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1249
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 559
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 879
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\ProjectDecompiler\WholeProjectDecompiler.cs:line 240
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.TaskReplicator.Replica.<>c.<Execute>b__7_0(Object s)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

error without csharp latest arg: ``path\to\ilspycmd.exe path/to/UnityEditor.dll -o path/to/output/directory -p ``

```csharp
 Process terminated. Assertion failed.
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.VariableToDeclare..ctor(DisplayClass container, IField field, ILVariable declaredVariable) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 69
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.HandleMonoStateMachine(ILFunction function, ILVariable thisVariable) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 658
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.AnalyzeVariable(ILVariable v) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 249
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.<AnalyzeFunction>g__VisitFunction|7_0(ILFunction f) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 140
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.<AnalyzeFunction>g__Visit|7_2(ILInstruction inst) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 161
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.AnalyzeFunction(ILFunction function) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 170
   at ICSharpCode.Decompiler.IL.Transforms.TransformDisplayClassUsage.ICSharpCode.Decompiler.IL.Transforms.IILTransform.Run(ILFunction function, ILTransformContext context) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\IL\Transforms\TransformDisplayClassUsage.cs:line 118
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1495
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IProperty property, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1743
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 1249
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 559
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileWholeModuleAsSingleFile(Boolean sortTypes) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 595
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileWholeModuleAsSingleFile() in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 569
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileWholeModuleAsString() in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 851
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.Decompile(String assemblyFileName, TextWriter output, String typeName) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 249
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 172
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<Apply>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass138_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.Main(String[] args) in C:\git\continuous-integration\modules\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 32
```

### Details
* Product in use: e.g. ILSpy fork, only modified console exe tho
* Version in use: d92dd153fc8768bb9c67645be422f1601b4c4906

**Comment by siegfriedpammer** [comment]
Cannot reproduce... could you try to find out which method triggers this assertion? I just tried decompiling the whole assembly, but recent master build do not fail. Can you verify on your side? Thanks!

**Comment by marwie** [comment]
Hello, opening the dll in latest ILSpy release works for me too.

![image](https://user-images.githubusercontent.com/5083203/119823755-77bbe680-bef5-11eb-9059-c88737463d50.png)
![image](https://user-images.githubusercontent.com/5083203/119823901-9c17c300-bef5-11eb-8727-013105ecc59e.png)
![image](https://user-images.githubusercontent.com/5083203/119823937-a5a12b00-bef5-11eb-8b00-804a6f18a23d.png)

**Comment by marwie** [comment]
Thanks for the fix ! It works
