### ISSUE TITLE
Error while decompiling : System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')

### ISSUE THREAD

**Issue by manuc66** [icsharpcode/ILSpy#2413]
### Steps to reproduce
Not systematic, it seems a multhreading bug, while trying to decompile DLLs

### Error message shown

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Error decompiling for 'Lorem\Ipsum\Sit.cs') (Error decompiling for 'Lorem\Ipsum\Amet.cs') (Error decompiling for 'Lorem\Ipsum\Dolor\Consectetur.cs') (Error decompiling for 'Lorem\Ipsum\PeriodicFilter.cs') (Error decompiling for 'Lorem\Ipsum\Dolor\LanguageManager.cs') (Error decompiling for 'Lorem\Ipsum\BettingCommonBo.cs')
 ---> Error decompiling for 'Lorem\Ipsum\Sit.cs'
in assembly "c:\some\path\Lorem.Ipsum.dll"
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
   at System.Collections.Generic.List`1.set_Capacity(Int32 value) in offset 9
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) in offset 54
   at System.Collections.Generic.List`1.AddWithResize(T item) in offset 7
   at System.Collections.Generic.List`1.Add(T item) in offset 52
   at ICSharpCode.Decompiler.CSharp.Syntax.TokenRole..ctor(String token) in offset 116
   at ICSharpCode.Decompiler.CSharp.Syntax.Roles..cctor() in offset 320
-- continuing with outer exception (System.TypeInitializationException) --
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 24
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 33
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.set_Name(String value) in offset 0
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 137
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 58
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 176
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, CancellationToken cancellationToken)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, CancellationToken cancellationToken)

	... truncated ...

 ---> (Inner Exception #1) Error decompiling for 'Lorem\Ipsum\Amet.cs'
in assembly "c:\some\path\Lorem.Ipsum.dll"
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
   at System.Collections.Generic.List`1.set_Capacity(Int32 value) in offset 9
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) in offset 54
   at System.Collections.Generic.List`1.AddWithResize(T item) in offset 7
   at System.Collections.Generic.List`1.Add(T item) in offset 52
   at ICSharpCode.Decompiler.CSharp.Syntax.TokenRole..ctor(String token) in offset 116
   at ICSharpCode.Decompiler.CSharp.Syntax.Roles..cctor() in offset 320
-- continuing with outer exception (System.TypeInitializationException) --
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 24
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 33
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.set_Name(String value) in offset 0
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 137
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 58
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 176
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35<---

 ---> (Inner Exception #2) Error decompiling for 'Lorem\Ipsum\Dolor\Consectetur.cs'
in assembly "c:\some\path\Lorem.Ipsum.dll"
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
   at System.Collections.Generic.List`1.set_Capacity(Int32 value) in offset 9
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) in offset 54
   at System.Collections.Generic.List`1.AddWithResize(T item) in offset 7
   at System.Collections.Generic.List`1.Add(T item) in offset 52
   at ICSharpCode.Decompiler.CSharp.Syntax.TokenRole..ctor(String token) in offset 116
   at ICSharpCode.Decompiler.CSharp.Syntax.Roles..cctor() in offset 320
-- continuing with outer exception (System.TypeInitializationException) --
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 24
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 33
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.set_Name(String value) in offset 0
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 137
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 58
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 176
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35<---

 ---> (Inner Exception #3) Error decompiling for 'Lorem\Ipsum\Scelerisque.cs'
in assembly "c:\some\path\Lorem.Ipsum.dll"
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
   at System.Collections.Generic.List`1.set_Capacity(Int32 value) in offset 9
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) in offset 54
   at System.Collections.Generic.List`1.AddWithResize(T item) in offset 7
   at System.Collections.Generic.List`1.Add(T item) in offset 52
   at ICSharpCode.Decompiler.CSharp.Syntax.TokenRole..ctor(String token) in offset 116
   at ICSharpCode.Decompiler.CSharp.Syntax.Roles..cctor() in offset 320
-- continuing with outer exception (System.TypeInitializationException) --
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 24
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 33
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.set_Name(String value) in offset 0
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 137
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 58
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 176
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35<---

 ---> (Inner Exception #4) Error decompiling for 'Lorem\Ipsum\Dolor\Maecenas.cs'
in assembly "c:\some\path\Lorem.Ipsum.dll"
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
   at System.Collections.Generic.List`1.set_Capacity(Int32 value) in offset 9
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) in offset 54
   at System.Collections.Generic.List`1.AddWithResize(T item) in offset 7
   at System.Collections.Generic.List`1.Add(T item) in offset 52
   at ICSharpCode.Decompiler.CSharp.Syntax.TokenRole..ctor(String token) in offset 116
   at ICSharpCode.Decompiler.CSharp.Syntax.Roles..cctor() in offset 320
-- continuing with outer exception (System.TypeInitializationException) --
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 24
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 33
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.set_Name(String value) in offset 0
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 137
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 58
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 176
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35<---

 ---> (Inner Exception #5) Error decompiling for 'Lorem\Ipsum\Adipiscing.cs'
in assembly "c:\some\path\Lorem.Ipsum.dll"
 ---> System.ArgumentOutOfRangeException: capacity was less than the current size. (Parameter 'value')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
   at System.Collections.Generic.List`1.set_Capacity(Int32 value) in offset 9
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) in offset 54
   at System.Collections.Generic.List`1.AddWithResize(T item) in offset 7
   at System.Collections.Generic.List`1.Add(T item) in offset 52
   at ICSharpCode.Decompiler.CSharp.Syntax.TokenRole..ctor(String token) in offset 116
   at ICSharpCode.Decompiler.CSharp.Syntax.Roles..cctor() in offset 320
-- continuing with outer exception (System.TypeInitializationException) --
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 24
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.ConstructType(String[] arr, Int32 i) in offset 33
   at ICSharpCode.Decompiler.CSharp.Syntax.NamespaceDeclaration.set_Name(String value) in offset 0
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in offset 137
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in offset 182
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 58
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in offset 176
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35<---
```

### Details
* Product in use: ICSharpCode.Decompiler nuget package
* Version in use: 7.0.0.6488

**Comment by manuc66** [comment]
Its seems the conjunction of:

- Parallel.ForEach: https://github.com/icsharpcode/ILSpy/blob/635013329a09cbf48079e4185bdda9261cf513dc/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs#L225
- add to static list at : https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/CSharp/Syntax/TokenRole.cs#L57

**Comment by manuc66** [comment]
Thanks @dgrunwald ! 

Have you an estimate when it will be released ?

**Comment by christophwille** [comment]
Grab an artifact from one of the GH Actions builds here https://github.com/icsharpcode/ILSpy/actions?query=workflow%3A%22Build+ILSpy%22+branch%3Amaster+is%3Asuccess+event%3Apush and the on the artifacts - this will take you to the current builds.

![image](https://user-images.githubusercontent.com/344208/118665195-663a5680-b7f2-11eb-8e64-2a7417679c89.png)

**Comment by manuc66** [comment]
Thanks, but I mean public official release on nuget feed

**Comment by christophwille** [comment]
No idea.

**Comment by manuc66** [comment]
The fix is working, thanks !
