### ISSUE TITLE
System.BadImageFormatException: Illegal tables in compressed metadata stream.

### ISSUE THREAD

**Issue by jeannekamikaze** [icsharpcode/ILSpy#2419]
### WARNING: Linked executable is malware.

Hello. I am trying to reverse a piece of malware and stumbled upon an assembly that fails to decompile with `ILSpy`. This [StackOverflow discussion](https://stackoverflow.com/questions/38707922/vs2015-illegal-tables-in-compressed-metadata-stream) suggests that an obfuscator could have messed up the metadata to stop decompilers. I also saw a similar discussion in #1231.

Is it possible for ILSpy to decompile as much of the assembly as possible before throwing the exception below? Or is the malware obfuscated beyond recognition? The assembly should execute just fine, though I have of course not tried that :) So I imagine some amount of decompilation could be possible?

If anyone can have a brief look, help would very much be appreciated. Thank you!

### Steps to reproduce
1. Download zipped executable here: https://www.sendspace.com/file/1i342l
2. Extract zip.
3. `ilspycmd -p selectorx.exe`

### Error message shown

On GNU/Linux (REMnux) with version `6.2.1`:
```
System.BadImageFormatException: Illegal tables in compressed metadata stream.
   at System.Reflection.Metadata.MetadataReader.ReadMetadataTableHeader(BlobReader& reader, HeapSizes& heapSizes, Int32[]& metadataTableRowCounts, TableMask& sortedTables)
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
   at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
   at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions) in /home/remnux/ILSpy/ICSharpCode.Decompiler/Metadata/PEFile.cs:line 69
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEStreamOptions streamOptions, MetadataReaderOptions metadataOptions) in /home/remnux/ILSpy/ICSharpCode.Decompiler/Metadata/PEFile.cs:line 54
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.DecompileAsProject(String assemblyFileName, String outputDirectory) in /home/remnux/ILSpy/ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs:line 179
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in /home/remnux/ILSpy/ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs:line 83
```

The error also exists in version `7.0.0.6488` on Windows:
```
// This file does not contain a managed assembly.

System.BadImageFormatException: Illegal tables in compressed metadata stream.
   at ICSharpCode.ILSpy.LoadedAssembly.<LoadAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
```

### Details
* Product in use: `ilspycmd` on Linux, `ILSpy.exe` on Windows
* Version in use: 6.2.1 on Linux, 7.0.0.6488 on Windows
* I can certainly contribute a fix if you can point me in the right direction :)

**Comment by dgrunwald** [comment]
There's not much that can be done if System.Reflection.Metadata refuses to load metadata from the assembly.
If the `MetadataReader` constructor fails, the decompiler can't even start to run.

You could try to use de4dot to de-obfuscate the assembly.
The other option would be to patch System.Reflection.Metadata to be more accepting of invalid values in the metadata header.

**Comment by jeannekamikaze** [comment]
Thank you very much for the tip and the fast reply. `de4dot` did indeed detect an "unknown" obfuscator and was able to clean up the file enough for `ILSpy` to be able to extract a reasonable reconstruction of the code.

I think it could also be helpful if `ILSpy` gave that same explanation you gave above on a metadata load failure. Maybe it is obvious to the usual audience that the decompiler can't even run upon a metadata load failure, but it certainly wasn't obvious to me :) I can look into adding this message separately if you think it would be helpful.

**Comment by dgrunwald** [comment]
Unfortunately if System.Reflection.Metadata throws `BadImageFormatException` there's no good way to distinguish obfuscated binaries from native binaries or completely bogus files.
So I don't see a good way to add we could add an improved error message.
