### ISSUE TITLE
DetectPinnedRegions: duplicatedBlockStartOffsets.Count == 0

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2457]
### Steps to reproduce
1. Save as project
https://www.sendspace.com/file/ek6smi

### Error message shown

```
Error decompiling @0600031E -------
in assembly "C:\IL_errs\err110.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 380
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message) in offset 9
   at System.Diagnostics.TraceInternal.Fail(String message) in offset 55
   at System.Diagnostics.Debug.Assert(Boolean condition) in offset 6
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.CreatePinnedRegion(Block block, StLoc stLoc) in DetectPinnedRegions.cs:line 638
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.DetectPinnedRegion(Block block) in DetectPinnedRegions.cs:line 494
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.ProcessPinnedRegion(PinnedRegion pinnedRegion) in DetectPinnedRegions.cs:line 705
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.CreatePinnedRegion(Block block, StLoc stLoc) in DetectPinnedRegions.cs:line 646
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.DetectPinnedRegion(Block block) in DetectPinnedRegions.cs:line 494
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.ProcessPinnedRegion(PinnedRegion pinnedRegion) in DetectPinnedRegions.cs:line 705
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.CreatePinnedRegion(Block block, StLoc stLoc) in DetectPinnedRegions.cs:line 646
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.DetectPinnedRegion(Block block) in DetectPinnedRegions.cs:line 494
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.ProcessPinnedRegion(PinnedRegion pinnedRegion) in DetectPinnedRegions.cs:line 705
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.CreatePinnedRegion(Block block, StLoc stLoc) in DetectPinnedRegions.cs:line 646
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.DetectPinnedRegion(Block block) in DetectPinnedRegions.cs:line 494
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.ProcessPinnedRegion(PinnedRegion pinnedRegion) in DetectPinnedRegions.cs:line 705
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.CreatePinnedRegion(Block block, StLoc stLoc) in DetectPinnedRegions.cs:line 646
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.DetectPinnedRegion(Block block) in DetectPinnedRegions.cs:line 494
   at ICSharpCode.Decompiler.IL.ControlFlow.DetectPinnedRegions.Run(ILFunction function, ILTransformContext context) in DetectPinnedRegions.cs:line 69
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1508
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1545
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1444
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1282
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 572
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 892
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in WholeProjectDecompiler.cs:line 238
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() in offset 713
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) in offset 6
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) in offset 134

```

### Details
* Product in use: 
ILSpy version 7.1.0.6580
.NET version 4.8.3928.0

**Comment by dgrunwald** [comment]
This is a different assertion, but seems to be the same underlying problem as in #2533
