### ISSUE TITLE
Decompiling error: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by DarkerSquirrel** [icsharpcode/ILSpy#2480]
[Assembly-CSharp.zip](https://github.com/icsharpcode/ILSpy/files/6981896/Assembly-CSharp.zip)

### Steps to reproduce
1. Try decompiling DSW,BattleConfig.ApplyCo()
2.  or try to export code of all Assembly-Csharp.dll

### Error message shown
```
Error decompiling @060008B1 DSW.BattleConfig.ApplyCo
in assembly "C:\_0day\Assembly-CSharp.dll"
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException() in offset 5
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key) in offset 30
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.MergeBranchStateIntoTargetBlock(Branch inst, State branchState) in DataFlowVisitor.cs:line 435
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.VisitBranch(Branch inst) in DataFlowVisitor.cs:line 426
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.Default(ILInstruction inst) in DataFlowVisitor.cs:line 292
   at ICSharpCode.Decompiler.FlowAnalysis.DataFlowVisitor`1.VisitBlockContainer(BlockContainer container) in DataFlowVisitor.cs:line 399
   at ICSharpCode.Decompiler.IL.Transforms.SplitVariables.Run(ILFunction function, ILTransformContext context) in SplitVariables.cs:line 39
   at ICSharpCode.Decompiler.IL.ILFunction.RunTransforms(IEnumerable`1 transforms, ILTransformContext context) in ILFunction.cs:line 394
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.Run(ILFunction function, ILTransformContext context) in YieldReturnDecompiler.cs:line 215
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1508
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1545
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1444
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 993
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options) in offset 247
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 124
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0() in offset 36
```

### Details
ILSpy version 7.1.0.6587
.NET version 4.8.4380.0

In my opinion , decompiling and exporting all .cs to a MSVC .csproj shouldn't stop in case decompilation of a certain method fails.

**Comment by dgrunwald** [comment]
The generated iterator class has very weird logic in a finally helper method:
```
	private void <>m__Finally1()
	{
		object[] array = new object[2];
		<>1__state = Native.dll.dllt(72.8f, 1789.4, <>7__wrap3, 1563.6, 4642.2f, 2691.2966252220249, 1475, 1562, 1563.6, 1475, 1280, 2630.2f, 2630.2f, 1475, 2630.2f, 150, 1433, 4642.2f, 4642.2f, <>7__wrap3, 3562.8f, 72.8f, 1251, 1475, 1433, 150, <>7__wrap3, 1433, 1280, 1433, 1789.4, 1433, 1789.4, 1475, 1475, <>7__wrap3, 2474, 99, 353, 1340, 97.4249f, 1648, 2364, 1719, 662, 244.53620731840331, 111.587982f, 3763, 3739, 487, 1860, 1961, 661, 86.2661f);
		((IDisposable)<>7__wrap1).Dispose();
	}
```
The `<>1__state` field determines control flow in MoveNext. Normally that field is only assigned compile-time constants; here it is set to value from native code.
How does that happen? The assembly doesn't look obfuscated otherwise.
It won't be possible to decompile the iterator if the state is manipulated in such ways, we best we can do is to detect this situation and abort the `yield return` decompilation.
