### ISSUE TITLE
ILSpyCmd does not recognize single-file executables  

### ISSUE THREAD

**Issue by Freakness109** [icsharpcode/ILSpy#2498]
### Steps to reproduce
1. Create a new hello-world example project (e.g. `dotnet new console -o repro`)
2. Create the single-file executable (e.g. `dotnet publish -p:PublishSingleFile=true -r linux-x64`)
3. Try to run ILSpyCmd on it (`ilspycmd bin/Debug/$version/$os/publish/repro`)

### Error message shown

```
ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler\Metadata\PEFile.cs:line 71
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEStreamOptions streamOptions, MetadataReaderOptions metadataOptions) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler\Metadata\PEFile.cs:line 58
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.GetDecompiler(String assemblyFileName) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 150
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.Decompile(String assemblyFileName, TextWriter output, String typeName) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 199
   at ICSharpCode.Decompiler.Console.ILSpyCmdProgram.OnExecute(CommandLineApplication app) in D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\IlspyCmdProgram.cs:line 126
```

### Details
* Product in use: ILSpyCmd (installed via dotnet tool) and AvaloniaILSpy fails to disassemble with a comparable backtrace
* Version in use: ILSpyCmd 7.1.0.6543 (also reproducible with commit `ed82bff896986e2b1fb41cccb67ddc7f11457821`), AvaloniaILSpy 7.0.1.1.rc
* Regular ILSpy on Windows handles the binary as expected
* The issue seems to be that both ILSpyCmd and AvaloniaILSpy expect a file to be a PE executable, while ILSpy tries various formats.
* I'd be willing to create a PR that moves the logic from ILSpy to somewhere common (e.g. ICSharpCode.Decompiler) and wires up the three consumers, given a bit of guidance.

**Comment by dgrunwald** [comment]
The core logic for opening bundles is already in ICSharpCode.Decompiler.
But only a single PE assembly can be decompiled to a project (.csproj). A bundle usually contains many assemblies and would need to be decompiled to a complete solution (.sln). So it's not so easy to hide the difference behind a common API.

**Comment by Freakness109** [comment]
That is true, hadn't thought of the difference. What would be a good path forward?
What I could think of is lifting a bit of logic from ILSpy to ILSpyCmd (along the lines of LoadedPackage/LoadedAssembly maybe?) to detect file type and in the case of a bundle dump each project into a separate folder using existing code.
Another approach would be to have a command-line switch to split the bundle into its assemblies, and then let the user run the command again, decompiling only the assembly they are interested in.
