### ISSUE TITLE
Assertion: Named arguments do not use correct type for `thisVarType`

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2582]
### Input code
Save code
assembly is not obfuscated

### Erroneous output
```c#
Error decompiling @060001A8 Unity.Injection.InjectionFactory.AddPolicies
in assembly "C:\Temp\err120.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 380
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message) in offset 9
   at System.Diagnostics.TraceInternal.Fail(String message) in offset 55
   at System.Diagnostics.Debug.Assert(Boolean condition) in offset 6
   at ICSharpCode.Decompiler.IL.StLoc.CheckInvariant(ILPhase phase) in StLoc.cs:line 44
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase) in Block.cs:line 108
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in StatementTransform.cs:line 138
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in Block.cs:line 318
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 118
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in BlockTransform.cs:line 90
   at ICSharpCode.Decompiler.IL.ILFunction.RunTransforms(IEnumerable`1 transforms, ILTransformContext context) in ILFunction.cs:line 405
   at ICSharpCode.Decompiler.IL.Transforms.DelegateConstruction.TransformDelegateConstruction(ILInstruction value, IMethod targetMethod, ILInstruction target, IType delegateType) in DelegateConstruction.cs:line 207
   at ICSharpCode.Decompiler.IL.Transforms.DelegateConstruction.ICSharpCode.Decompiler.IL.Transforms.IILTransform.Run(ILFunction function, ILTransformContext context) in DelegateConstruction.cs:line 56
   at ICSharpCode.Decompiler.IL.ILFunction.RunTransforms(IEnumerable`1 transforms, ILTransformContext context) in ILFunction.cs:line 405
   at ICSharpCode.Decompiler.IL.Transforms.LocalFunctionDecompiler.ReadLocalFunctionDefinition(ILFunction rootFunction, IMethod targetMethod, Int32 skipCount) in LocalFunctionDecompiler.cs:line 479
   at ICSharpCode.Decompiler.IL.Transforms.LocalFunctionDecompiler.<FindUseSites>g__HandleUseSite|12_0(IMethod targetMethod, ILInstruction inst, <>c__DisplayClass12_0&) in LocalFunctionDecompiler.cs:line 433
   at ICSharpCode.Decompiler.IL.Transforms.LocalFunctionDecompiler.FindUseSites(ILFunction function, ILTransformContext context, Dictionary`2 localFunctions) in LocalFunctionDecompiler.cs:line 410
   at ICSharpCode.Decompiler.IL.Transforms.LocalFunctionDecompiler.Run(ILFunction function, ILTransformContext context) in LocalFunctionDecompiler.cs:line 95
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1551
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1588
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1465
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1318
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 574
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 894
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass45_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file) in WholeProjectDecompiler.cs:line 239
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() in offset 713
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) in offset 6
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) in offset 134

```

### Details
ILSpy version 7.2.0.6792-preview4
.NET version 4.8.3928.0
[err120.zip](https://github.com/icsharpcode/ILSpy/files/7739070/err120.zip)

**Comment by siegfriedpammer** [comment]
Looks like the `NamedArgumentTransform` uses the wrong type for the `this` argument. It defaults to the declaring type of the invoked method, however in this case this causes conflicts with `T&`.

Adding

```csharp
IType thisVarType = call.Arguments[0].InferType(context.TypeSystem);
if (thisVarType.Kind == TypeKind.Unknown)
{
	thisVarType = call.Method.DeclaringType;
}
```

at https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/IL/Transforms/NamedArgumentTransform.cs#L101 would be my proposed fix. @dgrunwald what do you think? Am I missing something?

**Comment by dgrunwald** [comment]
`InferType` doesn't seem appropriate to me in that context.
