### ISSUE TITLE
System.BadImageFormatException: Read out of bounds

### ISSUE THREAD

**Issue by as564335sa** [icsharpcode/ILSpy#2590]
Hi,
      this exe decomlilation error,

```
System.BadImageFormatException: Read out of bounds.
   在 System.Reflection.Throw.OutOfBounds()
   在 System.Reflection.Metadata.BlobReader.ReadInt32()
   在 ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesFromMethodBody(MethodBodyBlock method, MetadataModule module) 位置 /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:行号 298
   在 ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) 位置 /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:行号 134
   在 ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) 位置 /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:行号 146
   在 ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) 位置 /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:行号 92
   在 ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) 位置 /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:行号 205
   在 ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) 位置 /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:行号 967
   在 ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options)
   在 ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   在 ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0()
```

what's wrong?
[test.zip](https://github.com/icsharpcode/ILSpy/files/7791806/test.zip)

**Comment by greenozon** [comment]
Try using latest ILSpy build

eg 7.2.0.6800  easily opens up your assembly:

But this assembly is heavily obfuscated...

![image](https://user-images.githubusercontent.com/765343/147731472-b18702e3-fc2b-4102-9c0b-330bff1ff875.png)


but it fails when clicking on some nodes, eg:

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ICSharpCode.Decompiler.Disassembler.ILParser.SkipOperand(BlobReader& blob, ILOpCode opCode) in /_/ICSharpCode.Decompiler/Disassembler/ILParser.cs:line 59
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.ReadCodeMappingInfo(PEFile module, CodeMappingInfo info, MethodDefinitionHandle parent, MethodDefinitionHandle part, Queue`1 connectedMethods, HashSet`1 processedNestedTypes) in /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:line 818
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.GetCodeMappingInfo(PEFile module, EntityHandle member) in /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:line 664
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:line 64
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in /_/ICSharpCode.Decompiler/CSharp/RequiredNamespaceCollector.cs:line 204
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:line 971
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in /_/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs:line 952
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0()

```

**Comment by as564335sa** [comment]
Yes, I opened it in v7.2.0.6791-preview3. It can be opened normally, but most methods report errors

**Comment by greenozon** [comment]
>but most methods report errors
thats expected, as you assembly is obfuscated and or protected

did you try to de-obfuscate it? (eg using de4dot tool)

**Comment by as564335sa** [comment]
Yes, I've tried, de4dot faild, and scanid can't find the way of confusion

**Comment by greenozon** [comment]
Yes, de4dot is great tool, but is outdated, unfortunately...
try this result, attached
ps = current issue number
[test-deobfuscated.zip](https://github.com/icsharpcode/ILSpy/files/7792086/test-deobfuscated.zip)

**Comment by as564335sa** [comment]
Great！ This is available! Can you tell me what tool you used?

**Comment by greenozon** [comment]
Sure thing
this tool is in posession of each & every planet habitant
its brain & hands
😉

**Comment by as564335sa** [comment]
Okey，thank you!

**Comment by Jack-tian666** [comment]
666
