### ISSUE TITLE
IndexOutOfRangeException in MetadataProperty.DecodeSignature with Trimmed Assembly

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2654]
### Steps to reproduce
[System.Data.Common.zip](https://github.com/icsharpcode/ILSpy/files/8288586/System.Data.Common.zip)
1. Try to decompile the above dll;(from an net6.0 program build with PublishTrimmed=true)
2. Open `System.Data.Common.DbConnectionStringBuilder` or expand the tree;

### Error message shown

```cs
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_Parameters()
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DetermineIsIndexer(String name)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty..ctor(MetadataModule module, PropertyDefinitionHandle handle)
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.GetDefinition(PropertyDefinitionHandle handle)
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.get_Properties()
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0()

```

### Details
* Product in use: ILSpy 
* Version in use: master(1ccc63b8290c9e5d982df3242dfe60791dc40302)

**Comment by dgrunwald** [comment]
The problem is a setter-only property that has a custom attribute on the implicit `value` parameter.
ILSpy tries to apply the custom attribute to the corresponding parameter in the property signature, but the property has one less parameter than the setter.
