### ISSUE TITLE
`ILSpy` cannot open assembly created with `ILASM`

### ISSUE THREAD

**Issue by kennykerr** [icsharpcode/ILSpy#2657]
Given a simple source file:

```
D:\> type min.il
.class interface public abstract windowsruntime Windows.Foundation.IStringable
{
    .method public hidebysig newslot abstract virtual instance string ToString()
    {
    }
}
```

Run the following command (this produces a valid WinRT winmd):

```
D:\> ilasm min.il /MDV="WindowsRuntime 1.2" /dll /output=min.winmd /quiet
```

ILSpy then fails to open the resulting assembly with the following error:

```
// This file does not contain a managed assembly.

System.BadImageFormatException: Missing mscorlib reference in AssemblyRef table.
   at ICSharpCode.ILSpy.LoadedAssembly.<LoadAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
```

It works if I manually add the `AssemblyRef` table but it would be great if this wasn't a hard requirement. Other parsers like `ILDASM` don't require the `AssemblyRef` table.

**Comment by siegfriedpammer** [comment]
The exception is actually thrown by `System.Reflection.Metadata`, which we are using to process .NET binaries. See the origin of the exception: https://github.com/dotnet/runtime/blob/58fa90be46a9e4ca96ee47ed44c114f5bcde8a39/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.WinMD.cs#L666 (Not sure if the line number is to blame... ;-))

If SRM fails to provide a working `MetadataReader`, ILSpy is pretty much out of luck. Same goes for obfuscated assemblies...

You might want to file an issue at the dotnet/runtime repo as we already do the only thing we can in this case: display a somewhat sensible error message. Thanks!

**Comment by siegfriedpammer** [comment]
Upon closer inspection: the exception is only thrown in some cases... I will have to take a look if there is a work around for this. Thanks for reporting!

Nonetheless, I would be interested in hearing what the folks maintaining SRM have to say about this... :-) So I would still ask you to open an issue with them. Thanks!

**Comment by kennykerr** [comment]
Here you go - thanks! https://github.com/dotnet/runtime/issues/66957

**Comment by kennykerr** [comment]
https://github.com/dotnet/runtime/issues/66957#issuecomment-1075414197
