### ISSUE TITLE
PE file does not contain any managed metadata.

### ISSUE THREAD

**Issue by AlAreqi320** [icsharpcode/ILSpy#2689]
ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
   at ICSharpCode.ILSpyX.LoadedAssembly.LoadAsync(Task`1 streamTask) in D:\a\ILSpy\ILSpy\ICSharpCode.ILSpyX\LoadedAssembly.cs:line 380
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in D:\a\ILSpy\ILSpy\ILSpy\TreeNodes\AssemblyTreeNode.cs:line 398

**Comment by siegfriedpammer** [comment]
Without the assembly in question it is impossible to investigate this. However, I think that this is not a bug, because not all assemblies are managed and ILSpy can only deal with managed assemblies.
So please provide the assembly, thanks!

**Comment by AlAreqi320** [comment]
Ok thank i will send you assembly file

**Comment by AlAreqi320** [comment]
whats you whatsapp number i will send you assembly file

**Comment by siegfriedpammer** [comment]
Yes, as expected. This executable is not a managed assembly. Therefore ILSpy is the wrong tool to work with. Sorry.
