### ISSUE TITLE
TranslateArrayInitializer crashes with out of order array init

### ISSUE THREAD

**Issue by TravisRo** [icsharpcode/ILSpy#2821]
This is back in the current 7.2.1.6856 release
See #2655

**Comment by siegfriedpammer** [comment]
Do you have an example that causes a crash and/or a stacktrace? I have added the code from the linked issue as unit test and it obviously doesn't cause a crash.

Thanks!

**Comment by TravisRo** [comment]
Hmm..  My guess is the unit test procedure is broke then because I'm quite certain it's the same issue.  Files are attached.

ILSpy version 7.2.1.6856
.NET version 4.8.9093.0

`Error decompiling @06000002 ILSpyIssue2821.ILSpyIssue2821Class.WriteTest
in assembly "C:\Users\Travis\source\repos\ILSpyIssue2821\bin\Release\ILSpyIssue2821.exe"
 ---> System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) in offset 16
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.TranslateArrayInitializer(Block block) in ExpressionBuilder.cs:line 3366
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitBlock(Block block, TranslationContext context) in ExpressionBuilder.cs:line 3103
   at ICSharpCode.Decompiler.IL.Block.AcceptVisitor[C,T](ILVisitor`2 visitor, C context) in Instructions.cs:line 876
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint) in ExpressionBuilder.cs:line 198
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitLeave(Leave inst) in StatementBuilder.cs:line 383
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 78
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitIfInstruction(IfInstruction inst) in StatementBuilder.cs:line 135
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 78
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop) in StatementBuilder.cs:line 1383
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockContainer container, Boolean isLoop) in StatementBuilder.cs:line 1328
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container) in StatementBuilder.cs:line 1215
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst) in StatementBuilder.cs:line 78
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst) in StatementBuilder.cs:line 83
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1580
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1604
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1478
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 995
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options) in offset 247
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 124
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0() in offset 36
`

[ILSpyIssue2821.zip](https://github.com/icsharpcode/ILSpy/files/9894729/ILSpyIssue2821.zip)

**Comment by TravisRo** [comment]
FYI, 7.1.0.6543 works fine

**Comment by siegfriedpammer** [comment]
Thanks for providing the sample! Testing the latest master, it works fine on my machine as well... Can you try the latest nightly build from here? https://github.com/icsharpcode/ILSpy/actions/runs/3340557201

**Comment by siegfriedpammer** [comment]
Looking closer, the problem is that this fix never went into 7.2, looking at https://github.com/icsharpcode/ILSpy/commit/6a3bb2bbf125f8ed3283bfb15eafeedeaa5e3fe0 we can see, that it is only contained in v8.0-preview1 and later.

@christophwille @dgrunwald Do you think this bug needs to be backported to 7.x?

**Comment by christophwille** [comment]
I am open to point releases, though: given that 8 is already quite stable... I'd only do it if a stable NuGet consumer really comes along and needs it in ics.d like "yesterday"

**Comment by TravisRo** [comment]
I'll just move on to 8.0.  I thought #2655 was reported back in 2020 but looking back, it was Mar. 20 of this year.
