### ISSUE TITLE
Assert at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() 

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2859]
### Input code
Save project / VS2019

[DynamicData.zip](https://github.com/icsharpcode/ILSpy/files/10169824/DynamicData.zip)

### Erroneous output
```c#
Failed to decompile the assembly 'C:\tmp\DynamicData.dll':
System.AggregateException: One or more errors occurred. (Error decompiling for 'DynamicData\ObservableCacheEx.cs') (Error decompiling for 'DynamicData\List\Linq\AddKeyEnumerator.cs') (Error decompiling for 'DynamicData\List\Linq\ItemChangeEnumerator.cs') (Error decompiling for 'DynamicData\Aggregation\AggregateEnumerator.cs') (Error decompiling for 'DynamicData\Cache\Internal\TransformWithForcedTransform.cs')
 ---> Error decompiling for 'DynamicData\ObservableCacheEx.cs'
in assembly "C:\tmp\DynamicData.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>g__ProcessFiles|3(List`1 files) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 255
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, IList`1 partialTypes, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 221
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 154
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.SolutionWriter.WriteProject(LoadedAssembly loadedAssembly, Language language, String targetDirectory, CancellationToken ct)
 ---> (Inner Exception #1) Error decompiling for 'DynamicData\List\Linq\AddKeyEnumerator.cs'
in assembly "C:\tmp\DynamicData.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205<---

 ---> (Inner Exception #2) Error decompiling for 'DynamicData\List\Linq\ItemChangeEnumerator.cs'
in assembly "C:\tmp\DynamicData.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205<---

 ---> (Inner Exception #3) Error decompiling for 'DynamicData\Aggregation\AggregateEnumerator.cs'
in assembly "C:\tmp\DynamicData.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205<---

 ---> (Inner Exception #4) Error decompiling for 'DynamicData\Cache\Internal\TransformWithForcedTransform.cs'
in assembly "C:\tmp\DynamicData.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205<---

-------------

```

### Details
* Product in use: ILSpy version 8.0.0.7250-preview3
.NET version 6.0.11-servicing.22523.4+943474ca16db7c65ba6cff4a89c3ebd219dde3e5

**Comment by greenozon** [comment]
Issue fixed in build
* ILSpy version 8.2.0.7521

so closing this ticket
thank you!
