### ISSUE TITLE
AssertionFailedException at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2975]
### Input code
Please provide the input that failed to decompile.
If providing IL code as input, please provide enough context to allow us to re-assemble the IL.
If uploading a complete assembly, please mention which method failed to decompile.

Try to export project

### Erroneous output
```c#
Error decompiling for 'Microsoft.Extensions.Diagnostics.HealthChecks\HealthCheckLogScope.cs'
in assembly "C:\Tmp\Microsoft.Extensions.Diagnostics.HealthChecks.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205

```

### Details
* Product in use: ILSpy
* Version in use: ILSpy version 8.0.0.7329-preview4
.NET version 6.0.3-servicing.22123.9+c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663

* Original location of the assembly:
* "c:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0\ref\net5.0\Microsoft.Extensions.Diagnostics.HealthChecks.dll" 

[Microsoft.Extensions.Diagnostics.HealthChecks.zip](https://github.com/icsharpcode/ILSpy/files/11331851/Microsoft.Extensions.Diagnostics.HealthChecks.zip)

**Comment by siegfriedpammer** [comment]
There is a mismatch in the metadata... the property definition itself does not define a NullableAttribute, only the getter:

```csharp
KeyValuePair<string, object> IEnumerator<KeyValuePair<string, object>>.Current
{
	[DebuggerHidden]
	[return: System.Runtime.CompilerServices.Nullable(new byte[] { 0, 1, 1 })]
	get
	{
		throw null;
	}
}
```

Expected by ILSpy:

```csharp
[System.Runtime.CompilerServices.Nullable(new byte[] { 0, 1, 1 })]
KeyValuePair<string, object> IEnumerator<KeyValuePair<string, object>>.Current
{
	[DebuggerHidden]
	[return: System.Runtime.CompilerServices.Nullable(new byte[] { 0, 1, 1 })]
	get
	{
		throw null;
	}
}
```

**Comment by greenozon** [comment]
Looks like this is common issue

another example


```
Error decompiling for 'System.Linq\AsyncEnumerable.cs'
in assembly "C:\Temp\1\System.Linq.Async.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 250
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205

```
[System.Linq.Async.zip](https://github.com/icsharpcode/ILSpy/files/11412068/System.Linq.Async.zip)

**Comment by greenozon** [comment]
One more

```
Error decompiling for 'Newtonsoft.Json.Linq\JObject.cs'
in assembly "C:\Temp\1\Newtonsoft.Json.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205

```
[Newtonsoft.Json.zip](https://github.com/icsharpcode/ILSpy/files/11412073/Newtonsoft.Json.zip)

**Comment by greenozon** [comment]
this issue is still reproducible on latest CI build

* ILSpy version 8.2.0.7504
* .NET version 6.0.21-servicing.23363.11+e40b3abf1b41621d4298642a5fd300ebf7cccf6d

**Comment by greenozon** [comment]
@siegfriedpammer   any chance to solve this old issue?...

**Comment by greenozon** [comment]
still present on debug build  ILSpy version 8.2.0.7520

**Comment by greenozon** [comment]
ALL above targets were fixed in the following build:
* ILSpy version 8.2.0.7521

so closing
thanks!
