### ISSUE TITLE
ICSharpCode.ILSpy.AssertionFailedException: Stack type mismatch in parameter 1 in call to op_Subtraction()

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2978]
### Input code
Please provide the input that failed to decompile.

Save project

### Erroneous output
```c#
Error decompiling @0600173C 
.....

 ---> ICSharpCode.ILSpy.AssertionFailedException: Stack type mismatch in parameter 1 in call to op_Subtraction()
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message) in offset 0
   at ICSharpCode.Decompiler.IL.CallInstruction.CheckInvariant(ILPhase phase) in CallInstruction.cs:line 134
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.StLoc.CheckInvariant(ILPhase phase) in StLoc.cs:line 41
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in StatementTransform.cs:line 138
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in Block.cs:line 332
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 118
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context) in BlockTransform.cs:line 113
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in BlockTransform.cs:line 90
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1733
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1770
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1619
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1486
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1367
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 650
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 949
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205



```
If the output fails to re-compile, provide the compiler error message.
If the output has the wrong behavior, explain how it differs from the expected behavior.

### Details
* Product in use: ILSpy 
* Version in use:  ILSpy version 8.0.0.7329-preview4
* .NET version 6.0.3-servicing.22123.9+c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663

https://www.sendspace.com/file/z8rmly

**Comment by siegfriedpammer** [comment]
I cannot reproduce the assertion using master.

**Comment by greenozon** [comment]
I've got latest CI build debug edition

ILSpy version 8.0.0.7345
.NET version 6.0.3-servicing.22123.9+c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663



and I see the repro as follows:

![image](https://github.com/icsharpcode/ILSpy/assets/765343/3c906ae2-89ba-4610-8253-c34085a00df0)

and this is the same stack trace as above...

@siegfriedpammer 
when you say master what specific build are you refering to?

**Comment by siegfriedpammer** [comment]
> when you say master what specific build are you refering to?

ILSpy version 8.0.0.7345
.NET version 6.0.16-servicing.23173.11+1e620a42e71ca8c7efb033fd525f04be5fa701fe

Have you tried reproducing the problem in an isolated assembly list + folder?
Or are you using any non-standard settings?

**Comment by greenozon** [comment]
Good point!
I did "Reset to defaults" from options menu
and I still see the same exception

![image](https://github.com/icsharpcode/ILSpy/assets/765343/db3e1bfb-800d-4eb2-a48c-5034ca5f41eb)

I need to try the newly released 8.0 version (release)

**Comment by greenozon** [comment]
question: why 8.0 release from Release page is having same build number as last CI build?
2) I do not see exception in release build, is it because asserts are enabled only in debug ci builds?

**Comment by christophwille** [comment]
> ```
> question: why 8.0 release from Release page is having same build number as last CI build?
> ```
> 
>     2. I do not see exception in release build, is it because asserts are enabled only in debug ci builds?

correct, only in Debug.

**Comment by siegfriedpammer** [comment]
OK... I can reproduce it now after disabling assembly resolving completely.

Could it be that you are seeing the assertion, because you don't have .NET 7 installed? The assembly in question targets .NET 7.

**Comment by greenozon** [comment]
YEAH... bingo :)
for some reason it was not present on my PC

after I've installed it
![image](https://github.com/icsharpcode/ILSpy/assets/765343/7e6035be-1aa7-42b8-8c1f-4f95868d816c)

it started to produce another trace!  see below
Note: I took the last CI build debug version (I guess this is same as release but debug mode ON)

Question: it is possible for ILSpy to show some warning/error box in such a cases...
it was not very obvous long time :)


```
in assembly "C:\IL_errs\err130.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.Implementation.AbstractType.ChangeNullability(Nullability nullability) in AbstractType.cs:line 67
   at ICSharpCode.Decompiler.TypeSystem.TypeParameterSubstitution.VisitNullabilityAnnotatedType(NullabilityAnnotatedType type) in TypeParameterSubstitution.cs:line 209
   at ICSharpCode.Decompiler.TypeSystem.Implementation.NullabilityAnnotatedType.AcceptVisitor(TypeVisitor visitor) in NullabilityAnnotatedType.cs:line 34
   at ICSharpCode.Decompiler.TypeSystem.Implementation.SpecializedMember.get_ReturnType() in SpecializedMember.cs:line 130
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesForMemberReference(IMember member) in RequiredNamespaceCollector.cs:line 399
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesFromMethodBody(MethodBodyBlock method, MetadataModule module) in RequiredNamespaceCollector.cs:line 347
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 134
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 99
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 946
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in offset 0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 0

```

**Comment by dgrunwald** [comment]
See  #2860 for the assertion in ChangeNullability.
I will keep this issue open for the original assertion. While ILSpy needs to load referenced assemblies for proper decompilation results, it should still work without crashing when references are missing.

**Comment by greenozon** [comment]
Successfully decompiled in the following version, so closing, thanks!

* ILSpy version 8.2.0.7521
