### ISSUE TITLE
"Check for updates" throws FormatException

### ISSUE THREAD

**Issue by cremor** [icsharpcode/ILSpy#2985]
### Steps to reproduce
1. Open Help - About
2. Click on the "Check for updates" button

### Error message shown

```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at ICSharpCode.ILSpy.AboutPage.GetLatestVersionAsync()
   at ICSharpCode.ILSpy.AboutPage.<>c__DisplayClass6_0.<<AddUpdateCheckButton>b__0>d.MoveNext()
```

### Details
* ILSpy version 8.0.0.7339-rc1
* The Help - Check for Updates menu item works fine. Just the button on the about page is broken.

**Comment by christophwille** [comment]
Thanks for reporting - http://ilspy.net/updates.xml had the "-rc1" in the latestVersion tag. My mistake. Should be numerical only.
