### ISSUE TITLE
System.InvalidOperationException: Stack empty.

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3051]
### Input code
Navigate to  System.ServiceModel.XamlIntegration.XPathMessageContextMarkupExtension
or
System.ServiceModel.XamlIntegration.XPathMessageContextTypeConverter

got this then (see below)

dnSpyEx does not have any issues
Code is clean, no prot/obfuscations/etc

### Erroneous output
```c#
Error decompiling @06002534 System.ServiceModel.XamlIntegration.XPathMessageContextMarkupExtension.get_Namespaces
in assembly "C:\tmp\System.ServiceModel.dll"
 ---> System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack() in offset 10
   at System.Collections.Generic.Stack`1.Pop() in offset 22
   at ICSharpCode.Decompiler.IL.BlockBuilder.CreateBlocks(BlockContainer mainContainer, IEnumerable`1 basicBlocks, CancellationToken cancellationToken) in BlockBuilder.cs:line 141
   at ICSharpCode.Decompiler.IL.ILReader.ReadIL(MethodDefinitionHandle method, MethodBodyBlock body, GenericContext genericContext, ILFunctionKind kind, CancellationToken cancellationToken) in ILReader.cs:line 675
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1698
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1756
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IProperty property, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 2041
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1472
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1369
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 1034
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in CSharpDecompiler.cs:line 1006
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options) in offset 93
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in offset 8
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 122
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass53_0.<DecompileAsync>b__0() in offset 20

```
If the output fails to re-compile, provide the compiler error message.
If the output has the wrong behavior, explain how it differs from the expected behavior.

### Details
* Product in use: ILSpy / ICSharpCode.Decompiler
* Version in use: ILSpy version 8.1.0.7479
* .NET version 6.0.3-servicing.22123.9+c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663

[System.ServiceModel.zip](https://github.com/icsharpcode/ILSpy/files/12269675/System.ServiceModel.zip)

**Comment by greenozon** [comment]
There are much more similar issues, just naviagate over this assembly types!

**Comment by dgrunwald** [comment]
Looks like a reference assembly with completely empty method bodies.
We can't easily add a [testcase](https://github.com/icsharpcode/ILSpy/blob/d1e9f8bd77d70a9f132adc1d8fae5f23b58053e6/ICSharpCode.Decompiler.Tests/TestCases/ILPretty/EmptyBodies.il#L12) for these because `ilasm` refuses to create such assemblies.
