### ISSUE TITLE
Assert at ICSharpCode.Decompiler.IL.ILReader.CheckOutgoingEdges() in ILReader.cs:line 385

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3070]
### Input code
save project

### Erroneous output
```c#
Error decompiling @0600341B LINQPad.ExecutionModel.Debugging.DebugProcess.StepCore
in assembly "C:\123\err79.exe"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.IL.ILReader.CheckOutgoingEdges() in ILReader.cs:line 385
   at ICSharpCode.Decompiler.IL.ILReader.ReadInstructions(CancellationToken cancellationToken) in ILReader.cs:line 480
   at ICSharpCode.Decompiler.IL.ILReader.ReadIL(MethodDefinitionHandle method, MethodBodyBlock body, GenericContext genericContext, ILFunctionKind kind, CancellationToken cancellationToken) in ILReader.cs:line 674
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.CreateILAst(MethodDefinitionHandle method, ILTransformContext context) in YieldReturnDecompiler.cs:line 500
   at ICSharpCode.Decompiler.IL.ControlFlow.AsyncAwaitDecompiler.AnalyzeMoveNext() in AsyncAwaitDecompiler.cs:line 708
   at ICSharpCode.Decompiler.IL.ControlFlow.AsyncAwaitDecompiler.Run(ILFunction function, ILTransformContext context) in AsyncAwaitDecompiler.cs:line 127
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1720
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1756
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1605
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1480
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1369
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 652
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 951
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205

```

### Details
* Version ILSpy version 8.1.0.7490
* .NET version 6.0.20-servicing.23320.17+a08d9ce2caf02455c0b825bcdc32974bdf769a80
* 
[err79.zip](https://github.com/icsharpcode/ILSpy/files/12473940/err79.zip)

**Comment by dgrunwald** [comment]
The problem here seems to be related to a missing reference assembly, ILSpy doesn't realize that `valuetype [LINQPad.Debugger]Microsoft.Debugging.MdbgEngine.StepperType` is an enum.
This results in an inconsistency of stack types on different control flow paths (concretely, the problem is discovered when falling through from IL_113f to IL_114f). This should have triggered a re-import of the following block to keep the types consistent; but somehow this didn't work.

**Comment by greenozon** [comment]
I've double checked feeding in all the assemblies from this SW
same error occuring

tested on

* ILSpy version 8.1.0.7501
* .NET version 6.0.21-servicing.23363.11+e40b3abf1b41621d4298642a5fd300ebf7cccf6d

**Comment by dgrunwald** [comment]
```
...
Import block at IL_113f with inputs O
Import block at IL_112f with inputs O
Import block at IL_114f with inputs Unknown, O
Import block at IL_113c with inputs O
Import block at IL_1139 with inputs O
Import block at IL_120f with inputs
Import block at IL_11ee with inputs
Import block at IL_113d with inputs I4, O
Import block at IL_114f with inputs O, I4
```
This is weird, IL_114f goes from [Unknown, O] to [O, I4]. That's invalid, each reimport is supposed to widen the types involved. Unknown->O is valid "widening", but O->I4 is invalid (narrowing).

`IL_113d: br.s IL_114f`
This simple block shouldn't change the stack state; but [I4, O] seems to swapped around to [O, I4].
So I think the missing reference is causing a reimport, and the reimport code path probably has a bug that swaps the stack order.
