### ISSUE TITLE
Load baml issue

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3086]
### Input code
Navigate to Resources
dialogs/versiondialog.baml
or
views/updatewindow.baml
and others

### Erroneous output
```c#
System.ArgumentException: '', hexadecimal value 0x03, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XContainer.WriteContentTo(XmlWriter writer)
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at System.Xml.Linq.XNode.ToString()
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadBaml(AvalonEditTextOutput output, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.<>c__DisplayClass1_2.<View>b__3()
```

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* ILSpy version 8.1.1.7464
* .NET version 6.0.21-servicing.23363.11+e40b3abf1b41621d4298642a5fd300ebf7cccf6d

https://www.sendspace.com/file/mwymnt

**Comment by greenozon** [comment]
closing old issue as I can't find input file...
