### ISSUE TITLE
Assert at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3094]
### Input code
save as project

### Erroneous output
```c#
Error decompiling for 'Newtonsoft.Json.Linq\JObject.cs'
in assembly "C:\IL_errs\err136.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 217
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 299
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in ApplyAttributeTypeVisitor.cs:line 142
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 returnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.DecodeSignature() in MetadataProperty.cs:line 169
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataProperty.get_ReturnType() in MetadataProperty.cs:line 118
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 140
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 89
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 79
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 206
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 947
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 298
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 719
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 205

```

### Details
* ILSpy version 8.2.0.7504
* .NET version 6.0.22-servicing.23424.25+4bb6dc195c0a3bc4c7e24ff54a8925b98db4fecd

[err136.zip](https://github.com/icsharpcode/ILSpy/files/12844942/err136.zip)

**Comment by dgrunwald** [comment]
```c#
// {1700029B Newtonsoft.Json.Linq.JObject+<GetEnumerator>d__63.System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<System.String,Newtonsoft.Json.Linq.JToken>>.Current}

KeyValuePair<string, JToken> IEnumerator<KeyValuePair<string, JToken>>.Current
{
	[DebuggerHidden]
	[return: Nullable(new byte[] { 0, 1, 2 })]
	get
	{
		return <>2__current;
	}
}
````

`{ 0, 1, 2 }` is correct:
 * 0 means Oblivious (correct for KeyValuePair itself, which cannot have nullability annotation due to being a struct)
 * 1 means NotNullable and applies to the `string`
 * 2 means Nullable and applies to the `JToken`

The assertion here triggers when a value type has a nullability other than 0.
Root cause is that ILSpy expects the return type attributes on the property, but they're only present on the setter. So the nullability is inherited from the context, which results in an invalid nullability for this property.

**Comment by dgrunwald** [comment]
A manually written explicit interface implementation has a notable attribute on both the property and the getter:
```
KeyValuePair<string, string?> IEnumerator<KeyValuePair<string, string?>>.Current => throw new NotImplementedException();
```
=>
```
[System.Runtime.CompilerServices.Nullable(new byte[] { 0, 1, 2 })]
KeyValuePair<string, string> IEnumerator<KeyValuePair<string, string>>.Current
{
	[return: System.Runtime.CompilerServices.Nullable(new byte[] { 0, 1, 2 })]
	get
	{
		throw new NotImplementedException();
	}
}
```

But the explicit interface implementation in an automatically generated enumerator for `yield return` seems to have the attribute only on the getter, not on the property. In combination with a `[NullableContext]` attribute on the parent class this results in the assertion failure.
