### ISSUE TITLE
Assert at IL.Transforms.TransformExpressionTrees

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3117]
### Input code
save project

### Erroneous output
```c#
Error decompiling @06000049 ----------.GetDistinctQueryResult
in assembly "C:\IL_errs\err142.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: StackTypes must match!
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage) in offset 0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.<>c__DisplayClass16_0.<ConvertInstruction>g__DoConvert|0() in TransformExpressionTrees.cs:line 281
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.<>c__DisplayClass29_0.<ConvertComparison>b__1() in TransformExpressionTrees.cs:line 791
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.<>c__DisplayClass16_0.<ConvertInstruction>g__DoConvert|0() in TransformExpressionTrees.cs:line 279
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.<>c__DisplayClass12_0.<ConvertLambda>g__BuildFunction|0() in TransformExpressionTrees.cs:line 184
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.TryConvertExpressionTree(ILInstruction instruction, ILInstruction statement) in TransformExpressionTrees.cs:line 136
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.TryConvertExpressionTree(ILInstruction instruction, ILInstruction statement) in TransformExpressionTrees.cs:line 147
   at ICSharpCode.Decompiler.IL.Transforms.TransformExpressionTrees.Run(Block block, Int32 pos, StatementTransformContext context) in TransformExpressionTrees.cs:line 118
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in StatementTransform.cs:line 140
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in Block.cs:line 333
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode entryNode, BlockTransformContext context) in BlockTransform.cs:line 136
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in BlockTransform.cs:line 100
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1737
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1773
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1622
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1497
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1364
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 1033
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in CSharpDecompiler.cs:line 1005
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options) in offset 93
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in offset 8
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 122
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass53_0.<DecompileAsync>b__0() in offset 20

```
If the output fails to re-compile, provide the compiler error message.
If the output has the wrong behavior, explain how it differs from the expected behavior.

### Details
* ILSpy version 8.2.0.7537
* .NET version 6.0.23-servicing.23480.2+e0f0de876a67755a2c6cd2dc730c13f5959bdea8

[err142.zip](https://github.com/icsharpcode/ILSpy/files/13326225/err142.zip)

**Comment by siegfriedpammer** [comment]
Cannot reproduce this with master. Can you try again?

**Comment by greenozon** [comment]
yeah, same result - can't reproduce, magic!!!
closing
thanks for try

ILSpy version 9.0.0.7814-preview2+c66733f353a24174dbc7c9283333b50f796cd426
.NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c
