### ISSUE TITLE
ILSpy throws exception HighlightingDefinitionInvalidException when loading Jab.Roslyn3.dll

### ISSUE THREAD

**Issue by cnayan** [icsharpcode/ILSpy#3127]
### Steps to reproduce
1. Download latest NuGet package of Jab [https://www.nuget.org/packages/Jab](https://www.nuget.org/packages/Jab)
2. Extract the content (use 7-Zip or something similar)
3. Open any of the assemblies in sub-path "analyzers\dotnet" in ILSpy (I use v8.2.0.7535). Assemblies:
  a. "Jab.dll"
  b. "Jab.Roslyn3.dll"

### Error message shown
ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Error delay-loading highlighting definition
 ---> ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Error at position (line 1, column 1):
Data at the root level is invalid. Line 1, position 1.
 ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader, Boolean skipValidation)
   --- End of inner exception stack trace ---
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader, Boolean skipValidation)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.Load(XmlReader reader, IHighlightingDefinitionReferenceResolver resolver)
   at ICSharpCode.ILSpy.TextView.ExtensionMethods.<>c__DisplayClass0_0.<RegisterHighlighting>b__0()
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetDefinition()
   --- End of inner exception stack trace ---
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetDefinition()
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetNamedColor(String name)
   at ICSharpCode.ILSpy.CSharpHighlightingTokenWriter..ctor(TokenWriter decoratedWriter, ISmartTextOutput textOutput, ILocatable locatable)
   at ICSharpCode.ILSpy.CSharpLanguage.WriteCode(ITextOutput output, DecompilerSettings settings, SyntaxTree syntaxTree, IDecompilerTypeSystem typeSystem)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass53_0.<DecompileAsync>b__0()

```
![image](https://github.com/icsharpcode/ILSpy/assets/2213067/d68d62a3-d212-43e8-bbfe-59c678ea2485)
```

### Details
* Product in use: ILSpy
* Version: 8.2.0.7535

**Comment by siegfriedpammer** [comment]
Looks like your Installation of ILSpy is broken. Which of the release downloads did you use? I cannot reproduce this with [ILSpy_binaries_8.2.0.7535-x64.zip](https://github.com/icsharpcode/ILSpy/releases/download/v8.2/ILSpy_binaries_8.2.0.7535-x64.zip).

**Comment by cnayan** [comment]
@siegfriedpammer I used the x64 installer. Version is same.

Link to installer: https://github.com/icsharpcode/ILSpy/releases/download/v8.2/ILSpy_Installer_8.2.0.7535-x64.msi

**Comment by cnayan** [comment]
Funny thing is, I installed ILSpy freshly and then opened the DLL. It showed the exception.
Today, I tried again, it worked just fine.

There indeed is a bug, but seems like we have a workaround, hence, not a severe bug.

**Comment by cnayan** [comment]
My OS details, jfi:

OS Name	Microsoft Windows 11 Home Single Language
Version	10.0.22631 Build 22631
