### ISSUE TITLE
Assert at System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3133]
### Input code
save project

### Erroneous output
```c#
Error decompiling @0600001E 
in assembly "C:\Tmp\err143.dll"
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ICSharpCode.Decompiler.Util.BitSet.Set(Int32 index) in BitSet.cs:line 196
   at ICSharpCode.Decompiler.Util.BitSet.set_Item(Int32 index, Boolean value) in BitSet.cs:line 69
   at ICSharpCode.Decompiler.IL.ILReader.PrepareBranchTargetsAndStacksForExceptionHandlers() in ILReader.cs:line 616
   at ICSharpCode.Decompiler.IL.ILReader.ReadInstructions(CancellationToken cancellationToken) in ILReader.cs:line 469
   at ICSharpCode.Decompiler.IL.ILReader.ReadIL(MethodDefinitionHandle method, MethodBodyBlock body, GenericContext genericContext, ILFunctionKind kind, CancellationToken cancellationToken) in ILReader.cs:line 696
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1715
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1773
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1622
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1497
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1364
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in CSharpDecompiler.cs:line 1033
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in CSharpDecompiler.cs:line 1005
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options) in offset 93
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in offset 8
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 122
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass53_0.<DecompileAsync>b__0() in offset 20

```

### Details
* ILSpy version 9.0.0.7548-preview1
* .NET version 8.0.0-rtm.23531.3+5535e31a712343a63f5d7d796cd874e563e5ac14

PS
decompiles OK in dnSpyEx

[err143.zip](https://github.com/icsharpcode/ILSpy/files/13531674/err143.zip)

**Comment by ElektroKill** [comment]
You did not provide an assembly to reproduce the error :P

**Comment by greenozon** [comment]
added sample above

**Comment by ElektroKill** [comment]
I'm pretty sure this is not an ILSpy issue. The method body for `InjaTrader.IB.Adapater.OnError` contains many exception handlers with garbage offsets that are out of the range of the body. When ILSpy tries to process these exception handlers, it will crash due to the offset being out of range. dnSpyEx decompiles it fine since it just skips over these invalid exception handlers. However, this is also not exactly correct behavior on the side of dnSpyEx as there are lone `leave` instructions that don't belong to any exception handler if the invalid exception handlers are ignored. This means that there probably were correct exception handlers in the body at one point but they got corrupted at some point.

**Comment by greenozon** [comment]
got it, if the bytecodes are not sane, nothing to be done, so closing
thanks for time spent and nice output!
