### ISSUE TITLE
Drag and drop a folder to ILSpy?

### ISSUE THREAD

**Issue by aybe** [icsharpcode/ILSpy#3171]
**Is your feature request related to a problem? Please describe.**

Tried to drop a folder in the application, hoping it would load all DLLs in it but got the following instead:

```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\paint.net' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at ICSharpCode.ILSpyX.LoadedAssembly.LoadAsync(Task`1 streamTask) in /_/ICSharpCode.ILSpyX/LoadedAssembly.cs:line 340
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass53_0.<DecompileAsync>b__0()
```

Basically, it mistook it as an assembly.

**Describe the solution you'd like**

Maybe the software could handle such scenario?

That is, to load every DLL in the folder that's been dropped.

**Additional context**

![image](https://github.com/icsharpcode/ILSpy/assets/1537591/7c9c5148-7cdd-4c10-8d7b-de93193f30b7)

**Comment by christophwille** [comment]
This most likely won't make it - because you could go inside that folder, select the assemblies in question, and drag and drop those onto ILSpy:
![image](https://github.com/user-attachments/assets/834d5487-c6e9-4cba-a677-496a35d634e2)
Supporting folders would mean all sorts of smarts - like ignoring anything not being an assemblies, and what is the expected behavior with subfolders of that folder? Include, or only grab assemblies from the dragged "parent" folder?
