### ISSUE TITLE
.NET 8 ReadyToRun not supported

### ISSUE THREAD

**Issue by KrisVandermotten** [icsharpcode/ILSpy#3229]
### Steps to reproduce
1. Open a .NET 8 assembly, such as System.Private.CoreLib
2. View ReadyToRun code

### Error message shown

```
System.BadImageFormatException: Warning: Invalid ReadyToRun section type
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunCoreHeader.ParseCoreHeader(Byte[] image, Int32& curOffset)
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunHeader..ctor(Byte[] image, Int32 rva, Int32 curOffset)
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.EnsureHeader()
   at ICSharpCode.ILSpy.ReadyToRun.ReadyToRunLanguage.DecompileMethod(IMethod method, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass51_0.<DecompileAsync>b__0()
```

### Details
* Product in use: ILSpy
* Version in use: 7.2.1.6856

See also #2784

**Comment by christophwille** [comment]
Does that also happen with the latest 9.0 preview series?
