### ISSUE TITLE
Failed to decompile file .NETCoreApp v8

### ISSUE THREAD

**Issue by danthespal** [icsharpcode/ILSpy#3255]
### Input code
```IL
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.MethodDebugInformation.GetSequencePoints()
   at ICSharpCode.ILSpyX.PdbProvider.PortableDebugInfoProvider.GetSequencePoints(MethodDefinitionHandle method) in /_/ICSharpCode.ILSpyX/PdbProvider/PortableDebugInfoProvider.cs:line 101
   at ICSharpCode.Decompiler.Disassembler.MethodBodyDisassembler.Disassemble(MetadataFile module, MethodDefinitionHandle handle) in /_/ICSharpCode.Decompiler/Disassembler/MethodBodyDisassembler.cs:line 129
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleMethodBlock(MetadataFile module, MethodDefinitionHandle handle, MetadataGenericContext genericContext) in /_/ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs:line 375
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleMethod(MetadataFile module, MethodDefinitionHandle handle) in /_/ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs:line 153
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(MetadataFile module, TypeDefinitionHandle type) in /_/ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs:line 1650
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(MetadataFile module, TypeDefinitionHandle type) in /_/ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs:line 1627
   at ICSharpCode.ILSpy.ILLanguage.DecompileType(ITypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass53_0.<DecompileAsync>b__0()
```

### Details
* Product in use: ILSpy 9.9.9.7706 pull 3243 debug preview 2

**Comment by siegfriedpammer** [comment]
It seems that there is a broken PDB file next to the assembly file you are trying to decompile.

Would it be possible for you to provide these files? Thanks!

**Comment by danthespal** [comment]
[GameHelper.zip](https://github.com/user-attachments/files/16568748/GameHelper.zip)
yes sure

**Comment by siegfriedpammer** [comment]
Sorry, I cannot reproduce the issue... starting from an empty assembly list, can you provide a detailed list of steps that you perform in ILSpy to get this error? Thanks!

**Comment by danthespal** [comment]
I open ILSpy, import the file, change from C# to IL, select the the Configurator under " { } - > Configurator" same on PrivateImplementationDetails

**Comment by siegfriedpammer** [comment]
The error is not reproducible on my machine, the PDB is not loaded. This is because the DLL you sent does not contain any entries in the Debug Directory, which ILSpy uses to detect whether to look for a PDB or not:

![image](https://github.com/user-attachments/assets/0ae66d5e-9d2f-43ae-8762-45f2dee184e1)

Can you please tell us, what ILSpy displays in the assembly tooltip? On my machine it reads:

![image](https://github.com/user-attachments/assets/b221cf53-d417-410f-83c8-548090494be8)

Thanks!

Something really strange is going on here...

**Comment by danthespal** [comment]
[GameHelper-Release-v6.0.13.zip](https://github.com/user-attachments/files/16628618/GameHelper-Release-v6.0.13.zip)
maybe  this will help

**Comment by siegfriedpammer** [comment]
So, in the end I manually loaded the PDB using the "Select PDB" feature and then I was able to reproduce the problem. Thanks for reporting this issue!
