### ISSUE TITLE
Sorry, we crashed: System.ArgumentException: Unsupported table index: FieldPtr

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3273]
### Steps to reproduce
1. Navigate to Metadata -> Tables
2. 
3. 

### Error message shown

![image](https://github.com/user-attachments/assets/699d871f-8687-4b93-a3a2-4f1caebf47ec)

text palyload of the error:

```
---------------------------
Sorry, we crashed
---------------------------
System.ArgumentException: Unsupported table index: FieldPtr

   at ICSharpCode.ILSpy.Metadata.MetadataTablesTreeNode.CreateTableTreeNode(TableIndex table, MetadataFile metadataFile)

   at ICSharpCode.ILSpy.Metadata.MetadataTablesTreeNode.LoadChildren()

   at ICSharpCode.ILSpyX.TreeView.SharpTreeNode.EnsureLazyChildren() in /_/ICSharpCode.ILSpyX/TreeView/SharpTreeNode.cs:line 339

   at ICSharpCode.ILSpyX.TreeView.SharpTreeNode.set_IsExpanded(Boolean value) in /_/ICSharpCode.ILSpyX/TreeView/SharpTreeNode.cs:line 276

   at ICSharpCode.ILSpy.Controls.TreeView.SharpTreeView.OnKeyDown(KeyEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)

   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)

   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)

   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

### Details
* ILSpy version 9.0.0.7729-preview2
* .NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c

**Comment by siegfriedpammer** [comment]
Could you please provide the binary for me to check? Thanks!

**Comment by greenozon** [comment]
d-n-d drop binary onto ILSpy
open up Metadata, using arrow keys browse secinos one by one
when you try to open up Tables - the above error will show up

but... only  once!

to reproduce it - need to close/open ILSpy and try again

https://www.sendspace.com/file/7gd4wj

**Comment by siegfriedpammer** [comment]
Sendspace is sending (haha) me (haha) into a captcha - error - captcha - retry (error 12 download has been updated) loop... not sure what's going on...

**Comment by siegfriedpammer** [comment]
Kept trying and it seems now it worked... persistence is key, it seems :D

**Comment by greenozon** [comment]
sorry about that, will use another one next time
