### ISSUE TITLE
Assert at ICSharpCode.Decompiler.IL.CallInstruction.CheckInvariant(ILPhase phase) 

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3296]
### Input code
save as project

### Erroneous output
```c#
Error decompiling @0600044C Microsoft.SharePoint.Client.TaxonomyExtensions.SetTaxonomyFieldValues
in assembly "C:\---.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: Stack type mismatch in 'this' argument in call to get_StaticName()
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.IL.CallInstruction.CheckInvariant(ILPhase phase) in CallInstruction.cs:line 129
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.Leave.CheckInvariant(ILPhase phase) in Leave.cs:line 112
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase) in Block.cs:line 108
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase) in BlockContainer.cs:line 196
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.ILFunction.CheckInvariant(ILPhase phase) in ILFunction.cs:line 260
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in ILInstruction.cs:line 95
   at ICSharpCode.Decompiler.IL.StObj.CheckInvariant(ILPhase phase) in Instructions.cs:line 4221
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context) in StatementTransform.cs:line 142
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context) in Block.cs:line 333
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode entryNode, BlockTransformContext context) in BlockTransform.cs:line 136
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context) in BlockTransform.cs:line 100
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1759
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1795
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1644
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass75_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1519
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1382
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 656
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 955
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 289
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35

```

### Details
* ILSpy version 9.0.0.7785-preview2+c1a42ccf7205f41d9ba3988926162feb6e57ca98
.NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c

[OfficeDevPnP.Core.zip](https://github.com/user-attachments/files/17176213/OfficeDevPnP.Core.zip)

**Comment by siegfriedpammer** [comment]
Cannot reproduce this:

1) Load fresh assembly list from template ".NET 4 (WPF)"
2) Reset decompilation settings to defaults
3) Add assembly to assembly list via drag&drop
4) Search for given member name
5) Navigate to member
6) No assertion :(

**Comment by greenozon** [comment]
maybe there is a correlation with dependent dlls, I need to check and get back soon

**Comment by greenozon** [comment]
Well, the things got more complicated!
if the dll is standalone - no issue reproduced!
but if it's inside the orig dir with lots of other (dependent) dlls - it is reproduced
any clues why is that?

![image](https://github.com/user-attachments/assets/59e19aac-7d7a-4eb1-9fc3-250156089644)

**Comment by greenozon** [comment]
added set of other dlls, please try to repro with those in the same dir

[2.zip](https://github.com/user-attachments/files/17202630/2.zip)

**Comment by greenozon** [comment]
any luck to repro on your your side?...

**Comment by siegfriedpammer** [comment]
> any luck to repro on your your side?...

Yes, will take a look. Thanks!
