### ISSUE TITLE
ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Error delay-loading highlighting definition

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3301]
### Steps to reproduce
1. drag-n-drop assemlby to the ILSpy
2. error printed on the right hand panel
3. 

### Error message shown

```
ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Error delay-loading highlighting definition
 ---> ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Root element is missing.
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader, Boolean skipValidation)
   --- End of inner exception stack trace ---
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader, Boolean skipValidation)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.LoadXshd(XmlReader reader)
   at ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.Load(XmlReader reader, IHighlightingDefinitionReferenceResolver resolver)
   at ICSharpCode.ILSpy.TextView.ExtensionMethods.<>c__DisplayClass0_0.<RegisterHighlighting>b__0()
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetDefinition()
   --- End of inner exception stack trace ---
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetDefinition()
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingManager.DelayLoadedHighlightingDefinition.GetNamedColor(String name)
   at ICSharpCode.ILSpy.CSharpHighlightingTokenWriter..ctor(TokenWriter decoratedWriter, ISmartTextOutput textOutput, ILocatable locatable)
   at ICSharpCode.ILSpy.CSharpLanguage.WriteCode(ITextOutput output, DecompilerSettings settings, SyntaxTree syntaxTree, IDecompilerTypeSystem typeSystem)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass54_0.<DecompileAsync>b__0()

```

### Details
* ILSpy version 9.0.0.7812-preview2+c6e37529771dc55d29d26c8a9026bbf0f911ff03
.NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c

[0Harmony.zip](https://github.com/user-attachments/files/17295359/0Harmony.zip)

**Comment by greenozon** [comment]
yeah, the SHA256 is equal to yours...
I'm not able to reproduce the issue today, sorry
I"ll try to gather pre-condiitinos and then get back
freel free to close this ticket in week-two if I did not find the repro

**Comment by greenozon** [comment]
I reproduced the issue, but... it behaves randomly, not in 100% cases...
it appearsly more if the dll being drag-n-dropped is the 1st one in the tree
it almost does not appear if I drop it to non-empty tree

**Comment by greenozon** [comment]
OK, the issue got reproduced, I've ran dnSpy and tried to debug ILSpy
here is the weird exception, @siegfriedpammer   do you have some clues  why it is so crazy?

![image](https://github.com/user-attachments/assets/5139496b-e42a-40ea-b0b1-8cdcfe3e8978)


![image](https://github.com/user-attachments/assets/b368bb16-f549-42e1-acd2-424744de2c9d)

is it possible to deduce what is going on from above cases?

**Comment by greenozon** [comment]
why is lazyLoadingFunction == null?

![image](https://github.com/user-attachments/assets/a3cdc616-95a1-4850-9ee7-2a860474f3c3)

might it be the reason for never ending exception I"m hitting on any click in right tree menu?

**Comment by greenozon** [comment]
There is a single location in the ILSpy code that sets this field, but I never hit this breakpoint:

![image](https://github.com/user-attachments/assets/b83b60d2-d140-4a51-ae6e-a814e28bba00)

**Comment by siegfriedpammer** [comment]
![image](https://github.com/user-attachments/assets/c72a310e-cd8d-4495-9c58-720fb91cafc8)

It is called from https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/TextView/DecompilerTextView.cs#L99

**Comment by greenozon** [comment]
amazing job!
so tricky issue!

thanks!
