### ISSUE TITLE
Assert    at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType()

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3313]
### Input code
save as proj

### Erroneous output
```c#
Error decompiling for 'Iced.Intel.DecoderInternal\OpCodeHandlersTables_EVEX.cs'
in assembly "C:\Temp\SensorProfiler.Module.dll"
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 379
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage) in offset 48
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in offset 0
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ExpectDummyNullabilityForGenericValueType() in ApplyAttributeTypeVisitor.cs:line 240
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in ApplyAttributeTypeVisitor.cs:line 322
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in ParameterizedType.cs:line 330
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly, Nullable`1 additionalAttributes) in ApplyAttributeTypeVisitor.cs:line 158
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature(MetadataModule module, IParameterizedMember owner, MethodSignature`1 signature, Nullable`1 parameterHandles, Nullability nullableContext, TypeSystemOptions typeSystemOptions, Nullable`1 additionalReturnTypeAttributes) in MetadataMethod.cs:line 273
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.DecodeSignature() in MetadataMethod.cs:line 194
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataMethod.get_ReturnType() in MetadataMethod.cs:line 162
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesForMemberReference(IMember member) in RequiredNamespaceCollector.cs:line 398
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesFromMethodBody(MethodBodyBlock method, MetadataModule module) in RequiredNamespaceCollector.cs:line 346
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 133
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in RequiredNamespaceCollector.cs:line 99
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 56
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in RequiredNamespaceCollector.cs:line 205
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 952
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 289
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 313
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35

```

![image](https://github.com/user-attachments/assets/6aeccf3f-e369-4f23-a08e-1a5c1934dd6b)

### Details
* ILSpy version 9.0.0.7827-preview3+e96605ca8721c096b9540d0d155f50657c4e54fc
.NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c

[err.zip](https://github.com/user-attachments/files/17533524/err.zip)

**Comment by greenozon** [comment]
@ ping...

**Comment by siegfriedpammer** [comment]
Not sure if @dgrunwald can provide more info, but to me this looks like there is a `NullableContext(0)` attribute missing on the `GetSerializedTables` method... the whole type is marked `NullableContext(1)` (which is "not nullable"), but members that do not involve any nullable types are then marked `NullableContext(0)`, i.e., "null oblivious"...

**Comment by greenozon** [comment]
test on
* ILSpy version 9.1.0.7998+7fc90255009bc568923a2840f240ed6a6ff4a20e
* .NET version 8.0.15+50c4cb9fc31c47f03eac865d7bc518af173b74b7
