### ISSUE TITLE
Ungraceful failure on bad XML

### ISSUE THREAD

**Issue by johanfange** [icsharpcode/ILSpy#353]
I have a bad XML documentation file, and this trips ILSpy up:

```
System.Xml.XmlException: There is no Unicode byte order mark. Cannot switch to Unicode.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.CheckEncoding(String newEncodingName)
   at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at ICSharpCode.NRefactory.Documentation.XmlDocumentationProvider..ctor(String fileName)
   at ICSharpCode.ILSpy.XmlDoc.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
   at ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   at ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   at ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   at ICSharpCode.ILSpy.CSharpLanguage.RunTransformsAndGenerateCode(AstBuilder astBuilder, ITextOutput output, DecompilationOptions options, IAstTransform additionalTransform)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass17.<DecompileAsync>b__16()
```

If I remove the XML file it works just fine. The file looks like this:

```
<?xml version="1.0" encoding="utf-16"?>
<doc>
  <assembly>
[...]
```

It claims to be UTF-16 encoded, but it's actually just plain ASCII (so utf-8 would work, i.e. just removing the encoding attribute).

It ought to at least gracefully ignore the file if it can't parse it.

Preferably it'd also recognize that the file starts with the bytes 3C 3F 78 6D 6C = "<?xml", meaning it can't be utf-16 and thus discarding the utf-16 encoding attribute, and just assume it's utf-8, like when no encoding is specified.

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
