### ISSUE TITLE
ICSharpCode.Decompiler.DecompilerException: Error decompiling blah blah blah ---> System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by jazzdelightsme** [icsharpcode/ILSpy#362]
ILSpy version 2.1.0.1603, decompiling a C# method that makes heavy use of C# awaits.

Here is the full error:

```
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Threading.Tasks.Task Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand::_ProcessCluster(System.String)
 ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.ByReferenceType..ctor(TypeReference type)
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.DoInferTypeForExpression(ILExpression expr, TypeReference expectedType, Boolean forceInferChildren)
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.InferTypeForExpression(ILExpression expr, TypeReference expectedType, Boolean forceInferChildren)
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.DoInferTypeForExpression(ILExpression expr, TypeReference expectedType, Boolean forceInferChildren)
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.InferTypeForExpression(ILExpression expr, TypeReference expectedType, Boolean forceInferChildren)
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.RunInference(ILExpression expr)
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.RunInference()
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethod(MethodDefinition method)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass17.<DecompileAsync>b__16()
```

Here is the IL of the method, although I suspect the C# decompiler is following a whole bunch of "await"s so the problem might not be here:

``` MSIL
.method private hidebysig 
    instance class [mscorlib]System.Threading.Tasks.Task _ProcessCluster (
        string clusterName
    ) cil managed 
{
    .custom instance void [mscorlib]System.Runtime.CompilerServices.AsyncStateMachineAttribute::.ctor(class [mscorlib]System.Type) = (
        01 00 52 4d 69 63 72 6f 73 6f 66 74 2e 43 6c 75
        73 74 65 72 41 77 61 72 65 55 70 64 61 74 69 6e
        67 2e 43 6f 6d 6d 61 6e 64 73 2e 49 6e 76 6f 6b
        65 43 61 75 52 75 6e 43 6f 6d 6d 61 6e 64 2b 3c
        5f 50 72 6f 63 65 73 73 43 6c 75 73 74 65 72 3e
        64 5f 5f 37 36 00 00
    )
    .custom instance void [mscorlib]System.Diagnostics.DebuggerStepThroughAttribute::.ctor() = (
        01 00 00 00
    )
    // Method begins at RVA 0x3c8dc
    // Code size 66 (0x42)
    .maxstack 2
    .locals init (
        [0] valuetype Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76',
        [1] valuetype [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder
    )

    IL_0000: ldloca.s 0
    IL_0002: ldarg.0
    IL_0003: stfld class Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'::'<>4__this'
    IL_0008: ldloca.s 0
    IL_000a: ldarg.1
    IL_000b: stfld string Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'::clusterName
    IL_0010: ldloca.s 0
    IL_0012: call valuetype [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder::Create()
    IL_0017: stfld valuetype [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'::'<>t__builder'
    IL_001c: ldloca.s 0
    IL_001e: ldc.i4.m1
    IL_001f: stfld int32 Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'::'<>1__state'
    IL_0024: ldloca.s 0
    IL_0026: ldfld valuetype [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'::'<>t__builder'
    IL_002b: stloc.1
    IL_002c: ldloca.s 1
    IL_002e: ldloca.s 0
    IL_0030: call instance void [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder::Start<valuetype Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'>(!!0&)
    IL_0035: ldloca.s 0
    IL_0037: ldflda valuetype [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder Microsoft.ClusterAwareUpdating.Commands.InvokeCauRunCommand/'<_ProcessCluster>d__76'::'<>t__builder'
    IL_003c: call instance class [mscorlib]System.Threading.Tasks.Task [mscorlib]System.Runtime.CompilerServices.AsyncTaskMethodBuilder::get_Task()
    IL_0041: ret
} // end of method InvokeCauRunCommand::_ProcessCluster
```

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
