### ISSUE TITLE
Selecting body on the Disassembly and right clicking causes ArgumentNullException.

### ISSUE THREAD

**Issue by ashwinsathyar** [icsharpcode/ILSpy#363]
Repro Steps :
1) Load an assembly in ILSpy
2) View a interface, class, method anything
3) Select the decompiled output
4) Right Click

Expectation :
1) No effect
2) Show a menu having Copy, Select All etc

Result:
There is a crash with the following callstack, however this exception is caught and only error box is thrown

Below is the callstack

---
## Sorry, we crashed

System.ArgumentNullException: Value cannot be null.

Parameter name: source

   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)

   at AssemblyVisualizer.HAL.ILSpy.BrowseDependenciesContextMenuEntry.IsVisible(TextViewContext context)

   at ICSharpCode.ILSpy.ContextMenuProvider.ShowContextMenu(TextViewContext context, ContextMenu& menu)

   at ICSharpCode.ILSpy.ContextMenuProvider.textView_ContextMenuOpening(Object sender, ContextMenuEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Controls.PopupControlService.RaiseContextMenuOpeningEvent(IInputElement source, Double x, Double y, Boolean userInitiated)

   at System.Windows.Controls.PopupControlService.ProcessMouseUp(Object sender, MouseButtonEventArgs e)

   at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)

   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

**Comment by siegfriedpammer** [comment]
at AssemblyVisualizer.HAL.ILSpy.BrowseDependenciesContextMenuEntry.IsVisible(TextViewContext context)

You are using a plugin for ILSpy, please report this to the author of the plugin. If it still happens after all these years... ;-)
