### ISSUE TITLE
Expanding Used By of System.Threading.Tasks.Task.Delay - NullReferenceException

### ISSUE THREAD

**Issue by 3-1415926** [icsharpcode/ILSpy#364]
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.Helpers.FindMethodUsageInType(TypeDefinition type, MethodDefinition analyzedMethod)
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.Helpers.GetOriginalCodeLocation(MemberReference member)
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.AnalyzedMethodUsedByTreeNode.<FindReferencesInType>d__9.MoveNext()
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.ScopedWhereUsedAnalyzer`1.<FindReferencesInAssembly>d__8.MoveNext()
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.AnalyzedMethodUsedByTreeNode.<FetchChildren>d__2.MoveNext()
   at ICSharpCode.ILSpy.TreeNodes.ThreadingSupport.<>c__DisplayClass4.<LoadChildren>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.Helpers.FindMethodUsageInType(TypeDefinition type, MethodDefinition analyzedMethod)
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.Helpers.GetOriginalCodeLocation(MemberReference member)
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.AnalyzedMethodUsedByTreeNode.<FindReferencesInType>d__9.MoveNext()
   at ICSharpCode.ILSpy.TreeNodes.Analyzer.ScopedWhereUsedAnalyzer`1.<FindReferencesInAssembly>d__8.MoveNext()
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by siegfriedpammer** [comment]
Cannot reproduce.
