### ISSUE TITLE
AddXmlDocTransform should not crash, if xml file is missing (was: System.Xml.XmlException when decompiling .NetCF assemblies)

### ISSUE THREAD

**Issue by mohas** [icsharpcode/ILSpy#374]
When I tried to decompile the .net cf 3.5 assembly: System.Windows.Forms, OpenFileDialog class I faced the following exception:

```
System.Xml.XmlException: XmlDoc C:\Program Files\Microsoft.NET\SDK\CompactFramework\v3.5\WindowsCE\System.Windows.Forms.xml is redirecting to %CORSYSDIR%System.Windows.Forms.xml, but that file was not found.
   at ICSharpCode.NRefactory.Documentation.XmlDocumentationProvider..ctor(String fileName)
   at ICSharpCode.ILSpy.XmlDoc.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
   at ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   at ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   at ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass17.<DecompileAsync>b__16()
```

Note: I can get no other class in that assembly to decompile but classes are listed correctly.

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
