### ISSUE TITLE
Throws exception when decompiling

### ISSUE THREAD

**Issue by mgwalm** [icsharpcode/ILSpy#446]
ILSpy throws the following exception:

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void MSI.Framework.UI.Application.ApplicationBase::LoadKnownTypes()
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at ICSharpCode.Decompiler.ILAst.StateRangeAnalysis.EnsureLabelAtPos(List`1 body, Int32& pos, Int32& bodyLength)
   at ICSharpCode.Decompiler.ILAst.AsyncDecompiler.AnalyzeStateMachine(ILBlock block)
   at ICSharpCode.Decompiler.ILAst.AsyncDecompiler.Run()
   at ICSharpCode.Decompiler.ILAst.AsyncDecompiler.RunStep1(DecompilerContext context, ILBlock method)
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass17.<DecompileAsync>b__16()

**Comment by siegfriedpammer** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
