### ISSUE TITLE
Decompiler throws exception with *.asmmeta.dll assemblies

### ISSUE THREAD

**Issue by JinShil** [icsharpcode/ILSpy#520]
Decompiling any class in the `System.Windows.Forms.WindowsCE.asmmeta.dll` assembly that comes with Visual Studio 2008 Professional results in the following exception displayed int the code pane:

```
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean System.Windows.Forms.CheckBox::get_AutoCheck()
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDefinition methodDef)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDefinition methodDef, Boolean optimize, DecompilerContext context)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateProperty(PropertyDefinition propDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15()
```

I was able to track this down to the fact that `(byteCode.StackBefore.Length - (byteCode.PopCount ?? byteCode.StackBefore.Length) + byteCode.PushCount)` results in -1 because `byteCode.StackBefore.Length` is 0, `byteCode.PopCount` is 1, and `byteCode.PushCount` is 0.  

Unfortunately, I was not able to understand the algorithm, so I couldn't figure out how to fix it.

**Comment by 0xd4d** [comment]
This occurs because the method is empty (just a `ret` instruction) but the method should return a value (it doesn't). You can add a hack yourself to `ILAstBuilder.cs` @ `List<ByteCode> StackAnalysis(MethodDefinition methodDef)`

```C#
// add this hack after the first foreach loop
			if (body.Count == 1 && body[0].Code == ILCode.Ret)
				body[0].PopCount = 0;
```

These assemblies contain just metadata and no actual code.

**Comment by dgrunwald** [comment]
I don't have `System.Windows.Forms.WindowsCE.asmmeta.dll` handy for testing, but the new decompiler should handle stack underflows more gracefully.
