### ISSUE TITLE
ILSpy's error on save the reference assembly 'mscorlib.dll'

### ISSUE THREAD

**Issue by indexless** [icsharpcode/ILSpy#532]
I downloaded ILSpy sources (ILSpy_2.2.0.1706_Source.zip), built and tried to decompile mscorlib.dll from reference assemblies of .NET 4.0:

> .\ILSpy\ILSpy\bin\Release\ILSpy.exe "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll"

It loaded the assembly (it showed the code on app right window) successfully, but when tried to save it, the app logged the error, in the same right window if it matters. (When I tried to load and saved the non-reference assembly "C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll", nothing 
wrong was happened.) The error log follows:

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Int32 System.Collections.Generic.IArraySortHelperContract`1::System.Collections.Generic.IArraySortHelper<TKey>.BinarySearch(TKey[],System.Int32,System.Int32,TKey,System.Collections.Generic.IComparer`1<TKey>)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDefinition methodDef) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 360
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDefinition methodDef, Boolean optimize, DecompilerContext context) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 220
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 71
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 81
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 781
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 759
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 368
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 255
   at ICSharpCode.ILSpy.CSharpLanguage.<>c__DisplayClass14.<WriteCodeFilesInProject>b__11(IGrouping`2 file) in C:\cygwin64\home\telzhov\sca-luxoft\sca\src\net\ILSpy\ILSpy\Languages\CSharpLanguage.cs:line 482
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)

**Comment by 0xd4d** [comment]
This is a reference assembly and should contain no code. However, at least one method contains code, but it's incomplete and invalid. Open the real mscorlib and try to save that one instead.

BTW, this is the method that caused the crash duing my test. The 2nd instruction is a branch but the target doesn't exist so it's null.

`System.Reflection.PropertyInfo System.DefaultBinder::SelectProperty(System.Reflection.BindingFlags,System.Reflection.PropertyInfo[],System.Type,System.Type[],System.Reflection.ParameterModifier[])`
