### ISSUE TITLE
The process was terminated due to an unhandled exception. (ILSpy won't startup anymore)

### ISSUE THREAD

**Issue by Jockebocke69** [icsharpcode/ILSpy#543]
Application: ILSpy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Configuration.ConfigurationErrorsException
Stack:
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(System.ComponentModel.Composition.Primitives.ImportDefinition)
   at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition, System.Collections.Generic.IEnumerable`1<System.ComponentModel.Composition.Primitives.Export> ByRef)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition, System.Collections.Generic.IEnumerable`1<System.ComponentModel.Composition.Primitives.Export> ByRef)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition, System.ComponentModel.Composition.Hosting.AtomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String)
   at ICSharpCode.ILSpy.Languages.Initialize(System.ComponentModel.Composition.Hosting.CompositionContainer)
   at ICSharpCode.ILSpy.App..ctor()
   at ICSharpCode.ILSpy.App.Main()

**Comment by siegfriedpammer** [comment]
Seems like your installation got corrupted... have you tried redownloading and replacing the files?
You could try resetting your settings by deleting (or renaming) `%AppData%\ICSharpCode\ILSpy.xml`

Hope this helps!

**Comment by Jockebocke69** [comment]
Hi Siegfried,

I solved the enigma .. it was a modification in the machine.config file, that caused ILSpy to not start anymore.
After correcting the xml so it was again well formed, everything was back to normal.

Case closed.

Johan De Bock

**Comment by Jockebocke69** [comment]
Hi Siegfried,

I solved the enigma .. it was a modification in the machine.config file, that caused ILSpy to not start anymore.
After correcting the xml so it was again well formed, everything was back to normal.

Case closed.
