### ISSUE TITLE
Decompilation of certain files crashes ILSpy

### ISSUE THREAD

**Issue by 0xd4d** [icsharpcode/ILSpy#562]
ILSpy version 2.2.0.1817

File: System.IO.FileSystem.dll
Method: System.IO.WinRTFileSystem.OpenAsync

``` text
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Threading.Tasks.Task`1<System.IO.FileStreamBase> System.IO.WinRTFileSystem::OpenAsync(System.String,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,System.Int32,System.IO.FileOptions)
 ---> System.InvalidOperationException: Could not infer any expression
   at ICSharpCode.Decompiler.ILAst.TypeAnalysis.RunInference() in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\TypeAnalysis.cs:line 184
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep) in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 263
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 97
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 71
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 81
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 783
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethod(MethodDefinition method) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 266
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options) in c:\work\ILSpy\ILSpy\Languages\CSharpLanguage.cs:line 100
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in c:\work\ILSpy\ILSpy\TextView\DecompilerTextView.cs:line 508
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15() in c:\work\ILSpy\ILSpy\TextView\DecompilerTextView.cs:line 491
```

File: System.IO.dll
Method: System.IO.StringWriter.MakeCompletedTask

``` text
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Threading.Tasks.Task System.IO.StringWriter::MakeCompletedTask()
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at ICSharpCode.Decompiler.ILAst.StateRangeAnalysis.EnsureLabelAtPos(List`1 body, Int32& pos, Int32& bodyLength) in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\StateRange.cs:line 280
   at ICSharpCode.Decompiler.ILAst.AsyncDecompiler.AnalyzeStateMachine(ILBlock block) in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\AsyncDecompiler.cs:line 393
   at ICSharpCode.Decompiler.ILAst.AsyncDecompiler.Run() in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\AsyncDecompiler.cs:line 106
   at ICSharpCode.Decompiler.ILAst.AsyncDecompiler.RunStep1(DecompilerContext context, ILBlock method) in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\AsyncDecompiler.cs:line 85
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep) in c:\work\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 114
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 97
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 71
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 81
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 783
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethod(MethodDefinition method) in c:\work\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 266
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options) in c:\work\ILSpy\ILSpy\Languages\CSharpLanguage.cs:line 100
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in c:\work\ILSpy\ILSpy\TextView\DecompilerTextView.cs:line 508
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15() in c:\work\ILSpy\ILSpy\TextView\DecompilerTextView.cs:line 491
```

The files are from .NET Native. If you don't have it installed the two files can be found here: http://www.filedropper.com/reqfiles (NOTE: Click on the black "Download This File" button, nothing else)

**Comment by dgrunwald** [comment]
newdecompiler removed both type inference nor goto labels at the ILAst level, so these exceptions can't happen anymore.
