### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.TypeReference' to type 'Mono.Cecil.PointerType'

### ISSUE THREAD

**Issue by jackpoz** [icsharpcode/ILSpy#592]
Decompiling a .NET assembly which contains unmanaged code produces an exception on ILSpy 2.3.0.1827 while it works fine on ILSpy 2.2.0.1706

2.3.0 exception:
```
 ---> System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.TypeReference' to type 'Mono.Cecil.PointerType'.
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.HandlePointerArithmetic(ILNode method)
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddMethod(MethodDefinition method)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15()
```

2.2.0 decompiled code (edited for unrelated reasons):
```
public unsafe void Start(uint sn, int ac)
{
    int num = (int)stackalloc byte[<Module>.__CxxQueryExceptionSize()];
    a.m_sn = sn;
    a.m_ac = ac;
    try
    {
        a.m_ia = IPAddress.Parse(a.m_iAString);
        this.m_p = a.m_ac;
        if (a.m_ac < 12345)
        {
        	this.m_p += a.m_pB;
        }
        a.m_uc = new UC(this.m_p);
        a.m_e = new E(a.m_ia, this.m_p);
        goto IL_C9;
    }
    uint exceptionCode = (uint)Marshal.GetExceptionCode();
    endfilter(<Module>.__CxxExceptionFilter(Marshal.GetExceptionPointers(), null, 0, null));
    IL_C9:
    try
    {
        a.m_uc.JoinMulticastGroup(a.m_ia, 2);
        goto IL_135;
    }
    exceptionCode = (uint)Marshal.GetExceptionCode();
    endfilter(<Module>.__CxxExceptionFilter(Marshal.GetExceptionPointers(), null, 0, null));
    IL_135:
    R.m_udpClient = a.m_uc;
    R.m_mysn = a.m_sn;
    R.m_t = new Thread(new ThreadStart(R.Start));
    R.m_t.IsBackground = true;
    R.m_t.Start();
    a.m_ty = new Timer();
    ElapsedEventHandler value = new ElapsedEventHandler(a.YE);
    a.m_ty.Elapsed += value;
    a.m_ty.Interval = (double)a.m_yi;
    a.m_ty.Start();
    a.Send();
}
```

I'll try this on master as soon as I have time (are there nightly-builds somewhere ?)

**Comment by 0xd4d** [comment]
Seems like it's related to #569

**Comment by jackpoz** [comment]
7e8d010db27debd75ab71514beb868391e8fec53 causes the same exception as on 2.3.0
