### ISSUE TITLE
NullReferenceException during decompilation

### ISSUE THREAD

**Issue by aelij** [icsharpcode/ILSpy#657]
Abbreviated stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.ImportGenericContext.TypeParameter(String type, Int32 position)
   at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportReference(TypeReference type, IGenericParameterProvider context)
   at Reflexil.Editors.TypeAttributesControl.BaseType_Validated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnValidated(EventArgs e)
```

**Comment by siegfriedpammer** [comment]
Seems this is related to https://github.com/sailro/Reflexil and not ILSpy. Would be better to report it there.
