### ISSUE TITLE
In v2.3.2, `Search for t:TypeName, m:Member...` feature doesn't work

### ISSUE THREAD

**Issue by urasandesu** [icsharpcode/ILSpy#692]
In v2.3.2, if using the `Search for t:TypeName, m:Member or c:Constant; use /reg(ular)?Ex(pressions)?/ or both - t:/Type(Name)?/...` feature, ILSpy always crashes: 
![v2 3 2](https://cloud.githubusercontent.com/assets/291065/14586401/e4583c78-04d1-11e6-9f21-19c67a5e37e9.png)
```
---------------------------
Sorry, we crashed
---------------------------
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ICSharpCode.ILSpy.AbstractSearchStrategy.IsMatch(String text)
   at ICSharpCode.ILSpy.TypeSearchStrategy.Search(TypeDefinition type, Language language, Action`1 addResult)
   at ICSharpCode.ILSpy.SearchPane.RunningSearch.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---------------------------
OK   
---------------------------
```

In v2.3.1.1855, the feature worked well. I think this is a regression :disappointed:

**Comment by neolithos** [comment]
I found the problem, I will try to fix it.

**Comment by urasandesu** [comment]
Thanks!! :laughing:
