### ISSUE TITLE
Stack dump on bad label

### ISSUE THREAD

**Issue by danmosemsft** [icsharpcode/ILSpy#719]
Somehow I had an assembly with this content

```
  .method public hidebysig specialname instance class System.Security.Cryptography.X509Certificates.X509ChainPolicy 
          get_ChainPolicy() cil managed
  {
    // Code size       16 (0x10)
    .maxstack  8
    IL_0000:  stind.i2
    IL_0001:  ldind.i4
    IL_0002:  bgt.un     IL_10008

    IL_0007:  nop
    IL_0008:  nop
    IL_0009:  nop
    IL_000a:  nop
    IL_000b:  stloc.2
    IL_000c:  nop
    IL_000d:  nop
    IL_000e:  nop
    IL_000f:  conv.r.un
  } // end of method X509ChainPolicy::get_ChainPolicy

```
Note the branch to missing label. This crashes makes ILspy dump stack. Is that expected, when IL is bad? Or should it ideally say something like "invalid branch" or "missing label"
```

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean System.Security.Cryptography.X509Certificates.X509ChainPolicy ::get_ChainPolicy()
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mono.Collections.Generic.Collection`1.get_Item(Int32 index)
   at ICSharpCode.Decompiler.ILAst.ILCodeUtil.ExpandMacro(ILCode& code, Object& operand, MethodBody methodBody)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDefinition methodDef)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDefinition methodDef, Boolean optimize, DecompilerContext context)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateProperty(PropertyDefinition propDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass31_0.<DecompileAsync>b__0()
```

**Comment by danmosemsft** [comment]
Seems this is really a bug against the assembler then, unless you want a prettier result. Or you want your decompiler to attempt to recover.

**Comment by dgrunwald** [comment]
IL code can be invalid in a large number of ways; we can't guard against all of them in ILSpy.

If the .NET runtime refuses to JIT-compile the method, don't expect ILSpy to decompile it.

**Comment by danmosemsft** [comment]
Fair enough, thanks!
