### ISSUE TITLE
System.InvalidCastException: Cast from Int64 to String not supported.

### ISSUE THREAD

**Issue by justadhiet** [icsharpcode/ILSpy#733]
I am using de4dot 3.1 and always get this error when trying to decompile :

System.InvalidCastException: Cast from Int64 to String not supported.
   at ICSharpCode.NRefactory.Utils.CSharpPrimitiveCast.CSharpPrimitiveCastUnchecked(TypeCode targetType, Object input)
   at ICSharpCode.NRefactory.Utils.CSharpPrimitiveCast.Cast(TypeCode targetType, Object input, Boolean checkForOverflow)
   at ICSharpCode.Decompiler.Ast.AstBuilder.MakePrimitive(Int64 val, TypeReference type)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateExpressionForConstant(Object constant, TypeReference type, Boolean isEnumMemberDeclaration)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateField(FieldDefinition fieldDef)
   at ICSharpCode.ILSpy.CSharpLanguage.AddFieldsAndCtors(AstBuilder codeDomBuilder, TypeDefinition declaringType, Boolean isStatic)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileField(FieldDefinition field, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TreeNodes.FieldTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass31_0.<DecompileAsync>b__0()

please help, thanks..

**Comment by siegfriedpammer** [comment]
Can you tell us what you were trying to decompile? Would make it a lot easier to fix this issue. Thanks!

**Comment by lextm** [comment]
@siegfriedpammer of possible, there should be an issue template to guide users.

**Comment by dgrunwald** [comment]
Closed due to lack of information.
