### ISSUE TITLE
Cannot Decompile ASP.NET Core MVC Razor Precompiled Views

### ISSUE THREAD

**Issue by VahidN** [icsharpcode/ILSpy#779]
The new ASP.NET Core 1.1 tooling, supports creating [ASP.NET Core MVC Razor Precompiled Views](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/), and when I try to decompile its produced .dll file using ILSpy, it throws the following exception:
```
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
I attached a sample here: [Core1RtmEmptyTest.PrecompiledViews.zip](https://github.com/icsharpcode/ILSpy/files/618202/Core1RtmEmptyTest.PrecompiledViews.zip)
If I delete its `.pdb file`, ILSpy is able to decompile it correctly.

**Comment by dgrunwald** [comment]
I recently updated the `newdecompiler` branch to the latest Cecil version, which seems to have fixed this issue.

**Comment by AArnott** [comment]
I don't think CoreCLR assemblies have changed from desktop assemblies. Rather: the PDB that is generated (by default) for .NET Core projects are the new "portable" variety, and this exception is thrown from the PDB reader. So I think it's a (significant) change to support [the new portable PDB format](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md).
