### ISSUE TITLE
Support for net47 Assemblies

### ISSUE THREAD

**Issue by alohaninja** [icsharpcode/ILSpy#808]
When loading .NET 4.7 assemblies in ILSpy you get an error message. Would be great to get this working - .NET 4.7 is becoming more widely supported. 

System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

After more review - it seems to be just this one assembly. Other .NET 4.7 assemblies do load - seems like there are just too many dependencies for it to handle.

**Comment by 0x53A** [comment]
I rather think it is related to the portable pdb format.

You could try to just delete the pdb, so that it doesn't attempt to load it.

**Comment by alohaninja** [comment]
Spot-on! That did the trick. I just had to remove the PDB for it to load. Thanks for the tip and quick response!

**Comment by lextm** [comment]
Duplicate to #789 as they all require latest Cecil.

**Comment by dgrunwald** [comment]
The new decompiler engine (which just landed on the master branch) uses an updated Cecil version.
