### ISSUE TITLE
ILSpy should support portable PBDs

### ISSUE THREAD

**Issue by terrajobst** [icsharpcode/ILSpy#817]
When you try to decompile a class library that uses portable PDBs (e.g. .NET Standard 2.0) ILSpy will crash with an error like this:

```
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Turning of "Use symbol names from PDBs" solves this issue. @jbevain mentioned in https://github.com/jbevain/cecil/issues/411#issuecomment-306067912 that ILSpy should update to Cecil 0.10 to gain portable PDB support.

**Comment by jbevain** [comment]
Cecil 0.10 has a bunch of breaking changes against 0.9. They're documented on the [development log](http://cecil.pe).

**Comment by lextm** [comment]
Related to #779 .

The `newcompiler` branch already contains the fix. Not sure when that branch would be merged to master.

**Comment by jbevain** [comment]
Also the `newdecompiler` branch should update to a newer Cecil, they're at 0.10-beta5 and a lot of work has been done on improving the ppdb support.

**Comment by dgrunwald** [comment]
`newdecompiler` got updated to a newer Cecil; and is now merged to master.
Can you check if your portable PDBs are now working correctly?

**Comment by siegfriedpammer** [comment]
I just tested with a small .net core project. There were no crashes and the symbols were used correctly. I guess that's fixed now.
