### ISSUE TITLE
NullReferenceException for ExpressionBuilder.TranslateTarget

### ISSUE THREAD

**Issue by twenzel** [icsharpcode/ILSpy#862]
When open the Microsoft.AspNetCore 2.0 assembly (`C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.dll, Microsoft.AspNetCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`) and tryo to decompile the WebHost type:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.TranslateTarget(IMember member, ILInstruction target, Boolean nonVirtualInvocation)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.ConvertField(IField field, ILInstruction target)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitLdsFlda(LdsFlda inst, TranslationContext context)
   at ICSharpCode.Decompiler.IL.LdsFlda.AcceptVisitor[C,T](ILVisitor`2 visitor, C context)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitLdObj(LdObj inst, TranslationContext context)
   at ICSharpCode.Decompiler.IL.LdObj.AcceptVisitor[C,T](ILVisitor`2 visitor, C context)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.HandleCallInstruction(CallInstruction inst)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.VisitCallVirt(CallVirt inst, TranslationContext context)
   at ICSharpCode.Decompiler.IL.CallVirt.AcceptVisitor[C,T](ILVisitor`2 visitor, C context)
   at ICSharpCode.Decompiler.CSharp.ExpressionBuilder.Translate(ILInstruction inst, IType typeHint)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Default(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlock(Block block)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitIfInstruction(IfInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertBlockContainer(BlockStatement blockStatement, BlockContainer container, IEnumerable`1 blocks, Boolean isLoop)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.VisitBlockContainer(BlockContainer container)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.ConvertAsBlock(ILInstruction inst)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(MethodDefinition methodDefinition, IMethod method, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions)
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0()

```
ILSpy version 3.0.0.2787

**Comment by siegfriedpammer** [comment]
This is due to missing references, we should not crash, though.
