### ISSUE TITLE
InvalidCastException when decompiling to C#

### ISSUE THREAD

**Issue by MageKing17** [icsharpcode/ILSpy#898]
Trying to decompile [Terraria's dedicated server](http://terraria.org/server/terraria-server-1353.zip) results in the following exception:
```
System.InvalidCastException: Unable to cast object of type 'ICSharpCode.Decompiler.TypeSystem.Implementation.DefaultResolvedEvent' to type 'ICSharpCode.Decompiler.TypeSystem.IProperty'.
   at ICSharpCode.Decompiler.IL.Transforms.AccessPathElement.GetAccessPath(ILInstruction instruction, IType rootType, Dictionary`2 possibleIndexVariables)
   at ICSharpCode.Decompiler.IL.Transforms.TransformCollectionAndObjectInitializers.IsPartOfInitializer(InstructionCollection`1 instructions, Int32 pos, ILVariable target, IType rootType, BlockType& blockType, Dictionary`2 possibleIndexVariables)
   at ICSharpCode.Decompiler.IL.Transforms.TransformCollectionAndObjectInitializers.DoTransform(Block body, Int32 pos)
   at ICSharpCode.Decompiler.IL.Transforms.TransformCollectionAndObjectInitializers.ICSharpCode.Decompiler.IL.Transforms.IStatementTransform.Run(Block block, Int32 pos, StatementTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.StatementTransform.Run(Block block, BlockTransformContext context)
   at ICSharpCode.Decompiler.IL.Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context)
   at ICSharpCode.Decompiler.IL.Transforms.BlockILTransform.Run(ILFunction function, ILTransformContext context)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(MethodDefinition methodDefinition, IMethod method, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, ITypeResolveContext decompilationContext)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types)
   at ICSharpCode.Decompiler.CSharp.WholeProjectDecompiler.<>c__DisplayClass22_0.<WriteCodeFilesInProject>b__1(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

Attempting to decompile individual classes reveals that the problem seems limited to `Terraria.GameContent.UI.Elements.UICharacterListItem`, `Terraria.GameContent.UI.Elements.UIWorldListItem`, `Terraria.GameContent.UI.States.UIManageControls`, and `Terraria.Initializers.UILinksInitializer` (which is rather ironic, because the dedicated server doesn't have a GUI). They decompile to IL just fine, but I can't tell by looking what it's doing that the decompiler isn't liking. Additionally, that last one has a much longer traceback, but it seems to just be calling `VisitBlock()` more times in a row.

**Comment by MageKing17** [comment]
Actually, I think #897 already fixed this.
