### ISSUE TITLE
NullReferenceException when setting FullyQualifyAmbiguousTypeNames=false

### ISSUE THREAD

**Issue by jeremymeng** [icsharpcode/ILSpy#962]
```csharp
using System;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.TypeSystem;

namespace ConsoleApp8
{
    class Program
    {
        static void Main(string[] args)
        {
            var decompiler = new CSharpDecompiler(
                @"C:\vso\yumeng\msil-decompiler-vscode\bin\msildecompiler\Mono.Cecil.dll",
                new DecompilerSettings()
                {
                    FullyQualifyAmbiguousTypeNames = false,
                });
            var name = new FullTypeName("Mono.Cecil.Cil.ILProcessor");
            var typeInfo = decompiler.TypeSystem.Compilation.FindType(name).GetDefinition();
            Console.WriteLine(decompiler.DecompileTypeAsString(name));
        }
    }
}

```
**Actual**:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceExtensionMethods.SetContext() in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Transforms\IntroduceExtensionMethods.cs:line 59
   at ICSharpCode.Decompiler.CSharp.Transforms.IntroduceExtensionMethods.Run(AstNode rootNode, TransformContext context) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\Transforms\IntroduceExtensionMethods.cs:line 47
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.RunTransforms(AstNode rootNode, ITypeResolveContext decompilationContext) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 286
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileType(FullTypeName fullTypeName) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 419
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypeAsString(FullTypeName fullTypeName) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 431
   at ConsoleApp8.Program.Main(String[] args) in C:\Users\yumeng\Documents\Visual Studio 2017\Projects\ConsoleApp8\ConsoleApp8\Program.cs:line 22
```

**Comment by siegfriedpammer** [comment]
What version of the nuget are you using?
