### ISSUE TITLE
Publickeytoken mismatch on Mono.Cecil.Pdb

### ISSUE THREAD

**Issue by smaillet** [icsharpcode/ILSpy#996]
When trying to read an assembly for the decompiler to process I hit a System.FileLoadException (details below) when Mono.Cecil tries to load it's Symbol reader DLL. It is looking for a DLL with a public key token that does not match the actual binary that is packaged with the decompiler. The FQN from the actual binary is: 
`Mono.Cecil.Pdb, Version=0.10.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756`

however Mono.Cecil.DLL is attempting to load:
`Mono.Cecil.Pdb, Version=0.10.0.0, PublicKeyToken=50cebf1cceb9d05e`

Full Exception details:
```
System.IO.FileLoadException occurred
  HResult=0x80131040
  Message=Could not load file or assembly 'Mono.Cecil.Pdb, Version=0.10.0.0, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at Mono.Cecil.Cil.SymbolProvider.GetSymbolType(SymbolKind kind, String fullname) in C:\projects\ilspy\cecil\Mono.Cecil.Cil\Symbols.cs:line 849
   at Mono.Cecil.Cil.SymbolProvider.GetReaderProvider(SymbolKind kind) in C:\projects\ilspy\cecil\Mono.Cecil.Cil\Symbols.cs:line 872
   at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName) in C:\projects\ilspy\cecil\Mono.Cecil.Cil\Symbols.cs:line 786
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) in C:\projects\ilspy\cecil\Mono.Cecil\AssemblyReader.cs:line 103
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters) in C:\projects\ilspy\cecil\Mono.Cecil\AssemblyReader.cs:line 85
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters) in C:\projects\ilspy\cecil\Mono.Cecil\ModuleDefinition.cs:line 1121
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in C:\projects\ilspy\cecil\Mono.Cecil\ModuleDefinition.cs:line 1093
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters) in C:\projects\ilspy\cecil\Mono.Cecil\AssemblyDefinition.cs:line 134
   at CodeGen.Mono.Cecil.AssemblyResolver.LoadAssembly(ReaderParameters readerParams, String path) in C:\Users\smaillet\Documents\Visual Studio 2017\Projects\TestNewDecomp\AssemblyResolver.cs:line 260
   at TestNewDecomp.Program.Main(String[] args) in C:\Users\smaillet\Documents\Visual Studio 2017\Projects\TestNewDecomp\Program.cs:line 40

```

**Comment by siegfriedpammer** [comment]
Where did you obtain the decompiler from? Are you using ILSpy or the decompiler nuget package? The nuget package does not contain `Mono.Cecil.Pdb.dll` at all.

**Comment by christophwille** [comment]
Because there was no further response, I am closing this issue.

For FileLoadException & netstandard NuGets in general, check out https://github.com/dotnet/standard/issues/481
